#!/bin/bash

INC="-I.. -I../.. -I../../game -I../../map_loader -I../../simple_map_gen -I../../misc"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../../game/runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c ../../game/game_array_simple.cpp -o game_array_simple.o
g++ $CXXFLAGS $INC -c ../../misc/map_bit_overlay.cpp -o map_bit_overlay.o
g++ $CXXFLAGS $INC -c test_support.cpp -o test_support.o
g++ $CXXFLAGS $INC -c riv_sys_audit_tester.cpp -o riv_sys_audit_tester.o

g++ $CXXFLAGS -o riv_sys_audit_tester \
    runtime_trace_dbg.o \
    game_array_simple.o \
    map_bit_overlay.o \
    test_support.o \
    riv_sys_audit_tester.o

rm runtime_trace_dbg.o game_array_simple.o map_bit_overlay.o test_support.o riv_sys_audit_tester.o
