#!/bin/bash
set -e

cd "$(dirname "$0")"

LIB_SO="../../data_io/runtime_static_loader_lib.so"
if [ ! -f "$LIB_SO" ]; then
    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
    exit 1
fi

INC="-I. -I.. -I../.. -I../../game -I../../map_loader -I../../simple_map_gen -I../../misc -I../../ai_proc -I../../data_io -I../../static_state"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_loader.cpp -o map_loader.o
g++ $CXXFLAGS $INC -c generate_distance_to_ocean_coast_tm.cpp -o generate_distance_to_ocean_coast_tm.o
g++ $CXXFLAGS $INC -c generate_distance_to_ocean_coast.cpp -o generate_distance_to_ocean_coast.o
g++ $CXXFLAGS $INC -c ../../ai_proc/ai_whiteboard.cpp -o ai_whiteboard.o
g++ $CXXFLAGS $INC -c ../../ai_proc/wb_que_xy.cpp -o wb_que_xy.o
g++ $CXXFLAGS $INC -c generate_distance_to_ocean_coast_tm_tester.cpp -o generate_distance_to_ocean_coast_tm_tester.o

g++ $CXXFLAGS -o generate_distance_to_ocean_coast_tm_tester \
    runtime_static_loader.o \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    generate_distance_to_ocean_coast_tm.o \
    generate_distance_to_ocean_coast.o \
    ai_whiteboard.o \
    wb_que_xy.o \
    generate_distance_to_ocean_coast_tm_tester.o -ldl

rm runtime_static_loader.o map_terrain_validate.o map_terrain_data.o map_loader.o \
    generate_distance_to_ocean_coast_tm.o generate_distance_to_ocean_coast.o \
    ai_whiteboard.o wb_que_xy.o generate_distance_to_ocean_coast_tm_tester.o
