#!/bin/bash

INC="-I. -I.. -I../.. -I../../game -I../../map_loader -I../../simple_map_gen -I../../misc -I../../ai_proc"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../../game/runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c generate_distance_p2p_mk4.cpp -o generate_distance_p2p_mk4.o
g++ $CXXFLAGS $INC -c walk_p2p_mk4.cpp -o walk_p2p_mk4.o
g++ $CXXFLAGS $INC -c ../../ai_proc/ai_whiteboard.cpp -o ai_whiteboard.o
g++ $CXXFLAGS $INC -c ../../ai_proc/wb_que_xy.cpp -o wb_que_xy.o
g++ $CXXFLAGS $INC -c generate_distance_p2p_mk4_minor_ctrl_tester.cpp -o generate_distance_p2p_mk4_minor_ctrl_tester.o

g++ $CXXFLAGS -o generate_distance_p2p_mk4_minor_ctrl_tester \
    runtime_trace_dbg.o \
    generate_distance_p2p_mk4.o \
    walk_p2p_mk4.o \
    ai_whiteboard.o \
    wb_que_xy.o \
    generate_distance_p2p_mk4_minor_ctrl_tester.o -lm

rm runtime_trace_dbg.o generate_distance_p2p_mk4.o walk_p2p_mk4.o \
    ai_whiteboard.o wb_que_xy.o generate_distance_p2p_mk4_minor_ctrl_tester.o
