#!/bin/bash

INC="-I. -I.. -I../.. -I../../game -I../../map_loader -I../../simple_map_gen -I../../misc -I../../ai_proc"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_loader.cpp -o map_loader.o
g++ $CXXFLAGS $INC -c ../../simple_map_gen/generator_constants.cpp -o generator_constants.o
g++ $CXXFLAGS $INC -c ../../simple_map_gen/perlin_noise.cpp -o perlin_noise.o
g++ $CXXFLAGS $INC -c ../../simple_map_gen/generate_overlay_water_land.cpp -o generate_overlay_water_land.o
g++ $CXXFLAGS $INC -c ../../simple_map_gen/water_land_overlay.cpp -o water_land_overlay.o
g++ $CXXFLAGS $INC -c ../../simple_map_gen/cont_indexer.cpp -o cont_indexer.o
g++ $CXXFLAGS $INC -c ../../game/runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c generate_distance_p2p_mk4.cpp -o generate_distance_p2p_mk4.o
g++ $CXXFLAGS $INC -c walk_p2p_mk4.cpp -o walk_p2p_mk4.o
g++ $CXXFLAGS $INC -c ../../ai_proc/ai_whiteboard.cpp -o ai_whiteboard.o
g++ $CXXFLAGS $INC -c ../../ai_proc/wb_que_xy.cpp -o wb_que_xy.o
g++ $CXXFLAGS $INC -c walk_p2p_mk4_tester.cpp -o walk_p2p_mk4_tester.o

g++ $CXXFLAGS -o walk_p2p_mk4_tester \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    generator_constants.o \
    perlin_noise.o \
    generate_overlay_water_land.o \
    water_land_overlay.o \
    cont_indexer.o \
    runtime_trace_dbg.o \
    generate_distance_p2p_mk4.o \
    walk_p2p_mk4.o \
    ai_whiteboard.o \
    wb_que_xy.o \
    walk_p2p_mk4_tester.o -lm

rm map_terrain_validate.o map_terrain_data.o map_loader.o \
    generator_constants.o perlin_noise.o generate_overlay_water_land.o water_land_overlay.o cont_indexer.o \
    runtime_trace_dbg.o generate_distance_p2p_mk4.o walk_p2p_mk4.o \
    ai_whiteboard.o wb_que_xy.o walk_p2p_mk4_tester.o
