//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py from TEMPLATE_general_assessor.cpp
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include "bit_array.h"
#include "assert_log.h"
#include "general_assessor.h"
#include "general_bit_bank.h"
#include "tile_req_chk.h"
[ASSESS_INCLUDES_TAG]

//================================================================================================================================
//=> - GeneralAssessor implementation -
//================================================================================================================================

static bool chk_bit (const BitArrayCL* ba, u16 idx) {
    if (ba == nullptr) {
        return false;
    }
    if (idx >= ba->get_count()) {
        return false;
    }
    return ba->get_bit(idx) == 1;
}

static bool chk_bank (const GeneralBitBank* bank, u16 city_idx, u16 flag_idx) {
    if (bank == nullptr) {
        return false;
    }
    return bank->is_flagged(city_idx, flag_idx);
}

static bool chk_resource (const AssessorCtx& ctx, u16 idx) {
    if (ctx.m_resource_bank != nullptr) {
        return chk_bank(ctx.m_resource_bank, ctx.m_city_idx, idx);
    }
    return chk_bit(ctx.m_resource, idx);
}

static bool chk_building (const AssessorCtx& ctx, u16 idx) {
    if (ctx.m_building_bank != nullptr) {
        return chk_bank(ctx.m_building_bank, ctx.m_city_idx, idx);
    }
    return chk_bit(ctx.m_building, idx);
}

static bool chk_toggle_city (const AssessorCtx& ctx, u16 idx) {
    if (ctx.m_toggle_city_bank != nullptr) {
        return chk_bank(ctx.m_toggle_city_bank, ctx.m_city_idx, idx);
    }
    return chk_bit(ctx.m_toggle_city, idx);
}

bool GeneralAssessor::chk (const ItemReqsStruct& reqs, const AssessorCtx& ctx) {
    for (u32 j = 0; j < MAX_PREREQ_COUNT; ++j) {
        const u8 tp = reqs.types[j];
        if (tp == ITEM_REQ_TYPE_NONE) {
            break;
        }
        const u16 ix = reqs.indices[j];
        if (ix == U16_KEY_NULL) {
            return false;
        }
        switch (tp) {
            [CHK_SWITCH_CASES_TAG]
            case ITEM_REQ_TYPE_TILE:
                if (!TileReqChk::chk_req(reqs.added_args[j], ix, ctx)) {
                    return false;
                }
                break;
            default:
                return false;
        }
    }
    return true;
}

[ASSESS_IMPLEMENTATIONS_TAG]

#ifdef TILE_REQ_CHK_STUB

bool TileReqChk::chk_req (u8, u16, const AssessorCtx&) {
    return false;
}

bool TileReqChk::chk_reqs (const ItemReqsStruct& reqs, const AssessorCtx& ctx) {
    for (u32 j = 0; j < MAX_PREREQ_COUNT; ++j) {
        if (reqs.types[j] == ITEM_REQ_TYPE_NONE) {
            break;
        }
        if (reqs.types[j] == ITEM_REQ_TYPE_TILE) {
            if (!chk_req(reqs.added_args[j], reqs.indices[j], ctx)) {
                return false;
            }
        }
    }
    return true;
}

#else

#include "tile_req_chk.cpp"

#endif

//================================================================================================================================
//=> - End -
//================================================================================================================================
