//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py from TEMPLATE_general_assessor.cpp
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include "bit_array.h"
#include "general_assessor.h"

//================================================================================================================================
//=> - GeneralAssessor implementation -
//================================================================================================================================

static bool chk_bit (const BitArrayCL* ba, u16 idx) {
    if (ba == nullptr) {
        return false;
    }
    if (idx >= ba->get_count()) {
        return false;
    }
    return ba->get_bit(idx) == 1;
}

bool GeneralAssessor::chk (const ItemReqsStruct& reqs, const AssessorCtx& ctx) {
    for (u32 j = 0; j < MAX_PREREQ_COUNT; ++j) {
        const u8 tp = reqs.types[j];
        if (tp == ITEM_REQ_TYPE_NONE) {
            break;
        }
        const u16 ix = reqs.indices[j];
        if (ix == U16_KEY_NULL) {
            return false;
        }
        switch (tp) {
            [CHK_SWITCH_CASES_TAG]
            default:
                return false;
        }
    }
    return true;
}

BitArrayCL* GeneralAssessor::assess (u16 item_count, const ItemReqsStruct* reqs_per_item, const AssessorCtx& ctx) {
    BitArrayCL* result = new BitArrayCL(item_count);
    if (reqs_per_item == nullptr) {
        return result;
    }
    for (u16 i = 0; i < item_count; ++i) {
        if (chk(reqs_per_item[i], ctx)) {
            result->set_bit(i);
        }
    }
    return result;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
