//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py from TEMPLATE_assessor_brute_shared.cpp
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include <cstdio>
#include <cstring>

#include "assessor_brute_shared.h"
#include "assessor_brute_write.h"
#include "general_assessor.h"
#include "bit_array.h"
#include "static_parsing_manager.h"

//================================================================================================================================
//=> - InferredReqs helpers -
//================================================================================================================================

static void add_u16 (u16* arr, u8* n, u16 v) {
    for (u8 i = 0; i < *n; ++i) {
        if (arr[i] == v) {
            return;
        }
    }
    if (*n < BRUTE_MAX_PER_TYPE) {
        arr[*n] = v;
        ++(*n);
    }
}

static void add_en (EnSlot& slot, u16 item_idx) {
    for (u16 i = 0; i < slot.m_n; ++i) {
        if (slot.m_items[i] == item_idx) {
            return;
        }
    }
    if (slot.m_n < BRUTE_MAX_ENABLED) {
        slot.m_items[slot.m_n] = item_idx;
        ++slot.m_n;
    }
}

static void set_all ([SET_ALL_PARAMS_TAG]) {
    [SET_ALL_BITS_TAG]
}

static void free_en_map (EnablesMap& en) {
    [FREE_EN_MAP_TAG]
}

static EnablesMap make_en_map ([MAKE_EN_MAP_ARGS_TAG]) {
    EnablesMap en = {};
    [MAKE_EN_MAP_INIT_TAG]
    return en;
}

//================================================================================================================================
//=> - AssessorBrute implementation -
//================================================================================================================================

int AssessorBrute::run (const StaticParsingManager& mgr, const BruteRunCfg& cfg) {
    if (cfg.m_item_count == 0 || cfg.m_reqs == nullptr) {
        return 0;
    }

    [RUN_LOCAL_COUNTS_TAG]

    [RUN_BITARRAY_DECL_TAG]

    InferredReqs* inferred = new InferredReqs[cfg.m_item_count];
    for (u16 i = 0; i < cfg.m_item_count; ++i) {
        inferred[i] = {};
    }
    EnablesMap en = make_en_map([MAKE_EN_MAP_CALL_TAG]);
    auto snap = [&](AssessorCtx& ctx) {
        [RUN_CTX_SNAP_TAG]
    };
    bool building_for_ablation = cfg.m_init_building_all || cfg.m_building_isolate;
    auto set_base = [&]() {
        set_all([SET_ALL_CALL_TAG]);
    };
    AssessorCtx ctx = {};
    snap(ctx);
    set_base();
    BitArrayCL* baseline = GeneralAssessor::assess(cfg.m_item_count, cfg.m_reqs, ctx);

    [ABLATION_LOOPS_TAG]

    [BUILDING_ISOLATE_TAG]

    delete baseline;
    int rc_out = 0;
    if (cfg.m_results_to_match_path != nullptr) {
        FILE* out = std::fopen(cfg.m_results_to_match_path, "w");
        if (out == nullptr) {
            rc_out = 1;
        } else {
            for (u16 i = 0; i < cfg.m_item_count; ++i) {
                if (cfg.m_emit_line != nullptr) {
                    cfg.m_emit_line(out, i, inferred[i], cfg.m_emit_ud);
                }
            }
            std::fclose(out);
        }
    }
    if (cfg.m_results_readable_path != nullptr) {
        FILE* rout = std::fopen(cfg.m_results_readable_path, "w");
        if (rout == nullptr) {
            rc_out = 1;
        } else {
            AssessorBruteWrite::write_readable(rout, en, mgr, cfg);
            std::fclose(rout);
        }
    }
    delete[] inferred;
    free_en_map(en);
    return rc_out;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
