#!/bin/bash

INC="-I.."

g++ -std=c++11 $INC -c perlin_noise.cpp -o perlin_noise.o
g++ -std=c++11 $INC -c generator_constants.cpp -o generator_constants.o
g++ -std=c++11 $INC -c generate_terrain_cont_pn.cpp -o generate_terrain_cont_pn.o
g++ -std=c++11 $INC -c generate_terrain_combo_add.cpp -o generate_terrain_combo_add.o
g++ -std=c++11 $INC -c generate_overlay_water_land.cpp -o generate_overlay_water_land.o
g++ -std=c++11 $INC -c generate_map_continents_basic.cpp -o generate_map_continents_basic.o
g++ -std=c++11 $INC -c generate_map_continents_basic_tester.cpp -o generate_map_continents_basic_tester.o

g++ -std=c++11 -o generate_map_continents_basic_tester \
    perlin_noise.o \
    generator_constants.o \
    generate_terrain_cont_pn.o \
    generate_terrain_combo_add.o \
    generate_overlay_water_land.o \
    generate_map_continents_basic.o \
    generate_map_continents_basic_tester.o \
    -lm

rm perlin_noise.o \
    generator_constants.o \
    generate_terrain_cont_pn.o \
    generate_terrain_combo_add.o \
    generate_overlay_water_land.o \
    generate_map_continents_basic.o \
    generate_map_continents_basic_tester.o
