#!/bin/bash

INC="-I.."

g++ -std=c++11 $INC -c perlin_noise.cpp -o perlin_noise.o
g++ -std=c++11 $INC -c generator_constants.cpp -o generator_constants.o
g++ -std=c++11 $INC -c generate_latitude_overlay.cpp -o generate_latitude_overlay.o
g++ -std=c++11 $INC -c generate_latitude_overlay_tester.cpp -o generate_latitude_overlay_tester.o

g++ -std=c++11 -o generate_latitude_overlay_tester \
    perlin_noise.o \
    generator_constants.o \
    generate_latitude_overlay.o \
    generate_latitude_overlay_tester.o \
    -lm

rm perlin_noise.o \
    generator_constants.o \
    generate_latitude_overlay.o \
    generate_latitude_overlay_tester.o
