#!/bin/bash

INC="-I.."

g++ -std=c++11 $INC -c perlin_noise.cpp -o perlin_noise.o
g++ -std=c++11 $INC -c generator_constants.cpp -o generator_constants.o
g++ -std=c++11 $INC -c generate_terrain_cont_pn.cpp -o generate_terrain_cont_pn.o
g++ -std=c++11 $INC -c generate_terrain_cont_pn_var_lac_tester.cpp -o generate_terrain_cont_pn_var_lac_tester.o

g++ -std=c++11 -o generate_terrain_cont_pn_var_lac_tester \
    perlin_noise.o generator_constants.o generate_terrain_cont_pn.o \
    generate_terrain_cont_pn_var_lac_tester.o -lm

rm perlin_noise.o generator_constants.o generate_terrain_cont_pn.o \
    generate_terrain_cont_pn_var_lac_tester.o
