#!/bin/bash

INC="-I.."

g++ -std=c++11 $INC -c perlin_noise.cpp -o perlin_noise.o
g++ -std=c++11 $INC -c generator_constants.cpp -o generator_constants.o
g++ -std=c++11 $INC -c generate_overlay_water_land.cpp -o generate_overlay_water_land.o
g++ -std=c++11 $INC -c generate_distance_land_to_water.cpp -o generate_distance_land_to_water.o
g++ -std=c++11 $INC -c generate_terrain_cont_pn.cpp -o generate_terrain_cont_pn.o
g++ -std=c++11 $INC -c generate_terrain_cont_outline.cpp -o generate_terrain_cont_outline.o
g++ -std=c++11 $INC -c generate_terrain_rotation.cpp -o generate_terrain_rotation.o
g++ -std=c++11 $INC -c generate_small_shape.cpp -o generate_small_shape.o
g++ -std=c++11 $INC -c generate_small_shape_tester.cpp -o generate_small_shape_tester.o

g++ -std=c++11 -o generate_small_shape_tester \
    perlin_noise.o \
    generator_constants.o \
    generate_overlay_water_land.o \
    generate_distance_land_to_water.o \
    generate_terrain_cont_pn.o \
    generate_terrain_cont_outline.o \
    generate_terrain_rotation.o \
    generate_small_shape.o \
    generate_small_shape_tester.o \
    -lm

rm perlin_noise.o \
    generator_constants.o \
    generate_overlay_water_land.o \
    generate_distance_land_to_water.o \
    generate_terrain_cont_pn.o \
    generate_terrain_cont_outline.o \
    generate_terrain_rotation.o \
    generate_small_shape.o \
    generate_small_shape_tester.o
