#!/bin/bash

INC="-I.. -I../map_loader -I../simple_map_gen"

g++ -std=c++11 $INC -c ../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ -std=c++11 $INC -c ../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ -std=c++11 $INC -c ../map_loader/map_loader.cpp -o map_loader.o
g++ -std=c++11 $INC -c generator_whiteboard.cpp -o generator_whiteboard.o
g++ -std=c++11 $INC -c generate_area_index.cpp -o generate_area_index.o
g++ -std=c++11 $INC -c generate_generic_depth_overlay.cpp -o generate_generic_depth_overlay.o
g++ -std=c++11 $INC -c generate_mtn_range.cpp -o generate_mtn_range.o
g++ -std=c++11 $INC -c generate_mtn_range_tester.cpp -o generate_mtn_range_tester.o

g++ -std=c++11 -o generate_mtn_range_tester \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    generator_whiteboard.o \
    generate_area_index.o \
    generate_generic_depth_overlay.o \
    generate_mtn_range.o \
    generate_mtn_range_tester.o \
    -lm

rm map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    generator_whiteboard.o \
    generate_area_index.o \
    generate_generic_depth_overlay.o \
    generate_mtn_range.o \
    generate_mtn_range_tester.o
