#!/bin/bash

INC="-I.. -I../map_loader -I../simple_map_gen"

g++ -std=c++11 $INC -c ../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ -std=c++11 $INC -c ../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ -std=c++11 $INC -c ../map_loader/map_loader.cpp -o map_loader.o
g++ -std=c++11 $INC -c perlin_noise.cpp -o perlin_noise.o
g++ -std=c++11 $INC -c generator_constants.cpp -o generator_constants.o
g++ -std=c++11 $INC -c generate_open_distance_to_water.cpp -o generate_open_distance_to_water.o
g++ -std=c++11 $INC -c generate_open_distance_to_water_tester.cpp -o generate_open_distance_to_water_tester.o

g++ -std=c++11 -o generate_open_distance_to_water_tester \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    perlin_noise.o \
    generator_constants.o \
    generate_open_distance_to_water.o \
    generate_open_distance_to_water_tester.o \
    -lm

rm map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    perlin_noise.o \
    generator_constants.o \
    generate_open_distance_to_water.o \
    generate_open_distance_to_water_tester.o
