#!/bin/bash

INC="-I.. -I../map_loader -I../simple_map_gen"

g++ -std=c++11 $INC -c ../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ -std=c++11 $INC -c ../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ -std=c++11 $INC -c ../map_loader/map_loader.cpp -o map_loader.o
g++ -std=c++11 $INC -c perlin_noise.cpp -o perlin_noise.o
g++ -std=c++11 $INC -c generate_generic_depth_overlay.cpp -o generate_generic_depth_overlay.o
g++ -std=c++11 $INC -c generate_generic_depth_overlay_tester.cpp -o generate_generic_depth_overlay_tester.o

g++ -std=c++11 -o generate_generic_depth_overlay_tester \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    perlin_noise.o \
    generate_generic_depth_overlay.o \
    generate_generic_depth_overlay_tester.o \
    -lm

rm map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    perlin_noise.o \
    generate_generic_depth_overlay.o \
    generate_generic_depth_overlay_tester.o
