#!/bin/bash

INC="-I.. -I../map_loader -I../simple_map_gen"

g++ -std=c++11 $INC -c ../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ -std=c++11 $INC -c ../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ -std=c++11 $INC -c ../map_loader/map_loader.cpp -o map_loader.o
g++ -std=c++11 $INC -c perlin_noise.cpp -o perlin_noise.o
g++ -std=c++11 $INC -c generator_constants.cpp -o generator_constants.o
g++ -std=c++11 $INC -c generator_whiteboard.cpp -o generator_whiteboard.o
g++ -std=c++11 $INC -c generate_global_ocean.cpp -o generate_global_ocean.o
g++ -std=c++11 $INC -c generate_river_pts.cpp -o generate_river_pts.o
g++ -std=c++11 $INC -c generate_river_sectors.cpp -o generate_river_sectors.o
g++ -std=c++11 $INC -c generate_river_network.cpp -o generate_river_network.o
g++ -std=c++11 $INC -c generate_river_lines.cpp -o generate_river_lines.o
g++ -std=c++11 $INC -c generate_distance_to_river.cpp -o generate_distance_to_river.o
g++ -std=c++11 $INC -c generate_open_distance_to_water.cpp -o generate_open_distance_to_water.o
g++ -std=c++11 $INC -c generate_plain_distance_to_water.cpp -o generate_plain_distance_to_water.o
g++ -std=c++11 $INC -c generate_latitude_overlay.cpp -o generate_latitude_overlay.o
g++ -std=c++11 $INC -c generate_map_climate.cpp -o generate_map_climate.o
g++ -std=c++11 $INC -c generate_map_climate_tester.cpp -o generate_map_climate_tester.o

g++ -std=c++11 -o generate_map_climate_tester \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    perlin_noise.o \
    generator_constants.o \
    generator_whiteboard.o \
    generate_global_ocean.o \
    generate_river_pts.o \
    generate_river_sectors.o \
    generate_river_network.o \
    generate_river_lines.o \
    generate_distance_to_river.o \
    generate_open_distance_to_water.o \
    generate_plain_distance_to_water.o \
    generate_latitude_overlay.o \
    generate_map_climate.o \
    generate_map_climate_tester.o \
    -lm

rm map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    perlin_noise.o \
    generator_constants.o \
    generator_whiteboard.o \
    generate_global_ocean.o \
    generate_river_pts.o \
    generate_river_sectors.o \
    generate_river_network.o \
    generate_river_lines.o \
    generate_distance_to_river.o \
    generate_open_distance_to_water.o \
    generate_plain_distance_to_water.o \
    generate_latitude_overlay.o \
    generate_map_climate.o \
    generate_map_climate_tester.o
