#!/bin/bash

INC="-I.."

g++ -std=c++11 $INC -c perlin_noise.cpp -o perlin_noise.o
g++ -std=c++11 $INC -c generator_constants.cpp -o generator_constants.o
g++ -std=c++11 $INC -c generate_terrain_cont_pn.cpp -o generate_terrain_cont_pn.o
g++ -std=c++11 $INC -c water_land_overlay.cpp -o water_land_overlay.o
g++ -std=c++11 $INC -c map_combiner.cpp -o map_combiner.o
g++ -std=c++11 $INC -c map_composer.cpp -o map_composer.o
g++ -std=c++11 $INC -c map_composer_tester.cpp -o map_composer_tester.o

g++ -std=c++11 -o map_composer_tester perlin_noise.o generator_constants.o generate_terrain_cont_pn.o water_land_overlay.o map_combiner.o map_composer.o map_composer_tester.o -lm

rm perlin_noise.o generator_constants.o generate_terrain_cont_pn.o water_land_overlay.o map_combiner.o map_composer.o map_composer_tester.o
