//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py from PREFIX_effector.h
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef CIV_EFFECTOR_H
#define CIV_EFFECTOR_H

#include "effect_map.h"

//================================================================================================================================
//=> - CivEffector class -
//================================================================================================================================

class CivEffector {
public:
    CivEffector ();
    ~CivEffector ();
    void parse (const EffectMapStruct* rows, u16 row_count);
    void take_ownership ();
    u16 get_count () const;
    const EffectMapStruct* get_rows () const;

private:
    CivEffector (const CivEffector& other) = delete;
    CivEffector (CivEffector&& other) = delete;
    CivEffector& operator= (const CivEffector& other) = delete;
    CivEffector& operator= (CivEffector&& other) = delete;
    void clear ();
    u16 m_count;
    EffectMapStruct* m_rows;
};

#endif // CIV_EFFECTOR_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
