//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py from PREFIX_effector.cpp
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include "[FILE_TAG]_effector.h"
#include "effect_scoper_common.h"

//================================================================================================================================
//=> - [SCOPE_CLASS] implementation -
//================================================================================================================================

[SCOPE_CLASS]::[SCOPE_CLASS] () :
    m_count(0),
    m_rows(nullptr) {
}

[SCOPE_CLASS]::~[SCOPE_CLASS] () {
    clear();
}

void [SCOPE_CLASS]::clear () {
    delete[] m_rows;
    m_rows = nullptr;
    m_count = 0;
}

void [SCOPE_CLASS]::parse (const EffectMapStruct* rows, u16 row_count) {
    clear();
    copy_scope_rows(rows, row_count, ItemEffectsScope::[SCOPE_ENUM], &m_rows, &m_count);
}

void [SCOPE_CLASS]::take_ownership () {
    if (m_rows == nullptr || m_count == 0) {
        return;
    }
    EffectMapStruct* tmp = m_rows;
    m_rows = new EffectMapStruct[m_count];
    for (u16 i = 0; i < m_count; ++i) {
        m_rows[i] = tmp[i];
    }
    delete[] tmp;
}

u16 [SCOPE_CLASS]::get_count () const {
    return m_count;
}

const EffectMapStruct* [SCOPE_CLASS]::get_rows () const {
    return m_rows;
}

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
