#!/bin/bash
set -e

cd "$(dirname "$0")"

LIB_SO="../../data_io/runtime_static_loader_lib.so"
if [ ! -f "$LIB_SO" ]; then
    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
    exit 1
fi

INC="-I.. -I../.. -I../../misc -I../../data_io -I../../static_state -I../../map_loader -I../../simple_map_gen -I../../adv_map_gen -I../../city -I../../city/assessor -I../../city/effector -I../../gen_bit_banks -I../../game"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_loader.cpp -o map_loader.o
g++ $CXXFLAGS $INC -c ../runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c ../game_array_simple.cpp -o game_array_simple.o
g++ $CXXFLAGS $INC -c ../factory_game_array_simple.cpp -o factory_game_array_simple.o
g++ $CXXFLAGS $INC -c aux_res_imp_terrain_tester.cpp -o aux_res_imp_terrain_tester.o

g++ $CXXFLAGS -o aux_res_imp_terrain_tester \
    runtime_static_loader.o \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    runtime_trace_dbg.o \
    game_array_simple.o \
    factory_game_array_simple.o \
    aux_res_imp_terrain_tester.o \
    -ldl \
    $LIB_SO \
    -Wl,-rpath,'$ORIGIN/../../data_io'

./aux_res_imp_terrain_tester "$@"

rm runtime_static_loader.o map_terrain_validate.o map_terrain_data.o map_loader.o \
    runtime_trace_dbg.o game_array_simple.o factory_game_array_simple.o \
    aux_res_imp_terrain_tester.o aux_res_imp_terrain_tester
