#!/bin/bash
set -e

cd "$(dirname "$0")"

LIB_SO="../../data_io/runtime_static_loader_lib.so"
if [ ! -f "$LIB_SO" ]; then
    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
    exit 1
fi

INC="-I../.. \
     -I../../misc \
     -I../../data_io \
     -I../../static_state \
     -I../../city \
     -I../../city/assessor \
     -I../../city/effector \
     -I../../dyn_state \
     -I../../gen_bit_banks \
     -I../../ai_pathing/walk_general \
     -I../../map_loader \
     -I../../simple_map_gen \
     -I.."
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
g++ $CXXFLAGS $INC -c ../../misc/bit_array.cpp -o bit_array.o
g++ $CXXFLAGS $INC -c ../../misc/map_bit_overlay.cpp -o map_bit_overlay.o
g++ $CXXFLAGS $INC -c ../../misc/map_bit_array_overlay.cpp -o map_bit_array_overlay.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ $CXXFLAGS $INC -c ../runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c ../../gen_bit_banks/general_bit_bank.cpp -o general_bit_bank.o
g++ $CXXFLAGS $INC -c ../../city/assessor/general_assessor.cpp -o general_assessor.o
g++ $CXXFLAGS $INC -c ../../city/effect_ctx.cpp -o effect_ctx.o
g++ $CXXFLAGS $INC -c ../../city/effector/effect_enabler.cpp -o effect_enabler.o
g++ $CXXFLAGS $INC -c ../../city/effector/booster_effect_register.cpp -o booster_effect_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/local_unit_exp_booster_register.cpp -o local_unit_exp_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/civ_ship_training_booster_register.cpp -o civ_ship_training_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/city_commerce_booster_register.cpp -o city_commerce_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/city_production_booster_register.cpp -o city_production_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/local_production_booster_register.cpp -o local_production_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/local_pop_growth_booster_register.cpp -o local_pop_growth_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/local_commerce_booster_register.cpp -o local_commerce_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/city_pop_growth_booster_register.cpp -o city_pop_growth_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/civ_pop_growth_booster_register.cpp -o civ_pop_growth_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/city_culture_booster_register.cpp -o city_culture_booster_register.o
g++ $CXXFLAGS $INC -c ../../dyn_state/unit_add_vector.cpp -o unit_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/unit_movement_mng.cpp -o unit_movement_mng.o
g++ $CXXFLAGS $INC -c ../player_ledger.cpp -o player_ledger.o
g++ $CXXFLAGS $INC -c ../tile_yields.cpp -o tile_yields.o
g++ $CXXFLAGS $INC -c ../tile_working.cpp -o tile_working.o
g++ $CXXFLAGS $INC -c ../tile_attr_tables.cpp -o tile_attr_tables.o
g++ $CXXFLAGS $INC -c ../game_array_simple.cpp -o game_array_simple.o
g++ $CXXFLAGS $INC -c ../civ_relations.cpp -o civ_relations.o
g++ $CXXFLAGS $INC -c ../../city/circular_tile_areas.cpp -o circular_tile_areas.o
g++ $CXXFLAGS $INC -c ../../city/city_border.cpp -o city_border.o
g++ $CXXFLAGS $INC -c ../../city/city.cpp -o city.o
g++ $CXXFLAGS $INC -c ../city_array.cpp -o city_array.o
g++ $CXXFLAGS $INC -c city_array_tester.cpp -o city_array_tester.o

g++ $CXXFLAGS -o city_array_tester \
    runtime_static_loader.o \
    bit_array.o \
    map_bit_overlay.o \
    map_bit_array_overlay.o \
    map_terrain_validate.o \
    runtime_trace_dbg.o \
    general_bit_bank.o \
    general_assessor.o \
    effect_ctx.o \
    effect_enabler.o \
    booster_effect_register.o \
    local_unit_exp_booster_register.o \
    civ_ship_training_booster_register.o \
    city_commerce_booster_register.o \
    city_production_booster_register.o \
    local_production_booster_register.o \
    local_pop_growth_booster_register.o \
    local_commerce_booster_register.o \
    city_pop_growth_booster_register.o \
    civ_pop_growth_booster_register.o \
    city_culture_booster_register.o \
    unit_add_vector.o \
    unit_movement_mng.o \
    player_ledger.o \
    tile_yields.o \
    tile_working.o \
    tile_attr_tables.o \
    game_array_simple.o \
    civ_relations.o \
    circular_tile_areas.o \
    city_border.o \
    city.o \
    city_array.o \
    city_array_tester.o \
    -ldl \
    $LIB_SO \
    -Wl,-rpath,'$ORIGIN/../../data_io'

./city_array_tester

rm -f runtime_static_loader.o bit_array.o map_bit_overlay.o map_bit_array_overlay.o map_terrain_validate.o \
    runtime_trace_dbg.o general_bit_bank.o general_assessor.o effect_ctx.o effect_enabler.o booster_effect_register.o \
    local_unit_exp_booster_register.o civ_ship_training_booster_register.o \
    city_commerce_booster_register.o city_production_booster_register.o \
    local_production_booster_register.o local_pop_growth_booster_register.o \
    local_commerce_booster_register.o city_pop_growth_booster_register.o \
    civ_pop_growth_booster_register.o city_culture_booster_register.o \
    unit_add_vector.o unit_movement_mng.o player_ledger.o tile_yields.o tile_working.o \
    tile_attr_tables.o game_array_simple.o civ_relations.o circular_tile_areas.o city_border.o city.o \
    city_array.o city_array_tester.o
