#!/bin/bash
set -e

cd "$(dirname "$0")"

INC="-I.. -I../.."
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c runtime_trace_dbg_tester.cpp -o runtime_trace_dbg_tester.o

g++ $CXXFLAGS -o runtime_trace_dbg_tester \
    runtime_trace_dbg.o \
    runtime_trace_dbg_tester.o

./runtime_trace_dbg_tester

rm runtime_trace_dbg.o runtime_trace_dbg_tester.o
