#!/bin/bash
set -e

cd "$(dirname "$0")"

LIB_SO="../../data_io/runtime_static_loader_lib.so"
if [ ! -f "$LIB_SO" ]; then
    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
    exit 1
fi

INC="-I../.. \
     -I../../misc \
     -I../../data_io \
     -I../../static_state \
     -I.."
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
g++ $CXXFLAGS $INC -c ../building_trait_attribution.cpp -o building_trait_attribution.o
g++ $CXXFLAGS $INC -c ../civ_trait_affinity.cpp -o civ_trait_affinity.o
g++ $CXXFLAGS $INC -c ../tech_trait_attribution.cpp -o tech_trait_attribution.o
g++ $CXXFLAGS $INC -c tech_trait_attribution_tester.cpp -o tech_trait_attribution_tester.o

g++ $CXXFLAGS -o tech_trait_attribution_tester \
    runtime_static_loader.o \
    building_trait_attribution.o \
    civ_trait_affinity.o \
    tech_trait_attribution.o \
    tech_trait_attribution_tester.o \
    -ldl \
    $LIB_SO \
    -Wl,-rpath,'$ORIGIN/../../data_io'

./tech_trait_attribution_tester

rm -f runtime_static_loader.o building_trait_attribution.o civ_trait_affinity.o \
    tech_trait_attribution.o tech_trait_attribution_tester.o
