#!/bin/bash
set -e

cd "$(dirname "$0")"

LIB_SO="../../data_io/runtime_static_loader_lib.so"
if [ ! -f "$LIB_SO" ]; then
    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
    exit 1
fi

WORK_MK="${TILE_WORK_ASSESSOR_MK:-mk01}"
WORK_REL="impl/tile_work_assessor_impl_${WORK_MK}.cpp"
WORK_ABS="../${WORK_REL}"
if [ ! -f "$WORK_ABS" ]; then
    echo "missing impl $WORK_ABS"
    exit 1
fi

YLD_MK="${TILE_YIELDS_MK:-mk01}"
YLD_REL="impl/tile_yields_impl_${YLD_MK}.cpp"
YLD_ABS="../${YLD_REL}"
if [ ! -f "$YLD_ABS" ]; then
    echo "missing impl $YLD_ABS"
    exit 1
fi

INC="-I.. -I../.. -I../../misc -I../../data_io -I../../static_state -I../../map_loader -I../../simple_map_gen -I../../adv_map_gen -I../../city -I../../city/assessor -I../../city/effector -I../../gen_bit_banks -I../../game"
CXXFLAGS="-std=c++17 -Wall -Wextra"
CXXFLAGS="$CXXFLAGS -DTILE_WORK_ASSESSOR_IMPL=\"${WORK_REL}\""
CXXFLAGS="$CXXFLAGS -DTILE_WORK_ASSESSOR_IMPL_TAG=\"${WORK_MK}\""
CXXFLAGS="$CXXFLAGS -DTILE_WORK_ASSESSOR_MK=\"${WORK_MK}\""
CXXFLAGS="$CXXFLAGS -DTILE_YIELDS_IMPL=\"${YLD_REL}\""
CXXFLAGS="$CXXFLAGS -DTILE_YIELDS_IMPL_TAG=\"${YLD_MK}\""
CXXFLAGS="$CXXFLAGS -DTILE_YIELDS_MK=\"${YLD_MK}\""

g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_loader.cpp -o map_loader.o
g++ $CXXFLAGS $INC -c ../runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c ../../misc/bit_array.cpp -o bit_array.o
g++ $CXXFLAGS $INC -c ../game_array_simple.cpp -o game_array_simple.o
g++ $CXXFLAGS $INC -c ../factory_game_array_simple.cpp -o factory_game_array_simple.o
g++ $CXXFLAGS $INC -c ../std_add_helper.cpp -o std_add_helper.o
g++ $CXXFLAGS $INC -c ../tile_attr_tables.cpp -o tile_attr_tables.o
g++ $CXXFLAGS $INC -c ../../city/assessor/general_assessor.cpp -o general_assessor.o
g++ $CXXFLAGS $INC -c ../tile_yields.cpp -o tile_yields.o
g++ $CXXFLAGS $INC -c ../tile_work_assessor.cpp -o tile_work_assessor.o
g++ $CXXFLAGS $INC -c tile_work_clearing_place_tester.cpp -o tile_work_clearing_place_tester.o

g++ $CXXFLAGS -o tile_work_clearing_place_tester \
    runtime_static_loader.o \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    runtime_trace_dbg.o \
    bit_array.o \
    game_array_simple.o \
    factory_game_array_simple.o \
    std_add_helper.o \
    tile_attr_tables.o \
    general_assessor.o \
    tile_yields.o \
    tile_work_assessor.o \
    tile_work_clearing_place_tester.o \
    -ldl \
    $LIB_SO \
    -Wl,-rpath,'$ORIGIN/../../data_io'

./tile_work_clearing_place_tester "$@"

rm runtime_static_loader.o map_terrain_validate.o map_terrain_data.o map_loader.o \
    runtime_trace_dbg.o bit_array.o game_array_simple.o factory_game_array_simple.o \
    std_add_helper.o tile_attr_tables.o general_assessor.o tile_yields.o \
    tile_work_assessor.o tile_work_clearing_place_tester.o tile_work_clearing_place_tester
