#!/bin/bash
set -e

cd "$(dirname "$0")"

LIB_SO="../../data_io/runtime_static_loader_lib.so"
if [ ! -f "$LIB_SO" ]; then
    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
    exit 1
fi

mkdir -p /home/w/Projects/simple-map-gen/unit-upgrades

INC="-I../.. \
     -I../../misc \
     -I../../data_io \
     -I../../static_state \
     -I../../city \
     -I../../city/assessor \
     -I../../city/effector \
     -I../../dyn_state \
     -I../../gen_bit_banks \
     -I../../ai_pathing/walk_general \
     -I../../ai_pathing/walk_cities \
     -I../../map_loader \
     -I../../simple_map_gen \
     -I../../ai_proc \
     -I.."
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
g++ $CXXFLAGS $INC -c ../../misc/bit_array.cpp -o bit_array.o
g++ $CXXFLAGS $INC -c ../resource_ledger.cpp -o resource_ledger.o
g++ $CXXFLAGS $INC -c ../player_ledger.cpp -o player_ledger.o
g++ $CXXFLAGS $INC -c ../unit_upgrades.cpp -o unit_upgrades.o
g++ $CXXFLAGS $INC -c unit_upgrades_table_tester.cpp -o unit_upgrades_table_tester.o

g++ $CXXFLAGS -o unit_upgrades_table_tester \
    runtime_static_loader.o \
    bit_array.o \
    resource_ledger.o \
    player_ledger.o \
    unit_upgrades.o \
    unit_upgrades_table_tester.o \
    -ldl \
    $LIB_SO \
    -Wl,-rpath,'$ORIGIN/../../data_io'

./unit_upgrades_table_tester

rm -f runtime_static_loader.o bit_array.o resource_ledger.o player_ledger.o unit_upgrades.o unit_upgrades_table_tester.o
