#!/bin/bash
set -e

cd "$(dirname "$0")"

LIB_SO="../../data_io/runtime_static_loader_lib.so"
if [ ! -f "$LIB_SO" ]; then
    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
    exit 1
fi

IMPL_MK="${UNIT_ROSTER_MNG_MK:-mk03}"
IMPL_REL="impl/unit_roster_mng_impl_${IMPL_MK}.cpp"
IMPL_ABS="../${IMPL_REL}"
if [ ! -f "$IMPL_ABS" ]; then
    echo "missing impl $IMPL_ABS"
    exit 1
fi

SEED_DEF=""
if [ -n "${UNIT_ROSTER_SEED:-}" ]; then
    SEED_DEF="-DUNIT_ROSTER_SEED=${UNIT_ROSTER_SEED}"
fi

mkdir -p /home/w/Projects/simple-map-gen/unit-roster

INC="-I../.. \
     -I../../misc \
     -I../../data_io \
     -I../../static_state \
     -I../../city \
     -I../../city/assessor \
     -I../../city/effector \
     -I../../dyn_state \
     -I../../gen_bit_banks \
     -I../../ai_pathing/walk_general \
     -I../../ai_pathing/walk_cities \
     -I../../map_loader \
     -I../../simple_map_gen \
     -I../../ai_proc \
     -I.."
CXXFLAGS="-std=c++17 -Wall -Wextra"
CXXFLAGS="$CXXFLAGS -DUNIT_ROSTER_MNG_IMPL=\"${IMPL_REL}\""
CXXFLAGS="$CXXFLAGS -DUNIT_ROSTER_MNG_MK=\"${IMPL_MK}\""
CXXFLAGS="$CXXFLAGS $SEED_DEF"

g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
g++ $CXXFLAGS $INC -c ../../misc/bit_array.cpp -o bit_array.o
g++ $CXXFLAGS $INC -c ../../misc/assert_log.cpp -o assert_log.o
g++ $CXXFLAGS $INC -c ../../gen_bit_banks/general_bit_bank.cpp -o general_bit_bank.o
g++ $CXXFLAGS $INC -DTILE_REQ_CHK_STUB -c ../../city/assessor/general_assessor.cpp -o general_assessor.o
g++ $CXXFLAGS $INC -c ../../ai_proc/linear_tech.cpp -o linear_tech.o
g++ $CXXFLAGS $INC -c ../unit_roster_mng.cpp -o unit_roster_mng.o
g++ $CXXFLAGS $INC -c unit_roster_mng_tester.cpp -o unit_roster_mng_tester.o

g++ $CXXFLAGS -o unit_roster_mng_tester \
    runtime_static_loader.o \
    bit_array.o \
    assert_log.o \
    general_bit_bank.o \
    general_assessor.o \
    linear_tech.o \
    unit_roster_mng.o \
    unit_roster_mng_tester.o \
    -ldl \
    $LIB_SO \
    -Wl,-rpath,'$ORIGIN/../../data_io' \
    -Wl,--allow-shlib-undefined

echo "--- running unit_roster_mng_tester (${IMPL_MK}) ---"
./unit_roster_mng_tester

rm -f runtime_static_loader.o bit_array.o assert_log.o general_bit_bank.o \
    general_assessor.o linear_tech.o unit_roster_mng.o unit_roster_mng_tester.o
