#!/bin/bash
set -e

cd "$(dirname "$0")"

LIB_SO="../../data_io/runtime_static_loader_lib.so"
if [ ! -f "$LIB_SO" ]; then
    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
    exit 1
fi

INC="-I../.. \
     -I../../misc \
     -I../../data_io \
     -I../../static_state \
     -I../../city \
     -I../../city/assessor \
     -I../../city/effector \
     -I../../dyn_state \
     -I../../gen_bit_banks \
     -I../../ai_pathing/walk_general \
     -I../../ai_pathing/walk_cities \
     -I../../map_loader \
     -I../../simple_map_gen \
     -I../../ai_proc \
     -I.."
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
g++ $CXXFLAGS $INC -c ../../misc/bit_array.cpp -o bit_array.o
g++ $CXXFLAGS $INC -c ../unit_utility_helper.cpp -o unit_utility_helper.o
g++ $CXXFLAGS $INC -c unit_utility_helper_tester.cpp -o unit_utility_helper_tester.o

g++ $CXXFLAGS -o unit_utility_helper_tester \
    runtime_static_loader.o \
    bit_array.o \
    unit_utility_helper.o \
    unit_utility_helper_tester.o \
    -ldl \
    $LIB_SO \
    -Wl,-rpath,'$ORIGIN/../../data_io'

./unit_utility_helper_tester

rm -f runtime_static_loader.o bit_array.o unit_utility_helper.o unit_utility_helper_tester.o
