#!/bin/bash

./tool_patch_texture "/home/w/Projects/img-content/colors-mtn-bottom-dark4_palette_patches.txt" 800 800 1 1

python3 tool_tile_noise.py "/home/w/Projects/img-content/colors-mtn-bottom-dark4_palette_texture.ppm"
python3 tool_tile_test.py "/home/w/Projects/img-content/colors-mtn-bottom-dark4_palette_texture_blurred.png"
