//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef BUILDING_ENUM_H
#define BUILDING_ENUM_H

#include "game_primitives.h"

//================================================================================================================================
//=> - Building -
//================================================================================================================================
//
//  Fixed catalog indices for building rows. Member order must match game_config.buildings load order.
//
//================================================================================================================================

enum class Building : u16 {
    Walls = 0,
    Barracks = 1,
    Supply_Depot = 2,
    Training_Grounds = 3,
    Armory = 4,
    Town_Watch = 5,
    Labor_Garrison = 6,
    Toll_Garrison = 7,
    Military_Smallholdings = 8,
    Granary = 9,
    Library = 10,
    Amphitheater = 11,
    Temple = 12,
    Marketplace = 13,
    Prefecture = 14,
    Census_Office = 15,
    Cisterns = 16,
    Dry_Sewers = 17,
    Cesspools = 18,
    Aqueduct = 19,
    Public_Fountains = 20,
    Public_Baths = 21,
    Water_Sewers = 22,
    Public_Latrines = 23,
    Courthouse = 24,
    Harbor = 25,
    Bank = 26,
    Cathedral = 27,
    University = 28,
    Colosseum = 29,
    Factory = 30,
    Police_Station = 31,
    Coastal_Fortress = 32,
    Airport = 33,
    Commercial_Dock = 34,
    Mass_Transit = 35,
    Public_Laundry = 36,
    Hospital = 37,
    Sanatorium = 38,
    Waterworks = 39,
    Sewage_Pumps = 40,
    Chlorination_Plant = 41,
    Incineration_Plant = 42,
    Pasteurization_Plant = 43,
    Laundry = 44,
    Coal_Plant = 45,
    Oil_Plant = 46,
    Hydro_Plant = 47,
    Nuclear_Plant = 48,
    Research_Lab = 49,
    Manufacturing_Plant = 50,
    Stock_Exchange = 51,
    Superhighways = 52,
    SAM_Missile_Battery = 53,
    Wastewater_Treatment_Plant = 54,
    Recycling_Center = 55,
    Offshore_Platform = 56,
    Civil_Defense = 57,
    Intelligence_Agency = 58,
    Solar_Plant = 59,
    Capitalization = 60
};

#endif // BUILDING_ENUM_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
