//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef BUILDING_ENUM_H
#define BUILDING_ENUM_H

#include "game_primitives.h"

//================================================================================================================================
//=> - Building -
//================================================================================================================================
//
//  Fixed catalog indices for building rows. Member order must match game_config.buildings load order.
//
//================================================================================================================================

enum class Building : u16 {
    Walls = 0,
    Barracks = 1,
    Granary = 2,
    Library = 3,
    Temple = 4,
    Marketplace = 5,
    Cisterns = 6,
    Dry_Sewers = 7,
    Cesspools = 8,
    Aqueduct = 9,
    Public_Fountains = 10,
    Public_Baths = 11,
    Water_Sewers = 12,
    Public_Latrines = 13,
    Courthouse = 14,
    Harbor = 15,
    Bank = 16,
    Cathedral = 17,
    University = 18,
    Colosseum = 19,
    Factory = 20,
    Police_Station = 21,
    Coastal_Fortress = 22,
    Airport = 23,
    Commercial_Dock = 24,
    Mass_Transit = 25,
    Public_Laundry = 26,
    Hospital = 27,
    Sanatorium = 28,
    Waterworks = 29,
    Sewage_Pumps = 30,
    Chlorination_Plant = 31,
    Incineration_Plant = 32,
    Pasteurization_Plant = 33,
    Laundry = 34,
    Coal_Plant = 35,
    Hydro_Plant = 36,
    Nuclear_Plant = 37,
    Research_Lab = 38,
    Manufacturing_Plant = 39,
    Stock_Exchange = 40,
    Superhighways = 41,
    SAM_Missile_Battery = 42,
    Wastewater_Treatment_Plant = 43,
    Recycling_Center = 44,
    Offshore_Platform = 45,
    Civil_Defense = 46,
    Intelligence_Agency = 47,
    Solar_Plant = 48,
    Capitalization = 49
};

#endif // BUILDING_ENUM_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
