//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef BUILDING_ENUM_H
#define BUILDING_ENUM_H

#include "game_primitives.h"

//================================================================================================================================
//=> - Building -
//================================================================================================================================
//
//  Fixed catalog indices for building rows. Member order must match game_config.buildings load order.
//
//================================================================================================================================

enum class Building : u16 {
    Walls = 0,
    Barracks = 1,
    Granary = 2,
    Library = 3,
    Amphitheater = 4,
    Temple = 5,
    Marketplace = 6,
    Cisterns = 7,
    Dry_Sewers = 8,
    Cesspools = 9,
    Aqueduct = 10,
    Public_Fountains = 11,
    Public_Baths = 12,
    Water_Sewers = 13,
    Public_Latrines = 14,
    Courthouse = 15,
    Harbor = 16,
    Bank = 17,
    Cathedral = 18,
    University = 19,
    Colosseum = 20,
    Factory = 21,
    Police_Station = 22,
    Coastal_Fortress = 23,
    Airport = 24,
    Commercial_Dock = 25,
    Mass_Transit = 26,
    Public_Laundry = 27,
    Hospital = 28,
    Sanatorium = 29,
    Waterworks = 30,
    Sewage_Pumps = 31,
    Chlorination_Plant = 32,
    Incineration_Plant = 33,
    Pasteurization_Plant = 34,
    Laundry = 35,
    Coal_Plant = 36,
    Oil_Plant = 37,
    Hydro_Plant = 38,
    Nuclear_Plant = 39,
    Research_Lab = 40,
    Manufacturing_Plant = 41,
    Stock_Exchange = 42,
    Superhighways = 43,
    SAM_Missile_Battery = 44,
    Wastewater_Treatment_Plant = 45,
    Recycling_Center = 46,
    Offshore_Platform = 47,
    Civil_Defense = 48,
    Intelligence_Agency = 49,
    Solar_Plant = 50,
    Capitalization = 51
};

#endif // BUILDING_ENUM_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
