#!/bin/bash

INC="-I. -I.. -I../misc -I../static_state"

g++ $INC -c ../static_state/static_bit_bank.cpp -o static_bit_bank.o
g++ $INC -c ../static_state/civ_bld_discount_map.cpp -o civ_bld_discount_map.o
g++ $INC -c ../misc/opt_str_mng.cpp -o opt_str_mng.o
g++ $INC -c path_mng.cpp -o path_mng.o
g++ $INC -c item_effect_handler.cpp -o item_effect_handler.o
g++ $INC -c item_effect_helpers.cpp -o item_effect_helpers.o
g++ $INC -c data_parser_base.cpp -o data_parser_base.o
g++ $INC -c building_parser.cpp -o building_parser.o
g++ $INC -c city_flag_parser.cpp -o city_flag_parser.o
g++ $INC -c civ_parser.cpp -o civ_parser.o
g++ $INC -c civ_trait_parser.cpp -o civ_trait_parser.o
g++ $INC -c resource_parser.cpp -o resource_parser.o
g++ $INC -c small_wonder_parser.cpp -o small_wonder_parser.o
g++ $INC -c tech_parser.cpp -o tech_parser.o
g++ $INC -c unit_parser.cpp -o unit_parser.o
g++ $INC -c unit_action_parser.cpp -o unit_action_parser.o
g++ $INC -c unit_type_parser.cpp -o unit_type_parser.o
g++ $INC -c wonder_parser.cpp -o wonder_parser.o
g++ $INC -c static_parsing_manager.cpp -o static_parsing_manager.o
g++ $INC -c civ_bld_discount_map_parsing.cpp -o civ_bld_discount_map_parsing.o
g++ $INC -c civ_bld_discount_map_tester.cpp -o civ_bld_discount_map_tester.o

g++ -o civ_bld_discount_map_tester \
    static_bit_bank.o \
    civ_bld_discount_map.o \
    opt_str_mng.o \
    path_mng.o \
    item_effect_handler.o \
    item_effect_helpers.o \
    data_parser_base.o \
    building_parser.o \
    city_flag_parser.o \
    civ_parser.o \
    civ_trait_parser.o \
    resource_parser.o \
    small_wonder_parser.o \
    tech_parser.o \
    unit_parser.o \
    unit_action_parser.o \
    unit_type_parser.o \
    wonder_parser.o \
    static_parsing_manager.o \
    civ_bld_discount_map_parsing.o \
    civ_bld_discount_map_tester.o

rm \
    static_bit_bank.o \
    civ_bld_discount_map.o \
    opt_str_mng.o \
    path_mng.o \
    item_effect_handler.o \
    item_effect_helpers.o \
    data_parser_base.o \
    building_parser.o \
    city_flag_parser.o \
    civ_parser.o \
    civ_trait_parser.o \
    resource_parser.o \
    small_wonder_parser.o \
    tech_parser.o \
    unit_parser.o \
    unit_action_parser.o \
    unit_type_parser.o \
    wonder_parser.o \
    static_parsing_manager.o \
    civ_bld_discount_map_parsing.o \
    civ_bld_discount_map_tester.o
