#!/bin/bash

# Define the include path for the compiler
INC="-I../ -I../misc -I../static_state"

# Compile objects
g++ $INC -c ../misc/opt_str_mng.cpp -o opt_str_mng.o
g++ $INC -c path_mng.cpp -o path_mng.o
g++ $INC -c data_parser_base.cpp -o data_parser_base.o
g++ $INC -c item_effect_handler.cpp -o item_effect_handler.o
g++ $INC -c item_effect_helpers.cpp -o item_effect_helpers.o
g++ $INC -c data_parser_base_req_tester.cpp -o data_parser_base_req_tester.o

# Link everything into the final tester
g++ -o data_parser_base_tester \
    opt_str_mng.o \
    path_mng.o \
    item_effect_handler.o \
    item_effect_helpers.o \
    data_parser_base.o \
    data_parser_base_req_tester.o

# Clean up
rm \
    opt_str_mng.o \
    path_mng.o \
    item_effect_handler.o \
    item_effect_helpers.o \
    data_parser_base.o \
    data_parser_base_req_tester.o