//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_item_effects.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include <cstring>

#include "item_effect_helpers.h"

ItemEffectType ItemEffectHelper::type_str_to_enum (cstr s) {
    if (s && std::strcmp(s, "NONE") == 0) { return ItemEffectType::NONE; }
    if (s && std::strcmp(s, "BOOSTER") == 0) { return ItemEffectType::BOOSTER; }
    if (s && std::strcmp(s, "BUILD") == 0) { return ItemEffectType::BUILD; }
    if (s && std::strcmp(s, "ENABLE") == 0) { return ItemEffectType::ENABLE; }
    if (s && std::strcmp(s, "RESEARCH_TECH") == 0) { return ItemEffectType::RESEARCH_TECH; }
    if (s && std::strcmp(s, "TRAIN") == 0) { return ItemEffectType::TRAIN; }
    if (s && std::strcmp(s, "TERRAIN_BOOSTER") == 0) { return ItemEffectType::TERRAIN_BOOSTER; }
    return ItemEffectType::NONE;
}

cstr ItemEffectHelper::type_enum_to_str (ItemEffectType v) {
    switch (v) {
        case ItemEffectType::NONE : return "NONE";
        case ItemEffectType::BOOSTER : return "BOOSTER";
        case ItemEffectType::BUILD : return "BUILD";
        case ItemEffectType::ENABLE : return "ENABLE";
        case ItemEffectType::RESEARCH_TECH : return "RESEARCH_TECH";
        case ItemEffectType::TRAIN : return "TRAIN";
        case ItemEffectType::TERRAIN_BOOSTER : return "TERRAIN_BOOSTER";
        default: return "NONE";
    }
}

ItemEffectBoosterType ItemEffectHelper::booster_type_str_to_enum (cstr s) {
    if (s && std::strcmp(s, "NONE") == 0) { return ItemEffectBoosterType::NONE; }
    if (s && std::strcmp(s, "SCIENCE") == 0) { return ItemEffectBoosterType::SCIENCE; }
    if (s && std::strcmp(s, "HAPPINESS") == 0) { return ItemEffectBoosterType::HAPPINESS; }
    if (s && std::strcmp(s, "PRODUCTION") == 0) { return ItemEffectBoosterType::PRODUCTION; }
    if (s && std::strcmp(s, "AIR_DEFENSE") == 0) { return ItemEffectBoosterType::AIR_DEFENSE; }
    if (s && std::strcmp(s, "AIR_RANGE") == 0) { return ItemEffectBoosterType::AIR_RANGE; }
    if (s && std::strcmp(s, "COMMERCE") == 0) { return ItemEffectBoosterType::COMMERCE; }
    if (s && std::strcmp(s, "CORRUPTION") == 0) { return ItemEffectBoosterType::CORRUPTION; }
    if (s && std::strcmp(s, "DEFENSE") == 0) { return ItemEffectBoosterType::DEFENSE; }
    if (s && std::strcmp(s, "ESPIONAGE") == 0) { return ItemEffectBoosterType::ESPIONAGE; }
    if (s && std::strcmp(s, "MOVEMENT") == 0) { return ItemEffectBoosterType::MOVEMENT; }
    if (s && std::strcmp(s, "NUKE_DEFENSE") == 0) { return ItemEffectBoosterType::NUKE_DEFENSE; }
    if (s && std::strcmp(s, "POLLUTION") == 0) { return ItemEffectBoosterType::POLLUTION; }
    if (s && std::strcmp(s, "POP_GROWTH") == 0) { return ItemEffectBoosterType::POP_GROWTH; }
    if (s && std::strcmp(s, "SEA_TRADE") == 0) { return ItemEffectBoosterType::SEA_TRADE; }
    if (s && std::strcmp(s, "SHIP_DEFENSE") == 0) { return ItemEffectBoosterType::SHIP_DEFENSE; }
    if (s && std::strcmp(s, "SHIP_MOVEMENT") == 0) { return ItemEffectBoosterType::SHIP_MOVEMENT; }
    if (s && std::strcmp(s, "SHIP_TRAINING") == 0) { return ItemEffectBoosterType::SHIP_TRAINING; }
    if (s && std::strcmp(s, "UNIT_EXP") == 0) { return ItemEffectBoosterType::UNIT_EXP; }
    if (s && std::strcmp(s, "UPGRADE_COST") == 0) { return ItemEffectBoosterType::UPGRADE_COST; }
    if (s && std::strcmp(s, "WAR_WEAR") == 0) { return ItemEffectBoosterType::WAR_WEAR; }
    return ItemEffectBoosterType::NONE;
}

cstr ItemEffectHelper::booster_type_enum_to_str (ItemEffectBoosterType v) {
    switch (v) {
        case ItemEffectBoosterType::NONE : return "NONE";
        case ItemEffectBoosterType::SCIENCE : return "SCIENCE";
        case ItemEffectBoosterType::HAPPINESS : return "HAPPINESS";
        case ItemEffectBoosterType::PRODUCTION : return "PRODUCTION";
        case ItemEffectBoosterType::AIR_DEFENSE : return "AIR_DEFENSE";
        case ItemEffectBoosterType::AIR_RANGE : return "AIR_RANGE";
        case ItemEffectBoosterType::COMMERCE : return "COMMERCE";
        case ItemEffectBoosterType::CORRUPTION : return "CORRUPTION";
        case ItemEffectBoosterType::DEFENSE : return "DEFENSE";
        case ItemEffectBoosterType::ESPIONAGE : return "ESPIONAGE";
        case ItemEffectBoosterType::MOVEMENT : return "MOVEMENT";
        case ItemEffectBoosterType::NUKE_DEFENSE : return "NUKE_DEFENSE";
        case ItemEffectBoosterType::POLLUTION : return "POLLUTION";
        case ItemEffectBoosterType::POP_GROWTH : return "POP_GROWTH";
        case ItemEffectBoosterType::SEA_TRADE : return "SEA_TRADE";
        case ItemEffectBoosterType::SHIP_DEFENSE : return "SHIP_DEFENSE";
        case ItemEffectBoosterType::SHIP_MOVEMENT : return "SHIP_MOVEMENT";
        case ItemEffectBoosterType::SHIP_TRAINING : return "SHIP_TRAINING";
        case ItemEffectBoosterType::UNIT_EXP : return "UNIT_EXP";
        case ItemEffectBoosterType::UPGRADE_COST : return "UPGRADE_COST";
        case ItemEffectBoosterType::WAR_WEAR : return "WAR_WEAR";
        default: return "NONE";
    }
}

ItemTerrainYield ItemEffectHelper::terrain_yield_str_to_enum (cstr s) {
    if (s && std::strcmp(s, "NONE") == 0) { return ItemTerrainYield::NONE; }
    if (s && std::strcmp(s, "FOOD") == 0) { return ItemTerrainYield::FOOD; }
    if (s && std::strcmp(s, "SHIELDS") == 0) { return ItemTerrainYield::SHIELDS; }
    if (s && std::strcmp(s, "COMMERCE") == 0) { return ItemTerrainYield::COMMERCE; }
    if (s && std::strcmp(s, "HAPPINESS") == 0) { return ItemTerrainYield::HAPPINESS; }
    if (s && std::strcmp(s, "DEFENSE") == 0) { return ItemTerrainYield::DEFENSE; }
    return ItemTerrainYield::NONE;
}

cstr ItemEffectHelper::terrain_yield_enum_to_str (ItemTerrainYield v) {
    switch (v) {
        case ItemTerrainYield::NONE : return "NONE";
        case ItemTerrainYield::FOOD : return "FOOD";
        case ItemTerrainYield::SHIELDS : return "SHIELDS";
        case ItemTerrainYield::COMMERCE : return "COMMERCE";
        case ItemTerrainYield::HAPPINESS : return "HAPPINESS";
        case ItemTerrainYield::DEFENSE : return "DEFENSE";
        default: return "NONE";
    }
}

ItemEffectsScope ItemEffectHelper::effects_scope_str_to_enum (cstr s) {
    if (s && std::strcmp(s, "NONE") == 0) { return ItemEffectsScope::NONE; }
    if (s && std::strcmp(s, "LOCAL") == 0) { return ItemEffectsScope::LOCAL; }
    if (s && std::strcmp(s, "CITY") == 0) { return ItemEffectsScope::CITY; }
    if (s && std::strcmp(s, "CIV") == 0) { return ItemEffectsScope::CIV; }
    if (s && std::strcmp(s, "GLOBAL") == 0) { return ItemEffectsScope::GLOBAL; }
    return ItemEffectsScope::NONE;
}

cstr ItemEffectHelper::effects_scope_enum_to_str (ItemEffectsScope v) {
    switch (v) {
        case ItemEffectsScope::NONE : return "NONE";
        case ItemEffectsScope::LOCAL : return "LOCAL";
        case ItemEffectsScope::CITY : return "CITY";
        case ItemEffectsScope::CIV : return "CIV";
        case ItemEffectsScope::GLOBAL : return "GLOBAL";
        default: return "NONE";
    }
}

ItemEffectAmountMode ItemEffectHelper::amount_mode_str_to_enum (cstr s) {
    if (s && std::strcmp(s, "NONE") == 0) { return ItemEffectAmountMode::NONE; }
    if (s && std::strcmp(s, "COUNT") == 0) { return ItemEffectAmountMode::COUNT; }
    if (s && std::strcmp(s, "PERCENTAGE") == 0) { return ItemEffectAmountMode::PERCENTAGE; }
    return ItemEffectAmountMode::NONE;
}

cstr ItemEffectHelper::amount_mode_enum_to_str (ItemEffectAmountMode v) {
    switch (v) {
        case ItemEffectAmountMode::NONE : return "NONE";
        case ItemEffectAmountMode::COUNT : return "COUNT";
        case ItemEffectAmountMode::PERCENTAGE : return "PERCENTAGE";
        default: return "NONE";
    }
}

ItemEffectBuildMode ItemEffectHelper::build_mode_str_to_enum (cstr s) {
    if (s && std::strcmp(s, "NONE") == 0) { return ItemEffectBuildMode::NONE; }
    if (s && std::strcmp(s, "AUTO_BUILD") == 0) { return ItemEffectBuildMode::AUTO_BUILD; }
    if (s && std::strcmp(s, "NO_BUILD") == 0) { return ItemEffectBuildMode::NO_BUILD; }
    return ItemEffectBuildMode::NONE;
}

cstr ItemEffectHelper::build_mode_enum_to_str (ItemEffectBuildMode v) {
    switch (v) {
        case ItemEffectBuildMode::NONE : return "NONE";
        case ItemEffectBuildMode::AUTO_BUILD : return "AUTO_BUILD";
        case ItemEffectBuildMode::NO_BUILD : return "NO_BUILD";
        default: return "NONE";
    }
}

ItemEffectUpkeepMode ItemEffectHelper::upkeep_mode_str_to_enum (cstr s) {
    if (s && std::strcmp(s, "NONE") == 0) { return ItemEffectUpkeepMode::NONE; }
    if (s && std::strcmp(s, "NORMAL_UPKEEP") == 0) { return ItemEffectUpkeepMode::NORMAL_UPKEEP; }
    if (s && std::strcmp(s, "NO_UPKEEP") == 0) { return ItemEffectUpkeepMode::NO_UPKEEP; }
    return ItemEffectUpkeepMode::NONE;
}

cstr ItemEffectHelper::upkeep_mode_enum_to_str (ItemEffectUpkeepMode v) {
    switch (v) {
        case ItemEffectUpkeepMode::NONE : return "NONE";
        case ItemEffectUpkeepMode::NORMAL_UPKEEP : return "NORMAL_UPKEEP";
        case ItemEffectUpkeepMode::NO_UPKEEP : return "NO_UPKEEP";
        default: return "NONE";
    }
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
