//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include "map_climate_parser.h"

//================================================================================================================================
//=> - MapClimateParser implementation -
//================================================================================================================================

MapClimateParser::MapClimateParser (const StringManager& items, const NameToIdxCbs& map) : DataParserBase(items, map) {
}

MapClimateStaticDataStruct* MapClimateParser::parse_data_dependencies () {
    MapClimateStaticDataStruct* parsed_data = new MapClimateStaticDataStruct[m_item_count]();
    for (u32 i = 0; i < m_item_count; ++i) {
        StringManager line_items;
        get_line_items(get_raw_lines().get_string_content(i), line_items);
        // No parsing instructions provided
    }
    return parsed_data;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================

