//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include "resource_parser.h"

//================================================================================================================================
//=> - ResourceParser implementation -
//================================================================================================================================

ResourceParser::ResourceParser (const StringManager& items, const NameToIdxCbs& map) : DataParserBase(items, map) {
}

ResourceStaticDataStruct* ResourceParser::parse_data_dependencies () {
    ResourceStaticDataStruct* parsed_data = new ResourceStaticDataStruct[m_item_count]();
    for (u32 i = 0; i < m_item_count; ++i) {
        StringManager line_items;
        get_line_items(get_raw_lines().get_string_content(i), line_items);
        parsed_data[i].food = parse_u16(line_items, 1);
        parsed_data[i].shields = parse_u16(line_items, 2);
        parsed_data[i].commerce = parse_u16(line_items, 3);
        parsed_data[i].reqs = parse_item_reqs(line_items, 4);
        parsed_data[i].res_dist_idx = m_name_to_idx_cbs.res_dist_name_to_idx(get_names().get_string_content(i));
    }
    return parsed_data;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================

