//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_runtime_statics.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef RUNTIME_STATICS_H
#define RUNTIME_STATICS_H

class StaticParsingManager;

#include "config_settings_static.h"

#include "building_static_data.h"
#include "city_flag_static_data.h"
#include "city_job_static_data.h"
#include "civ_static_data.h"
#include "civ_trait_static_data.h"
#include "tile_attribute_static_data.h"
#include "resource_static_data.h"
#include "res_dist_static_data.h"
#include "res_type_static_data.h"
#include "small_wonder_static_data.h"
#include "tech_static_data.h"
#include "unit_action_static_data.h"
#include "unit_role_static_data.h"
#include "unit_type_static_data.h"
#include "unit_static_data.h"
#include "wonder_static_data.h"
#include "worker_job_static_data.h"
#include "unit_type_action_map.h"
#include "civ_bld_discount_map.h"
#include "gen_effector/local_effector.h"
#include "gen_effector/city_effector.h"
#include "gen_effector/civ_effector.h"
#include "gen_effector/global_effector.h"
#include "dyn_produce_register.h"
#include "dyn_booster_register.h"
#include "dyn_job_slot_register.h"

//================================================================================================================================
//=> - RuntimeStatics class -
//================================================================================================================================

class RuntimeStatics {
public:
    void load_from (StaticParsingManager& p);

    GameConfigSettings& config ();
    const GameConfigSettings& config () const;

    BuildingStaticData& building ();

    const BuildingStaticData& building () const;

    CityFlagStaticData& city_flag ();

    const CityFlagStaticData& city_flag () const;

    CityJobStaticData& city_job ();

    const CityJobStaticData& city_job () const;

    CivStaticData& civ ();

    const CivStaticData& civ () const;

    CivTraitStaticData& civ_trait ();

    const CivTraitStaticData& civ_trait () const;

    TileAttributeStaticData& tile_attribute ();

    const TileAttributeStaticData& tile_attribute () const;

    ResourceStaticData& resource ();

    const ResourceStaticData& resource () const;

    ResDistStaticData& res_dist ();

    const ResDistStaticData& res_dist () const;

    ResTypeStaticData& res_type ();

    const ResTypeStaticData& res_type () const;

    SmallWonderStaticData& small_wonder ();

    const SmallWonderStaticData& small_wonder () const;

    TechStaticData& tech ();

    const TechStaticData& tech () const;

    UnitActionStaticData& unit_action ();

    const UnitActionStaticData& unit_action () const;

    UnitRoleStaticData& unit_role ();

    const UnitRoleStaticData& unit_role () const;

    UnitTypeStaticData& unit_type ();

    const UnitTypeStaticData& unit_type () const;

    UnitStaticData& unit ();

    const UnitStaticData& unit () const;

    WonderStaticData& wonder ();

    const WonderStaticData& wonder () const;

    WorkerJobStaticData& worker_job ();

    const WorkerJobStaticData& worker_job () const;

    UnitTypeActionMap& unit_type_action_map ();

    const UnitTypeActionMap& unit_type_action_map () const;

    CivBldDiscountMap& civ_bld_discount_map ();

    const CivBldDiscountMap& civ_bld_discount_map () const;

    LocalEffector& local_fx ();

    const LocalEffector& local_fx () const;

    CityEffector& city_fx ();

    const CityEffector& city_fx () const;

    CivEffector& civ_fx ();

    const CivEffector& civ_fx () const;

    GlobalEffector& global_fx ();

    const GlobalEffector& global_fx () const;

    DynProduceRegister& dyn_produce ();

    const DynProduceRegister& dyn_produce () const;

    DynBoosterRegister& dyn_booster ();

    const DynBoosterRegister& dyn_booster () const;

    DynJobSlotRegister& dyn_job_slot ();

    const DynJobSlotRegister& dyn_job_slot () const;

private:
    GameConfigSettings m_config;
    BuildingStaticData m_building;
    CityFlagStaticData m_city_flag;
    CityJobStaticData m_city_job;
    CivStaticData m_civ;
    CivTraitStaticData m_civ_trait;
    TileAttributeStaticData m_tile_attribute;
    ResourceStaticData m_resource;
    ResDistStaticData m_res_dist;
    ResTypeStaticData m_res_type;
    SmallWonderStaticData m_small_wonder;
    TechStaticData m_tech;
    UnitActionStaticData m_unit_action;
    UnitRoleStaticData m_unit_role;
    UnitTypeStaticData m_unit_type;
    UnitStaticData m_unit;
    WonderStaticData m_wonder;
    WorkerJobStaticData m_worker_job;
    
    UnitTypeActionMap m_unit_type_action_map;
    CivBldDiscountMap m_civ_bld_discount_map;
    
    LocalEffector m_local_fx;
    CityEffector m_city_fx;
    CivEffector m_civ_fx;
    GlobalEffector m_global_fx;
    
    DynProduceRegister m_dyn_produce;
    DynBoosterRegister m_dyn_booster;
    DynJobSlotRegister m_dyn_job_slot;
};

extern RuntimeStatics* g_runtime_statics;

void set_runtime_statics (RuntimeStatics* statics);

RuntimeStatics& runtime_statics ();

#endif // RUNTIME_STATICS_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
