//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_runtime_statics.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include "runtime_static_loader.h"

#include <dlfcn.h>

#include "runtime_static_loader_lib_api.h"

//================================================================================================================================
//=> - RuntimeStaticLoader implementation -
//================================================================================================================================

RuntimeStaticLoader::RuntimeStaticLoader () :
    m_lib(nullptr),
    m_handle(nullptr),
    m_statics(nullptr) {
}

RuntimeStaticLoader::~RuntimeStaticLoader () {
    unload();
    delete m_statics;
    m_statics = nullptr;
}

bool RuntimeStaticLoader::load (const char* lib_path, const char* data_path_offset) {
    unload();
    delete m_statics;
    m_statics = nullptr;
    m_lib = dlopen(lib_path, RTLD_NOW);
    if (m_lib == nullptr) {
        return false;
    }
    auto fn_create = reinterpret_cast<RuntimeStaticLoaderLibHandle (*)(const char*)>(
        dlsym(m_lib, "runtime_static_loader_lib_create"));
    auto fn_statics = reinterpret_cast<RuntimeStatics* (*)(RuntimeStaticLoaderLibHandle)>(
        dlsym(m_lib, "runtime_static_loader_lib_runtime_statics"));
    if (fn_create == nullptr || fn_statics == nullptr) {
        dlclose(m_lib);
        m_lib = nullptr;
        return false;
    }
    m_handle = fn_create(data_path_offset);
    if (m_handle == nullptr) {
        dlclose(m_lib);
        m_lib = nullptr;
        return false;
    }
    m_statics = fn_statics(m_handle);
    if (m_statics == nullptr) {
        auto fn_destroy = reinterpret_cast<void (*)(RuntimeStaticLoaderLibHandle)>(
            dlsym(m_lib, "runtime_static_loader_lib_destroy"));
        if (fn_destroy != nullptr) {
            fn_destroy(m_handle);
        }
        dlclose(m_lib);
        m_handle = nullptr;
        m_lib = nullptr;
        return false;
    }
    return true;
}

void RuntimeStaticLoader::unload () {
    if (m_lib == nullptr) {
        return;
    }
    if (m_handle != nullptr) {
        auto fn_detach = reinterpret_cast<RuntimeStatics* (*)(RuntimeStaticLoaderLibHandle)>(
            dlsym(m_lib, "runtime_static_loader_lib_detach_statics"));
        if (fn_detach != nullptr && m_statics != nullptr) {
            fn_detach(m_handle);
        }
        auto fn_destroy = reinterpret_cast<void (*)(RuntimeStaticLoaderLibHandle)>(
            dlsym(m_lib, "runtime_static_loader_lib_destroy"));
        if (fn_destroy != nullptr) {
            fn_destroy(m_handle);
        }
        m_handle = nullptr;
    }
    dlclose(m_lib);
    m_lib = nullptr;
}

bool RuntimeStaticLoader::is_loaded () const {
    return m_lib != nullptr;
}

RuntimeStatics& RuntimeStaticLoader::statics () {
    return *m_statics;
}

const RuntimeStatics& RuntimeStaticLoader::statics () const {
    return *m_statics;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
