//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_runtime_statics.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef RUNTIME_STATICS_H
#define RUNTIME_STATICS_H

class StaticParsingManager;

#include "config_settings_static.h"

#include "building_static_data.h"
#include "toggle_city_static_data.h"
#include "toggle_civ_static_data.h"
#include "toggle_global_static_data.h"
#include "city_job_static_data.h"
#include "civ_static_data.h"
#include "civ_trait_static_data.h"
#include "tile_attribute_static_data.h"
#include "resource_static_data.h"
#include "res_dist_static_data.h"
#include "res_type_static_data.h"
#include "small_wonder_static_data.h"
#include "tech_static_data.h"
#include "unit_action_static_data.h"
#include "unit_role_static_data.h"
#include "unit_type_static_data.h"
#include "unit_domain_static_data.h"
#include "unit_static_data.h"
#include "wonder_static_data.h"
#include "map_overlay_static_data.h"
#include "map_attribute_static_data.h"
#include "map_terrain_static_data.h"
#include "map_climate_static_data.h"
#include "worker_job_target_static_data.h"
#include "worker_job_type_static_data.h"
#include "worker_job_static_data.h"
#include "worker_job_imp_static_data.h"
#include "tile_yield_type_static_data.h"
#include "improvement_yield_static_data.h"
#include "unit_type_action_map.h"
#include "civ_bld_discount_map.h"
#include "trait_affinity_map.h"
#include "gen_effector/local_effector.h"
#include "gen_effector/city_effector.h"
#include "gen_effector/civ_effector.h"
#include "gen_effector/global_effector.h"
#include "dyn_produce_register.h"
#include "dyn_booster_register.h"
#include "dyn_job_slot_register.h"
#include "dyn_job_yield_register.h"
#include "worker_job_imp_index.h"

//================================================================================================================================
//=> - RuntimeStatics class -
//================================================================================================================================

class RuntimeStatics {
public:
    void load_from (StaticParsingManager& p);

    GameConfigSettings& config ();
    const GameConfigSettings& config () const;

    BuildingStaticData& building ();

    const BuildingStaticData& building () const;

    ToggleCityStaticData& toggle_city ();

    const ToggleCityStaticData& toggle_city () const;

    ToggleCivStaticData& toggle_civ ();

    const ToggleCivStaticData& toggle_civ () const;

    ToggleGlobalStaticData& toggle_global ();

    const ToggleGlobalStaticData& toggle_global () const;

    CityJobStaticData& city_job ();

    const CityJobStaticData& city_job () const;

    CivStaticData& civ ();

    const CivStaticData& civ () const;

    CivTraitStaticData& civ_trait ();

    const CivTraitStaticData& civ_trait () const;

    TileAttributeStaticData& tile_attribute ();

    const TileAttributeStaticData& tile_attribute () const;

    ResourceStaticData& resource ();

    const ResourceStaticData& resource () const;

    ResDistStaticData& res_dist ();

    const ResDistStaticData& res_dist () const;

    ResTypeStaticData& res_type ();

    const ResTypeStaticData& res_type () const;

    SmallWonderStaticData& small_wonder ();

    const SmallWonderStaticData& small_wonder () const;

    TechStaticData& tech ();

    const TechStaticData& tech () const;

    UnitActionStaticData& unit_action ();

    const UnitActionStaticData& unit_action () const;

    UnitRoleStaticData& unit_role ();

    const UnitRoleStaticData& unit_role () const;

    UnitTypeStaticData& unit_type ();

    const UnitTypeStaticData& unit_type () const;

    UnitDomainStaticData& unit_domain ();

    const UnitDomainStaticData& unit_domain () const;

    UnitStaticData& unit ();

    const UnitStaticData& unit () const;

    WonderStaticData& wonder ();

    const WonderStaticData& wonder () const;

    MapOverlayStaticData& map_overlay ();

    const MapOverlayStaticData& map_overlay () const;

    MapAttributeStaticData& map_attribute ();

    const MapAttributeStaticData& map_attribute () const;

    MapTerrainStaticData& map_terrain ();

    const MapTerrainStaticData& map_terrain () const;

    MapClimateStaticData& map_climate ();

    const MapClimateStaticData& map_climate () const;

    WorkerJobTargetStaticData& worker_job_target ();

    const WorkerJobTargetStaticData& worker_job_target () const;

    WorkerJobTypeStaticData& worker_job_type ();

    const WorkerJobTypeStaticData& worker_job_type () const;

    WorkerJobStaticData& worker_job ();

    const WorkerJobStaticData& worker_job () const;

    WorkerJobImpStaticData& worker_job_imp ();

    const WorkerJobImpStaticData& worker_job_imp () const;

    TileYieldTypeStaticData& tile_yield_type ();

    const TileYieldTypeStaticData& tile_yield_type () const;

    ImprovementYieldStaticData& improvement_yield ();

    const ImprovementYieldStaticData& improvement_yield () const;

    UnitTypeActionMap& unit_type_action_map ();

    const UnitTypeActionMap& unit_type_action_map () const;

    CivBldDiscountMap& civ_bld_discount_map ();

    const CivBldDiscountMap& civ_bld_discount_map () const;

    TraitAffinityMap& trait_affinity_map ();

    const TraitAffinityMap& trait_affinity_map () const;

    LocalEffector& local_fx ();

    const LocalEffector& local_fx () const;

    CityEffector& city_fx ();

    const CityEffector& city_fx () const;

    CivEffector& civ_fx ();

    const CivEffector& civ_fx () const;

    GlobalEffector& global_fx ();

    const GlobalEffector& global_fx () const;

    DynProduceRegister& dyn_produce ();

    const DynProduceRegister& dyn_produce () const;

    DynBoosterRegister& dyn_booster ();

    const DynBoosterRegister& dyn_booster () const;

    DynJobSlotRegister& dyn_job_slot ();

    const DynJobSlotRegister& dyn_job_slot () const;

    DynJobYieldRegister& dyn_job_yield ();

    const DynJobYieldRegister& dyn_job_yield () const;

    WorkerJobImpIndex& worker_job_imp_index ();

    const WorkerJobImpIndex& worker_job_imp_index () const;

private:
    GameConfigSettings m_config;
    BuildingStaticData m_building;
    ToggleCityStaticData m_toggle_city;
    ToggleCivStaticData m_toggle_civ;
    ToggleGlobalStaticData m_toggle_global;
    CityJobStaticData m_city_job;
    CivStaticData m_civ;
    CivTraitStaticData m_civ_trait;
    TileAttributeStaticData m_tile_attribute;
    ResourceStaticData m_resource;
    ResDistStaticData m_res_dist;
    ResTypeStaticData m_res_type;
    SmallWonderStaticData m_small_wonder;
    TechStaticData m_tech;
    UnitActionStaticData m_unit_action;
    UnitRoleStaticData m_unit_role;
    UnitTypeStaticData m_unit_type;
    UnitDomainStaticData m_unit_domain;
    UnitStaticData m_unit;
    WonderStaticData m_wonder;
    MapOverlayStaticData m_map_overlay;
    MapAttributeStaticData m_map_attribute;
    MapTerrainStaticData m_map_terrain;
    MapClimateStaticData m_map_climate;
    WorkerJobTargetStaticData m_worker_job_target;
    WorkerJobTypeStaticData m_worker_job_type;
    WorkerJobStaticData m_worker_job;
    WorkerJobImpStaticData m_worker_job_imp;
    TileYieldTypeStaticData m_tile_yield_type;
    ImprovementYieldStaticData m_improvement_yield;
    
    UnitTypeActionMap m_unit_type_action_map;
    CivBldDiscountMap m_civ_bld_discount_map;
    TraitAffinityMap m_trait_affinity_map;
    
    LocalEffector m_local_fx;
    CityEffector m_city_fx;
    CivEffector m_civ_fx;
    GlobalEffector m_global_fx;
    
    DynProduceRegister m_dyn_produce;
    DynBoosterRegister m_dyn_booster;
    DynJobSlotRegister m_dyn_job_slot;
    DynJobYieldRegister m_dyn_job_yield;
    WorkerJobImpIndex m_worker_job_imp_index;
};

extern RuntimeStatics* g_runtime_statics;

void set_runtime_statics (RuntimeStatics* statics);

RuntimeStatics& runtime_statics ();

#endif // RUNTIME_STATICS_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
