//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_runtime_statics.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef RUNTIME_STATICS_H
#define RUNTIME_STATICS_H

class StaticParsingManager;

#include "building_static_data.h"
#include "city_flag_static_data.h"
#include "civ_static_data.h"
#include "civ_trait_static_data.h"
#include "mvt_cost_static_data.h"
#include "resource_static_data.h"
#include "res_dist_static_data.h"
#include "small_wonder_static_data.h"
#include "tech_static_data.h"
#include "unit_static_data.h"
#include "unit_action_static_data.h"
#include "unit_type_static_data.h"
#include "wonder_static_data.h"
#include "unit_type_action_map.h"
#include "civ_bld_discount_map.h"
#include "gen_effector/local_effector.h"
#include "gen_effector/city_effector.h"
#include "gen_effector/civ_effector.h"
#include "gen_effector/global_effector.h"

//================================================================================================================================
//=> - RuntimeStatics class -
//================================================================================================================================

class RuntimeStatics {
public:
    void load_from (StaticParsingManager& p);

    BuildingStaticData& building ();

    const BuildingStaticData& building () const;

    CityFlagStaticData& city_flag ();

    const CityFlagStaticData& city_flag () const;

    CivStaticData& civ ();

    const CivStaticData& civ () const;

    CivTraitStaticData& civ_trait ();

    const CivTraitStaticData& civ_trait () const;

    MvtCostStaticData& mvt_cost ();

    const MvtCostStaticData& mvt_cost () const;

    ResourceStaticData& resource ();

    const ResourceStaticData& resource () const;

    ResDistStaticData& res_dist ();

    const ResDistStaticData& res_dist () const;

    SmallWonderStaticData& small_wonder ();

    const SmallWonderStaticData& small_wonder () const;

    TechStaticData& tech ();

    const TechStaticData& tech () const;

    UnitStaticData& unit ();

    const UnitStaticData& unit () const;

    UnitActionStaticData& unit_action ();

    const UnitActionStaticData& unit_action () const;

    UnitTypeStaticData& unit_type ();

    const UnitTypeStaticData& unit_type () const;

    WonderStaticData& wonder ();

    const WonderStaticData& wonder () const;

    UnitTypeActionMap& unit_type_action_map ();

    const UnitTypeActionMap& unit_type_action_map () const;

    CivBldDiscountMap& civ_bld_discount_map ();

    const CivBldDiscountMap& civ_bld_discount_map () const;

    LocalEffector& local_fx ();

    const LocalEffector& local_fx () const;

    CityEffector& city_fx ();

    const CityEffector& city_fx () const;

    CivEffector& civ_fx ();

    const CivEffector& civ_fx () const;

    GlobalEffector& global_fx ();

    const GlobalEffector& global_fx () const;

private:
    BuildingStaticData m_building;
    CityFlagStaticData m_city_flag;
    CivStaticData m_civ;
    CivTraitStaticData m_civ_trait;
    MvtCostStaticData m_mvt_cost;
    ResourceStaticData m_resource;
    ResDistStaticData m_res_dist;
    SmallWonderStaticData m_small_wonder;
    TechStaticData m_tech;
    UnitStaticData m_unit;
    UnitActionStaticData m_unit_action;
    UnitTypeStaticData m_unit_type;
    WonderStaticData m_wonder;
    
    UnitTypeActionMap m_unit_type_action_map;
    CivBldDiscountMap m_civ_bld_discount_map;
    
    LocalEffector m_local_fx;
    CityEffector m_city_fx;
    CivEffector m_civ_fx;
    GlobalEffector m_global_fx;
};

extern RuntimeStatics* g_runtime_statics;

void set_runtime_statics (RuntimeStatics* statics);

RuntimeStatics& runtime_statics ();

#endif // RUNTIME_STATICS_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
