//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_parse_manager.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef STATIC_PARSING_MANAGER_H
#define STATIC_PARSING_MANAGER_H

#include "path_mng.h"
#include "data_parser_base.h"
#include "opt_str_mng.h"

class StaticBitBank;

#include "building_parser.h"
#include "toggle_city_parser.h"
#include "toggle_civ_parser.h"
#include "toggle_global_parser.h"
#include "city_job_parser.h"
#include "civ_parser.h"
#include "civ_trait_parser.h"
#include "tile_attribute_parser.h"
#include "resource_parser.h"
#include "res_dist_parser.h"
#include "res_type_parser.h"
#include "small_wonder_parser.h"
#include "tech_parser.h"
#include "unit_action_parser.h"
#include "unit_role_parser.h"
#include "unit_type_parser.h"
#include "unit_domain_parser.h"
#include "unit_parser.h"
#include "wonder_parser.h"
#include "map_overlay_parser.h"
#include "map_attribute_parser.h"
#include "map_terrain_parser.h"
#include "map_climate_parser.h"
#include "worker_job_target_parser.h"
#include "worker_job_type_parser.h"
#include "worker_job_parser.h"
#include "worker_job_imp_parser.h"
#include "tile_yield_type_parser.h"
#include "improvement_yield_parser.h"

#include "building_static_data.h"
#include "toggle_city_static_data.h"
#include "toggle_civ_static_data.h"
#include "toggle_global_static_data.h"
#include "city_job_static_data.h"
#include "civ_static_data.h"
#include "civ_trait_static_data.h"
#include "tile_attribute_static_data.h"
#include "resource_static_data.h"
#include "res_dist_static_data.h"
#include "res_type_static_data.h"
#include "small_wonder_static_data.h"
#include "tech_static_data.h"
#include "unit_action_static_data.h"
#include "unit_role_static_data.h"
#include "unit_type_static_data.h"
#include "unit_domain_static_data.h"
#include "unit_static_data.h"
#include "wonder_static_data.h"
#include "map_overlay_static_data.h"
#include "map_attribute_static_data.h"
#include "map_terrain_static_data.h"
#include "map_climate_static_data.h"
#include "worker_job_target_static_data.h"
#include "worker_job_type_static_data.h"
#include "worker_job_static_data.h"
#include "worker_job_imp_static_data.h"
#include "tile_yield_type_static_data.h"
#include "improvement_yield_static_data.h"

#include "trait_affinity_map.h"

//================================================================================================================================
//=> - StaticParsingManager class -
//================================================================================================================================

class StaticParsingManager {
public:
    explicit StaticParsingManager (cstr path_offset);
    ~StaticParsingManager ();

    const BuildingStaticDataStruct* get_building_data () const;

    u16 get_building_count () const;

    const ToggleCityStaticDataStruct* get_toggle_city_data () const;

    u16 get_toggle_city_count () const;

    const ToggleCivStaticDataStruct* get_toggle_civ_data () const;

    u16 get_toggle_civ_count () const;

    const ToggleGlobalStaticDataStruct* get_toggle_global_data () const;

    u16 get_toggle_global_count () const;

    const CityJobStaticDataStruct* get_city_job_data () const;

    u16 get_city_job_count () const;

    const CivStaticDataStruct* get_civ_data () const;

    u16 get_civ_count () const;

    const CivTraitStaticDataStruct* get_civ_trait_data () const;

    u16 get_civ_trait_count () const;

    const TileAttributeStaticDataStruct* get_tile_attribute_data () const;

    u16 get_tile_attribute_count () const;

    const ResourceStaticDataStruct* get_resource_data () const;

    u16 get_resource_count () const;

    const ResDistStaticDataStruct* get_res_dist_data () const;

    u16 get_res_dist_count () const;

    const ResTypeStaticDataStruct* get_res_type_data () const;

    u16 get_res_type_count () const;

    const SmallWonderStaticDataStruct* get_small_wonder_data () const;

    u16 get_small_wonder_count () const;

    const TechStaticDataStruct* get_tech_data () const;

    u16 get_tech_count () const;

    const UnitActionStaticDataStruct* get_unit_action_data () const;

    u16 get_unit_action_count () const;

    const UnitRoleStaticDataStruct* get_unit_role_data () const;

    u16 get_unit_role_count () const;

    const UnitTypeStaticDataStruct* get_unit_type_data () const;

    u16 get_unit_type_count () const;

    const UnitDomainStaticDataStruct* get_unit_domain_data () const;

    u16 get_unit_domain_count () const;

    const UnitStaticDataStruct* get_unit_data () const;

    u16 get_unit_count () const;

    const WonderStaticDataStruct* get_wonder_data () const;

    u16 get_wonder_count () const;

    const MapOverlayStaticDataStruct* get_map_overlay_data () const;

    u16 get_map_overlay_count () const;

    const MapAttributeStaticDataStruct* get_map_attribute_data () const;

    u16 get_map_attribute_count () const;

    const MapTerrainStaticDataStruct* get_map_terrain_data () const;

    u16 get_map_terrain_count () const;

    const MapClimateStaticDataStruct* get_map_climate_data () const;

    u16 get_map_climate_count () const;

    const WorkerJobTargetStaticDataStruct* get_worker_job_target_data () const;

    u16 get_worker_job_target_count () const;

    const WorkerJobTypeStaticDataStruct* get_worker_job_type_data () const;

    u16 get_worker_job_type_count () const;

    const WorkerJobStaticDataStruct* get_worker_job_data () const;

    u16 get_worker_job_count () const;

    const WorkerJobImpStaticDataStruct* get_worker_job_imp_data () const;

    u16 get_worker_job_imp_count () const;

    const TileYieldTypeStaticDataStruct* get_tile_yield_type_data () const;

    u16 get_tile_yield_type_count () const;

    const ImprovementYieldStaticDataStruct* get_improvement_yield_data () const;

    u16 get_improvement_yield_count () const;
    const DataParserBase& get_building_name_parser () const;

    const DataParserBase& get_toggle_city_name_parser () const;

    const DataParserBase& get_toggle_civ_name_parser () const;

    const DataParserBase& get_toggle_global_name_parser () const;

    const DataParserBase& get_city_job_name_parser () const;

    const DataParserBase& get_civ_name_parser () const;

    const DataParserBase& get_civ_trait_name_parser () const;

    const DataParserBase& get_tile_attribute_name_parser () const;

    const DataParserBase& get_resource_name_parser () const;

    const DataParserBase& get_res_dist_name_parser () const;

    const DataParserBase& get_res_type_name_parser () const;

    const DataParserBase& get_small_wonder_name_parser () const;

    const DataParserBase& get_tech_name_parser () const;

    const DataParserBase& get_unit_action_name_parser () const;

    const DataParserBase& get_unit_role_name_parser () const;

    const DataParserBase& get_unit_type_name_parser () const;

    const DataParserBase& get_unit_domain_name_parser () const;

    const DataParserBase& get_unit_name_parser () const;

    const DataParserBase& get_wonder_name_parser () const;

    const DataParserBase& get_map_overlay_name_parser () const;

    const DataParserBase& get_map_attribute_name_parser () const;

    const DataParserBase& get_map_terrain_name_parser () const;

    const DataParserBase& get_map_climate_name_parser () const;

    const DataParserBase& get_worker_job_target_name_parser () const;

    const DataParserBase& get_worker_job_type_name_parser () const;

    const DataParserBase& get_worker_job_name_parser () const;

    const DataParserBase& get_worker_job_imp_name_parser () const;

    const DataParserBase& get_tile_yield_type_name_parser () const;

    const DataParserBase& get_improvement_yield_name_parser () const;
    
    StaticBitBank* get_unit_type_action_map_bank () const;

    StaticBitBank* get_civ_bld_discount_map_bank () const;

    void release_map_banks ();
    TraitAffinityMap& get_trait_affinity_map ();

    const TraitAffinityMap& get_trait_affinity_map () const;
    
    const NameToIdxCbs& get_name_to_idx_cbs () const;
    cstr get_path_to_settings () const;
    u16 get_callback_count () const;

private:
    StaticParsingManager () = delete;
    StaticParsingManager (const StaticParsingManager& other) = delete;
    StaticParsingManager (StaticParsingManager&& other) = delete;

    void build_name_to_idx_callbacks ();
    void parse_supported_data ();

    static u16 safe_size_to_u16 (size_t value);

    PathMng m_paths;

    StringManager m_effect_items;
    StringManager m_building_items;
    StringManager m_toggle_city_items;
    StringManager m_toggle_civ_items;
    StringManager m_toggle_global_items;
    StringManager m_city_job_items;
    StringManager m_civ_items;
    StringManager m_civ_trait_items;
    StringManager m_tile_attribute_items;
    StringManager m_resource_items;
    StringManager m_res_dist_items;
    StringManager m_res_type_items;
    StringManager m_small_wonder_items;
    StringManager m_tech_items;
    StringManager m_unit_action_items;
    StringManager m_unit_role_items;
    StringManager m_unit_type_items;
    StringManager m_unit_domain_items;
    StringManager m_unit_items;
    StringManager m_wonder_items;
    StringManager m_map_overlay_items;
    StringManager m_map_attribute_items;
    StringManager m_map_terrain_items;
    StringManager m_map_climate_items;
    StringManager m_worker_job_target_items;
    StringManager m_worker_job_type_items;
    StringManager m_worker_job_items;
    StringManager m_worker_job_imp_items;
    StringManager m_tile_yield_type_items;
    StringManager m_improvement_yield_items;
    StringManager m_trait_affinity_items;

    DataParserBase* m_building_name_parser;
    DataParserBase* m_toggle_city_name_parser;
    DataParserBase* m_toggle_civ_name_parser;
    DataParserBase* m_toggle_global_name_parser;
    DataParserBase* m_city_job_name_parser;
    DataParserBase* m_civ_name_parser;
    DataParserBase* m_civ_trait_name_parser;
    DataParserBase* m_tile_attribute_name_parser;
    DataParserBase* m_resource_name_parser;
    DataParserBase* m_res_dist_name_parser;
    DataParserBase* m_res_type_name_parser;
    DataParserBase* m_small_wonder_name_parser;
    DataParserBase* m_tech_name_parser;
    DataParserBase* m_unit_action_name_parser;
    DataParserBase* m_unit_role_name_parser;
    DataParserBase* m_unit_type_name_parser;
    DataParserBase* m_unit_domain_name_parser;
    DataParserBase* m_unit_name_parser;
    DataParserBase* m_wonder_name_parser;
    DataParserBase* m_map_overlay_name_parser;
    DataParserBase* m_map_attribute_name_parser;
    DataParserBase* m_map_terrain_name_parser;
    DataParserBase* m_map_climate_name_parser;
    DataParserBase* m_worker_job_target_name_parser;
    DataParserBase* m_worker_job_type_name_parser;
    DataParserBase* m_worker_job_name_parser;
    DataParserBase* m_worker_job_imp_name_parser;
    DataParserBase* m_tile_yield_type_name_parser;
    DataParserBase* m_improvement_yield_name_parser;

    NameToIdxCbs m_name_to_idx_cbs;
    u16 m_callback_count;

    StaticBitBank* m_unit_type_action_map_bank;
    StaticBitBank* m_civ_bld_discount_map_bank;
    TraitAffinityMap m_trait_affinity_map;

    BuildingStaticDataStruct* m_building_data;
    ToggleCityStaticDataStruct* m_toggle_city_data;
    ToggleCivStaticDataStruct* m_toggle_civ_data;
    ToggleGlobalStaticDataStruct* m_toggle_global_data;
    CityJobStaticDataStruct* m_city_job_data;
    CivStaticDataStruct* m_civ_data;
    CivTraitStaticDataStruct* m_civ_trait_data;
    TileAttributeStaticDataStruct* m_tile_attribute_data;
    ResourceStaticDataStruct* m_resource_data;
    ResDistStaticDataStruct* m_res_dist_data;
    ResTypeStaticDataStruct* m_res_type_data;
    SmallWonderStaticDataStruct* m_small_wonder_data;
    TechStaticDataStruct* m_tech_data;
    UnitActionStaticDataStruct* m_unit_action_data;
    UnitRoleStaticDataStruct* m_unit_role_data;
    UnitTypeStaticDataStruct* m_unit_type_data;
    UnitDomainStaticDataStruct* m_unit_domain_data;
    UnitStaticDataStruct* m_unit_data;
    WonderStaticDataStruct* m_wonder_data;
    MapOverlayStaticDataStruct* m_map_overlay_data;
    MapAttributeStaticDataStruct* m_map_attribute_data;
    MapTerrainStaticDataStruct* m_map_terrain_data;
    MapClimateStaticDataStruct* m_map_climate_data;
    WorkerJobTargetStaticDataStruct* m_worker_job_target_data;
    WorkerJobTypeStaticDataStruct* m_worker_job_type_data;
    WorkerJobStaticDataStruct* m_worker_job_data;
    WorkerJobImpStaticDataStruct* m_worker_job_imp_data;
    TileYieldTypeStaticDataStruct* m_tile_yield_type_data;
    ImprovementYieldStaticDataStruct* m_improvement_yield_data;
};

#endif // STATIC_PARSING_MANAGER_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================

