//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_parse_manager.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef STATIC_PARSING_MANAGER_H
#define STATIC_PARSING_MANAGER_H

#include "path_mng.h"
#include "data_parser_base.h"
#include "opt_str_mng.h"

class StaticBitBank;

#include "building_parser.h"
#include "city_flag_parser.h"
#include "civ_parser.h"
#include "civ_trait_parser.h"
#include "tile_attribute_parser.h"
#include "resource_parser.h"
#include "res_dist_parser.h"
#include "small_wonder_parser.h"
#include "tech_parser.h"
#include "unit_parser.h"
#include "unit_action_parser.h"
#include "unit_type_parser.h"
#include "wonder_parser.h"

#include "building_static_data.h"
#include "city_flag_static_data.h"
#include "civ_static_data.h"
#include "civ_trait_static_data.h"
#include "tile_attribute_static_data.h"
#include "resource_static_data.h"
#include "res_dist_static_data.h"
#include "small_wonder_static_data.h"
#include "tech_static_data.h"
#include "unit_static_data.h"
#include "unit_action_static_data.h"
#include "unit_type_static_data.h"
#include "wonder_static_data.h"

//================================================================================================================================
//=> - StaticParsingManager class -
//================================================================================================================================

class StaticParsingManager {
public:
    explicit StaticParsingManager (cstr path_offset);
    ~StaticParsingManager ();

    const BuildingStaticDataStruct* get_building_data () const;

    u16 get_building_count () const;

    const CityFlagStaticDataStruct* get_city_flag_data () const;

    u16 get_city_flag_count () const;

    const CivStaticDataStruct* get_civ_data () const;

    u16 get_civ_count () const;

    const CivTraitStaticDataStruct* get_civ_trait_data () const;

    u16 get_civ_trait_count () const;

    const TileAttributeStaticDataStruct* get_tile_attribute_data () const;

    u16 get_tile_attribute_count () const;

    const ResourceStaticDataStruct* get_resource_data () const;

    u16 get_resource_count () const;

    const ResDistStaticDataStruct* get_res_dist_data () const;

    u16 get_res_dist_count () const;

    const SmallWonderStaticDataStruct* get_small_wonder_data () const;

    u16 get_small_wonder_count () const;

    const TechStaticDataStruct* get_tech_data () const;

    u16 get_tech_count () const;

    const UnitStaticDataStruct* get_unit_data () const;

    u16 get_unit_count () const;

    const UnitActionStaticDataStruct* get_unit_action_data () const;

    u16 get_unit_action_count () const;

    const UnitTypeStaticDataStruct* get_unit_type_data () const;

    u16 get_unit_type_count () const;

    const WonderStaticDataStruct* get_wonder_data () const;

    u16 get_wonder_count () const;
    const DataParserBase& get_building_name_parser () const;

    const DataParserBase& get_city_flag_name_parser () const;

    const DataParserBase& get_civ_name_parser () const;

    const DataParserBase& get_civ_trait_name_parser () const;

    const DataParserBase& get_tile_attribute_name_parser () const;

    const DataParserBase& get_resource_name_parser () const;

    const DataParserBase& get_res_dist_name_parser () const;

    const DataParserBase& get_small_wonder_name_parser () const;

    const DataParserBase& get_tech_name_parser () const;

    const DataParserBase& get_unit_name_parser () const;

    const DataParserBase& get_unit_action_name_parser () const;

    const DataParserBase& get_unit_type_name_parser () const;

    const DataParserBase& get_wonder_name_parser () const;
    
    StaticBitBank* get_unit_type_action_map_bank () const;

    StaticBitBank* get_civ_bld_discount_map_bank () const;

    void release_map_banks ();
    
    const NameToIdxCbs& get_name_to_idx_cbs () const;
    cstr get_path_to_settings () const;
    u16 get_callback_count () const;

private:
    StaticParsingManager () = delete;
    StaticParsingManager (const StaticParsingManager& other) = delete;
    StaticParsingManager (StaticParsingManager&& other) = delete;

    void build_name_to_idx_callbacks ();
    void parse_supported_data ();

    static u16 safe_size_to_u16 (size_t value);

    PathMng m_paths;

    StringManager m_effect_items;
    StringManager m_building_items;
    StringManager m_city_flag_items;
    StringManager m_civ_items;
    StringManager m_civ_trait_items;
    StringManager m_tile_attribute_items;
    StringManager m_resource_items;
    StringManager m_res_dist_items;
    StringManager m_small_wonder_items;
    StringManager m_tech_items;
    StringManager m_unit_items;
    StringManager m_unit_action_items;
    StringManager m_unit_type_items;
    StringManager m_wonder_items;

    DataParserBase* m_building_name_parser;
    DataParserBase* m_city_flag_name_parser;
    DataParserBase* m_civ_name_parser;
    DataParserBase* m_civ_trait_name_parser;
    DataParserBase* m_tile_attribute_name_parser;
    DataParserBase* m_resource_name_parser;
    DataParserBase* m_res_dist_name_parser;
    DataParserBase* m_small_wonder_name_parser;
    DataParserBase* m_tech_name_parser;
    DataParserBase* m_unit_name_parser;
    DataParserBase* m_unit_action_name_parser;
    DataParserBase* m_unit_type_name_parser;
    DataParserBase* m_wonder_name_parser;

    NameToIdxCbs m_name_to_idx_cbs;
    u16 m_callback_count;

    StaticBitBank* m_unit_type_action_map_bank;
    StaticBitBank* m_civ_bld_discount_map_bank;

    BuildingStaticDataStruct* m_building_data;
    CityFlagStaticDataStruct* m_city_flag_data;
    CivStaticDataStruct* m_civ_data;
    CivTraitStaticDataStruct* m_civ_trait_data;
    TileAttributeStaticDataStruct* m_tile_attribute_data;
    ResourceStaticDataStruct* m_resource_data;
    ResDistStaticDataStruct* m_res_dist_data;
    SmallWonderStaticDataStruct* m_small_wonder_data;
    TechStaticDataStruct* m_tech_data;
    UnitStaticDataStruct* m_unit_data;
    UnitActionStaticDataStruct* m_unit_action_data;
    UnitTypeStaticDataStruct* m_unit_type_data;
    WonderStaticDataStruct* m_wonder_data;
};

#endif // STATIC_PARSING_MANAGER_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================

