//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef TECH_ENUM_H
#define TECH_ENUM_H

#include "game_primitives.h"

//================================================================================================================================
//=> - Tech -
//================================================================================================================================
//
//  Fixed catalog indices for tech rows. Member order must match game_config.techs load order.
//
//================================================================================================================================

enum class Tech : u16 {
    Foundation = 0,
    Alphabet = 1,
    Bronze_Working = 2,
    Agriculture = 3,
    Warrior_Code = 4,
    The_Wheel = 5,
    Mining = 6,
    Pottery = 7,
    Masonry = 8,
    Animal_Husbandry = 9,
    Horseback_Riding = 10,
    Iron_Working = 11,
    Writing = 12,
    Map_Making = 13,
    Mathematics = 14,
    Calendar = 15,
    Philosophy = 16,
    Code_of_Laws = 17,
    Construction = 18,
    Currency = 19,
    Republic = 20,
    Literature = 21,
    Polytheism = 22,
    Monotheism = 23,
    Chivalry = 24,
    Engineering = 25,
    Feudalism = 26,
    Theology = 27,
    Invention = 28,
    Gunpowder = 29,
    Education = 30,
    Printing_Press = 31,
    Banking = 32,
    Chemistry = 33,
    Metallurgy = 34,
    Astronomy = 35,
    Physics = 36,
    Magnetism = 37,
    Theory_of_Gravity = 38,
    Navigation = 39,
    Music_Theory = 40,
    Military_Tradition = 41,
    Nationalism = 42,
    Espionage = 43,
    Democracy = 44,
    Economics = 45,
    Scientific_Method = 46,
    Steam_Power = 47,
    Industrialization = 48,
    Medicine = 49,
    Biology = 50,
    Germ_Theory = 51,
    Pasteurization = 52,
    Mass_Immunization = 53,
    Virology = 54,
    Antibiotics = 55,
    Thermal_Sterilization = 56,
    Electricity = 57,
    Industrial_Chemistry = 58,
    The_Corporation = 59,
    Refining = 60,
    Steel = 61,
    Replaceable_Parts = 62,
    Combustion = 63,
    Flight = 64,
    Mass_Production = 65,
    Amphibious_War = 66,
    Electronics = 67,
    Atomic_Theory = 68,
    Motorized_Transportation = 69,
    Radio = 70,
    Advanced_Flight = 71,
    Rocketry = 72,
    Computers = 73,
    Nuclear_Power = 74,
    Miniaturization = 75,
    Robotics = 76,
    Space_Flight = 77,
    Fusion_Power = 78,
    Genetics = 79,
    Ecology = 80,
    Superconductor = 81,
    Stealth = 82,
    Future_Tech = 83
};

#endif // TECH_ENUM_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
