//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_path_manager.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef PATH_MNG_H
#define PATH_MNG_H

#include "game_primitives.h"

static const u16 PATH_MNG_PATH_N = 512;
static const u16 PATH_MNG_SUFFIX_MAX_N = [PATH_MNG_SUFFIX_MAX_N_TAG];
static const u16 PATH_MNG_OFFSET_MAX_N = PATH_MNG_PATH_N - PATH_MNG_SUFFIX_MAX_N - 1;
static const u16 PATH_MNG_OFFSET_BUF_N = PATH_MNG_OFFSET_MAX_N + 1;

//================================================================================================================================
//=> - PathMng class -
//================================================================================================================================

class PathMng {
public:
    explicit PathMng (cstr path_offset);

    [PATH_MNG_HEADER_GETTERS_TAG]

private:
    PathMng () = delete;
    PathMng (const PathMng& other) = delete;
    PathMng (PathMng&& other) = delete;

    void build_paths ();
    void validate_paths_or_exit () const;

    char m_path_offset[PATH_MNG_PATH_N];

    [PATH_MNG_HEADER_MEMBERS_TAG]
};

#endif // PATH_MNG_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================

