//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_item_effects.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef ITEM_EFFECTS_H
#define ITEM_EFFECTS_H

#include "game_primitives.h"

//================================================================================================================================
//=> - Effect limits -
//================================================================================================================================

#define MAX_EFFECT_COUNT 5 

//================================================================================================================================
//=> - Common effect enums -
//================================================================================================================================

enum class ItemEffectType : u16 {
    [IE_TYPE_ENUM_MEMBERS]
};

enum class ItemEffectBoosterType : u16 {
    [IE_BOOSTER_TYPE_ENUM_MEMBERS]
};

enum class ItemTerrainYield : u8 {
    [IE_TERRAIN_YIELD_ENUM_MEMBERS]
};

enum class ItemEffectsScope : u8 {
    [IE_SCOPE_ENUM_MEMBERS]
};

enum class ItemEffectAmountMode : u8 {
    [IE_AMOUNT_MODE_ENUM_MEMBERS]
};

enum class ItemEffectBuildMode : u8 {
    [IE_BUILD_MODE_ENUM_MEMBERS]
};

enum class ItemEffectUpkeepMode : u8 {
    [IE_UPKEEP_MODE_ENUM_MEMBERS]
};

//================================================================================================================================
//=> - Per-effect payload structs -
//================================================================================================================================

typedef struct ItemEffectBooster {
    ItemEffectBoosterType target_id;
    i16 amount;
    ItemEffectsScope scope;
    ItemEffectAmountMode amount_mode;
} ItemEffectBooster;

typedef struct ItemEffectTerrainBooster {
    u16 terrain_id;
    i8 amount;
    ItemTerrainYield yield; 
    ItemEffectsScope scope;
    ItemEffectAmountMode amount_mode;
} ItemEffectTerrainBooster;

typedef struct ItemEffectBuild {
    u16 building_id;
    ItemEffectsScope scope;
    ItemEffectBuildMode build_mode;
    ItemEffectUpkeepMode upkeep_mode;
} ItemEffectBuild;

typedef struct ItemEffectEnable {
    u16 feature_id;
    ItemEffectsScope scope;
} ItemEffectEnable;

typedef struct ItemEffectResearchTech {
    u16 tech_count;
} ItemEffectResearchTech;

typedef struct ItemEffectTrain {
    u16 unit_id;
    u8 turns_interval;
} ItemEffectTrain;

//================================================================================================================================
//=> - Union + tagged entry -
//================================================================================================================================

typedef union ItemEffectsUnion {
    ItemEffectBooster booster;
    ItemEffectBuild build;
    ItemEffectEnable enable;
    ItemEffectResearchTech research_tech;
    ItemEffectTrain train;
} ItemEffectsUnion;

typedef struct ItemEffectStruct {
    u16 type;
    ItemEffectsUnion effect;
} ItemEffectStruct;

typedef struct ItemEffectsStruct {
    ItemEffectStruct items[MAX_EFFECT_COUNT];
} ItemEffectsStruct;

#endif // ITEM_EFFECTS_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
