//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_path_manager.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include <cstdio>
#include <cstdlib>
#include <cstring>

#include "path_mng.h"

//================================================================================================================================
//=> - Private helper functions -
//================================================================================================================================

static void copy_path (char* dst, u16 n, cstr src) {
    if (!src) {
        src = "";
    }
    std::snprintf(dst, n, "%s", src);
}

static void join_path (char* dst, u16 n, cstr base, cstr suffix) {
    if (!base) {
        base = "";
    }
    if (!suffix) {
        suffix = "";
    }
    const u32 bl = (u32)std::strlen(base);
    const u32 sl = (u32)std::strlen(suffix);
    if (n == 0 || bl + 1u + sl >= n) {
        if (n > 0) {
            dst[0] = '\0';
        }
        return;
    }
    std::memcpy(dst, base, bl);
    dst[bl] = '/';
    std::memcpy(dst + bl + 1, suffix, sl + 1);
}

static bool does_file_exist (cstr path) {
    if (!path || !path[0]) {
        return false;
    }
    FILE* f = std::fopen(path, "r");
    if (!f) {
        return false;
    }
    std::fclose(f);
    return true;
}

//================================================================================================================================
//=> - PathMng implementation -
//================================================================================================================================

PathMng::PathMng (cstr path_offset) {
    copy_path(m_path_offset, PATH_MNG_OFFSET_BUF_N, path_offset);
    build_paths();
    validate_paths_or_exit();
}

[PATH_MNG_CPP_GETTERS_TAG]

void PathMng::build_paths () {
    [PATH_MNG_CPP_BUILD_PATHS_TAG]
}

void PathMng::validate_paths_or_exit () const {
    u32 error_count = 0;

    [PATH_MNG_CPP_VALIDATE_PATHS_TAG]

    if (error_count > 0) {
        printf("ERROR: Path validation failed (%u missing files)\n", error_count);
        std::exit(1);
    }
}

//================================================================================================================================
//=> - End -
//================================================================================================================================

