//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef TILE_ATTRIBUTE_ENUM_H
#define TILE_ATTRIBUTE_ENUM_H

#include "game_primitives.h"

//================================================================================================================================
//=> - TileAttribute -
//================================================================================================================================
//
//  Fixed catalog indices for tile_attribute rows. Member order must match game_config.tile_attributes load order.
//
//================================================================================================================================

enum class TileAttribute : u16 {
    TERR_NONE = 0,
    TERR_OCEAN = 1,
    TERR_SEA = 2,
    TERR_COASTAL = 3,
    TERR_PLAINS = 4,
    TERR_HILLS = 5,
    TERR_MOUNTAINS = 6,
    TERR_VOLCANO = 7,
    TERR_INLAND_SEA = 8,
    TERR_INLAND_LAKE = 9,
    TERR_TILE_SENTINEL = 10,
    CLIMATE_NONE = 11,
    CLIMATE_DESERT = 12,
    CLIMATE_PLAINS = 13,
    CLIMATE_GRASSLAND = 14,
    CLIMATE_BLACK_SOIL = 15,
    OV_NONE = 16,
    OV_FORESTS = 17,
    OV_SWAMPS = 18,
    OV_JUNGLES = 19,
    OV_GLACIER = 20,
    OV_RIVERS = 21,
    ROAD_NONE = 22,
    ROAD_PATH = 23,
    ROAD_COBBLE = 24,
    ROAD_ASPHALT = 25,
    ROAD_RAIL = 26
};

#endif // TILE_ATTRIBUTE_ENUM_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
