//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include "unit_role_parser.h"

//================================================================================================================================
//=> - UnitRoleParser implementation -
//================================================================================================================================

UnitRoleParser::UnitRoleParser (const StringManager& items, const NameToIdxCbs& map) : DataParserBase(items, map) {
}

UnitRoleStaticDataStruct* UnitRoleParser::parse_data_dependencies () {
    UnitRoleStaticDataStruct* parsed_data = new UnitRoleStaticDataStruct[m_item_count]();
    for (u32 i = 0; i < m_item_count; ++i) {
        StringManager line_items;
        get_line_items(get_raw_lines().get_string_content(i), line_items);
        parsed_data[i].mods = parse_combat_mods(line_items, 1);
    }
    return parsed_data;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================

