//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef UNIT_ENUM_H
#define UNIT_ENUM_H

#include "game_primitives.h"

//================================================================================================================================
//=> - Unit -
//================================================================================================================================
//
//  Fixed catalog indices for unit rows. Member order must match game_config.units load order.
//
//================================================================================================================================

enum class Unit : u16 {
    Settler = 0,
    Worker = 1,
    Scout = 2,
    Warrior = 3,
    Explorer = 4,
    Archer = 5,
    Spearman = 6,
    Jaguar_Warrior = 7,
    Javelin_Thrower = 8,
    Enkidu_Warrior = 9,
    Numidian_Mercenary = 10,
    Hoplite = 11,
    Bowman = 12,
    Immortal = 13,
    Chasqui_Scout = 14,
    Impi = 15,
    Chariot = 16,
    Catapult = 17,
    Swordsman = 18,
    Pikeman = 19,
    War_Chariot = 20,
    Legion = 21,
    Musketman = 22,
    Three_Man_Chariot = 23,
    Swiss_Mercenary = 24,
    Berserker = 25,
    Galley = 26,
    Longbowman = 27,
    Horseman = 28,
    Rider = 29,
    Samurai = 30,
    Ancient_Cavalry = 31,
    Trebuchet = 32,
    War_Elephant = 33,
    Gallic_Swordsman = 34,
    Hwach_a = 35,
    Crusader = 36,
    Musketeer = 37,
    Cataphract = 38,
    Transport = 39,
    Cannon = 40,
    Knight = 41,
    Conquistador = 42,
    Mounted_Warrior = 43,
    Caravel = 44,
    Ansar_Warrior = 45,
    Privateer = 46,
    Rifleman = 47,
    Mobile_SAM = 48,
    Keshik = 49,
    Carrack = 50,
    Frigate = 51,
    Man_O_War = 52,
    Cavalry = 53,
    Cossack = 54,
    Submarine = 55,
    Artillery = 56,
    Radar_Artillery = 57,
    Sipahi = 58,
    Paratrooper = 59,
    Ironclad = 60,
    Infantry = 61,
    Guided_Missile = 62,
    Fighter = 63,
    F_15 = 64,
    Destroyer = 65,
    Bomber = 66,
    Marine = 67,
    Carrier = 68,
    Stealth_Fighter = 69,
    Stealth_Bomber = 70,
    Nuclear_Submarine = 71,
    Tank = 72,
    Cruiser = 73,
    Panzer = 74,
    AEGIS_Cruiser = 75,
    Helicopter = 76,
    Battleship = 77,
    Mech_Infantry = 78,
    Modern_Armor = 79,
    Tactical_Nuke = 80,
    Nuclear_Missile = 81
};

#endif // UNIT_ENUM_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
