//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include "unit_action_parser.h"

//================================================================================================================================
//=> - UnitActionParser implementation -
//================================================================================================================================

UnitActionParser::UnitActionParser (const StringManager& items, const NameToIdxCbs& map) : DataParserBase(items, map) {
}

UnitActionStaticDataStruct* UnitActionParser::parse_data_dependencies () {
    UnitActionStaticDataStruct* parsed_data = new UnitActionStaticDataStruct[m_item_count]();
    for (u32 i = 0; i < m_item_count; ++i) {
        StringManager line_items;
        get_line_items(get_raw_lines().get_string_content(i), line_items);
        // No parsing instructions provided
    }
    return parsed_data;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================

