//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef WONDER_ENUM_H
#define WONDER_ENUM_H

#include "game_primitives.h"

//================================================================================================================================
//=> - Wonder -
//================================================================================================================================
//
//  Fixed catalog indices for wonder rows. Member order must match game_config.wonders load order.
//
//================================================================================================================================

enum class Wonder : u16 {
    Pyramids = 0,
    Great_Library = 1,
    Hanging_Gardens = 2,
    Colossus = 3,
    Great_Lighthouse = 4,
    Oracle = 5,
    Great_Wall = 6,
    Basilica_Cistern = 7,
    Statue_of_Zeus = 8,
    Sun_Tzu_s_Art_of_War = 9,
    Leonardo_s_Workshop = 10,
    Knights_Templar = 11,
    Magellan_s_Voyage = 12,
    Copernicus_Observatory = 13,
    Shakespeare_s_Theatre = 14,
    Newton_s_University = 15,
    J_S_Bach_s_Cathedral = 16,
    Adam_Smith_s_Trading_Company = 17,
    Darwin_s_Voyage = 18,
    Statue_of_Liberty = 19,
    Jennerian_Society = 20,
    The_Pasteur_Institute = 21,
    Salk_Laboratories = 22,
    Eiffel_Tower = 23,
    Hoover_Dam = 24,
    United_Nations = 25,
    SETI_Program = 26,
    Cure_for_Cancer = 27,
    Longevity = 28,
    Manhattan_Project = 29,
    Apollo_Program = 30
};

#endif // WONDER_ENUM_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
