#!/bin/bash

# Define the include path for the compiler
INC="-I../ -I../misc"

# Compile objects (Adding the path to files in misc)
g++ $INC -c ../misc/str_mng.cpp -o str_mng.o
g++ $INC -c ../misc/bit_array.cpp -o bit_array.o
g++ $INC -c city_flags.cpp -o city_flags.o
g++ $INC -c tech_data.cpp -o tech_data.o
g++ $INC -c resource_data.cpp -o resource_data.o
g++ $INC -c building_data.cpp -o building_data.o
g++ $INC -c wonder_data.cpp -o wonder_data.o
g++ $INC -c wonder_tester.cpp -o wonder_tester.o

# Link everything into the final tester
g++ -o wonder_tester str_mng.o bit_array.o city_flags.o tech_data.o resource_data.o building_data.o wonder_data.o wonder_tester.o

# Clean up
rm str_mng.o bit_array.o city_flags.o tech_data.o resource_data.o building_data.o wonder_data.o wonder_tester.o