//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include <cstdio>

#include "worker_job_imp_parser_tester.h"
#include "item_effect_helpers.h"

//================================================================================================================================
//=> - Static members -
//================================================================================================================================

WorkerJobImpParserTester* WorkerJobImpParserTester::s_inst = NULL;

//================================================================================================================================
//=> - WorkerJobImpParserTester implementation -
//================================================================================================================================

WorkerJobImpParserTester::WorkerJobImpParserTester () : 
    m_plvl(0), 
    m_out(NULL), 
    m_building_sd(NULL),
    m_toggle_city_sd(NULL),
    m_toggle_civ_sd(NULL),
    m_toggle_global_sd(NULL),
    m_city_job_sd(NULL),
    m_civ_sd(NULL),
    m_civ_trait_sd(NULL),
    m_tile_attribute_sd(NULL),
    m_resource_sd(NULL),
    m_res_dist_sd(NULL),
    m_res_type_sd(NULL),
    m_small_wonder_sd(NULL),
    m_tech_era_sd(NULL),
    m_tech_age_sd(NULL),
    m_tech_sd(NULL),
    m_unit_action_sd(NULL),
    m_unit_role_sd(NULL),
    m_unit_type_sd(NULL),
    m_unit_domain_sd(NULL),
    m_unit_sd(NULL),
    m_wonder_sd(NULL),
    m_map_overlay_sd(NULL),
    m_map_attribute_sd(NULL),
    m_map_terrain_sd(NULL),
    m_map_climate_sd(NULL),
    m_worker_job_target_sd(NULL),
    m_worker_job_type_sd(NULL),
    m_worker_job_sd(NULL),
    m_worker_job_imp_sd(NULL),
    m_tile_yield_type_sd(NULL),
    m_improvement_yield_sd(NULL), 
    m_building_psr(NULL),
    m_toggle_city_psr(NULL),
    m_toggle_civ_psr(NULL),
    m_toggle_global_psr(NULL),
    m_city_job_psr(NULL),
    m_civ_psr(NULL),
    m_civ_trait_psr(NULL),
    m_tile_attribute_psr(NULL),
    m_resource_psr(NULL),
    m_res_dist_psr(NULL),
    m_res_type_psr(NULL),
    m_small_wonder_psr(NULL),
    m_tech_era_psr(NULL),
    m_tech_age_psr(NULL),
    m_tech_psr(NULL),
    m_unit_action_psr(NULL),
    m_unit_role_psr(NULL),
    m_unit_type_psr(NULL),
    m_unit_domain_psr(NULL),
    m_unit_psr(NULL),
    m_wonder_psr(NULL),
    m_map_overlay_psr(NULL),
    m_map_attribute_psr(NULL),
    m_map_terrain_psr(NULL),
    m_map_climate_psr(NULL),
    m_worker_job_target_psr(NULL),
    m_worker_job_type_psr(NULL),
    m_worker_job_psr(NULL),
    m_worker_job_imp_psr(NULL),
    m_tile_yield_type_psr(NULL),
    m_improvement_yield_psr(NULL) 
{
}

void WorkerJobImpParserTester::set_building_sd (const BuildingStaticData* sd) {

    m_building_sd = sd;

}

void WorkerJobImpParserTester::set_toggle_city_sd (const ToggleCityStaticData* sd) {

    m_toggle_city_sd = sd;

}

void WorkerJobImpParserTester::set_toggle_civ_sd (const ToggleCivStaticData* sd) {

    m_toggle_civ_sd = sd;

}

void WorkerJobImpParserTester::set_toggle_global_sd (const ToggleGlobalStaticData* sd) {

    m_toggle_global_sd = sd;

}

void WorkerJobImpParserTester::set_city_job_sd (const CityJobStaticData* sd) {

    m_city_job_sd = sd;

}

void WorkerJobImpParserTester::set_civ_sd (const CivStaticData* sd) {

    m_civ_sd = sd;

}

void WorkerJobImpParserTester::set_civ_trait_sd (const CivTraitStaticData* sd) {

    m_civ_trait_sd = sd;

}

void WorkerJobImpParserTester::set_tile_attribute_sd (const TileAttributeStaticData* sd) {

    m_tile_attribute_sd = sd;

}

void WorkerJobImpParserTester::set_resource_sd (const ResourceStaticData* sd) {

    m_resource_sd = sd;

}

void WorkerJobImpParserTester::set_res_dist_sd (const ResDistStaticData* sd) {

    m_res_dist_sd = sd;

}

void WorkerJobImpParserTester::set_res_type_sd (const ResTypeStaticData* sd) {

    m_res_type_sd = sd;

}

void WorkerJobImpParserTester::set_small_wonder_sd (const SmallWonderStaticData* sd) {

    m_small_wonder_sd = sd;

}

void WorkerJobImpParserTester::set_tech_era_sd (const TechEraStaticData* sd) {

    m_tech_era_sd = sd;

}

void WorkerJobImpParserTester::set_tech_age_sd (const TechAgeStaticData* sd) {

    m_tech_age_sd = sd;

}

void WorkerJobImpParserTester::set_tech_sd (const TechStaticData* sd) {

    m_tech_sd = sd;

}

void WorkerJobImpParserTester::set_unit_action_sd (const UnitActionStaticData* sd) {

    m_unit_action_sd = sd;

}

void WorkerJobImpParserTester::set_unit_role_sd (const UnitRoleStaticData* sd) {

    m_unit_role_sd = sd;

}

void WorkerJobImpParserTester::set_unit_type_sd (const UnitTypeStaticData* sd) {

    m_unit_type_sd = sd;

}

void WorkerJobImpParserTester::set_unit_domain_sd (const UnitDomainStaticData* sd) {

    m_unit_domain_sd = sd;

}

void WorkerJobImpParserTester::set_unit_sd (const UnitStaticData* sd) {

    m_unit_sd = sd;

}

void WorkerJobImpParserTester::set_wonder_sd (const WonderStaticData* sd) {

    m_wonder_sd = sd;

}

void WorkerJobImpParserTester::set_map_overlay_sd (const MapOverlayStaticData* sd) {

    m_map_overlay_sd = sd;

}

void WorkerJobImpParserTester::set_map_attribute_sd (const MapAttributeStaticData* sd) {

    m_map_attribute_sd = sd;

}

void WorkerJobImpParserTester::set_map_terrain_sd (const MapTerrainStaticData* sd) {

    m_map_terrain_sd = sd;

}

void WorkerJobImpParserTester::set_map_climate_sd (const MapClimateStaticData* sd) {

    m_map_climate_sd = sd;

}

void WorkerJobImpParserTester::set_worker_job_target_sd (const WorkerJobTargetStaticData* sd) {

    m_worker_job_target_sd = sd;

}

void WorkerJobImpParserTester::set_worker_job_type_sd (const WorkerJobTypeStaticData* sd) {

    m_worker_job_type_sd = sd;

}

void WorkerJobImpParserTester::set_worker_job_sd (const WorkerJobStaticData* sd) {

    m_worker_job_sd = sd;

}

void WorkerJobImpParserTester::set_worker_job_imp_sd (const WorkerJobImpStaticData* sd) {

    m_worker_job_imp_sd = sd;

}

void WorkerJobImpParserTester::set_tile_yield_type_sd (const TileYieldTypeStaticData* sd) {

    m_tile_yield_type_sd = sd;

}

void WorkerJobImpParserTester::set_improvement_yield_sd (const ImprovementYieldStaticData* sd) {

    m_improvement_yield_sd = sd;

}

FILE* WorkerJobImpParserTester::out () const {
    return m_out != NULL ? m_out : stdout;
}

void WorkerJobImpParserTester::open_writer () {
    if (m_out != NULL) {
        return;
    }
    m_out = fopen("RESULTS_NEW_WORKER_JOB_IMP", "w");
}

void WorkerJobImpParserTester::close_writer () {
    if (m_out != NULL) {
        fclose(m_out);
        m_out = NULL;
    }
}

void WorkerJobImpParserTester::set_plvl (int lvl) {
    m_plvl = lvl;
}

bool WorkerJobImpParserTester::ld_sm (StringManager& sm, cstr path) {
    if (sm.load_file_content(path)) {
        sm.split_string_by_char(0, '\n');
        DataParserBase::normalize_lines(sm);
        return true;
    }
    sm.load_cstr_content("NONE");
    sm.split_string_by_char(0, '\n');
    DataParserBase::normalize_lines(sm);
    return false;
}

u16 WorkerJobImpParserTester::st_building_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_building_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_building_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_toggle_city_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_toggle_city_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_toggle_city_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_toggle_civ_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_toggle_civ_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_toggle_civ_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_toggle_global_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_toggle_global_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_toggle_global_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_city_job_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_city_job_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_city_job_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_civ_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_civ_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_civ_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_civ_trait_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_civ_trait_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_civ_trait_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_tile_attribute_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_tile_attribute_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_tile_attribute_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_resource_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_resource_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_resource_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_res_dist_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_res_dist_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_res_dist_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_res_type_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_res_type_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_res_type_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_small_wonder_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_small_wonder_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_small_wonder_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_tech_era_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_tech_era_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_tech_era_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_tech_age_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_tech_age_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_tech_age_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_tech_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_tech_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_tech_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_unit_action_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_unit_action_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_unit_action_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_unit_role_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_unit_role_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_unit_role_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_unit_type_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_unit_type_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_unit_type_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_unit_domain_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_unit_domain_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_unit_domain_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_unit_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_unit_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_unit_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_wonder_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_wonder_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_wonder_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_map_overlay_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_map_overlay_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_map_overlay_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_map_attribute_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_map_attribute_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_map_attribute_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_map_terrain_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_map_terrain_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_map_terrain_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_map_climate_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_map_climate_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_map_climate_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_worker_job_target_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_worker_job_target_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_worker_job_target_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_worker_job_type_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_worker_job_type_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_worker_job_type_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_worker_job_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_worker_job_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_worker_job_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_worker_job_imp_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_worker_job_imp_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_worker_job_imp_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_tile_yield_type_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_tile_yield_type_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_tile_yield_type_psr->name_to_idx(name);
}

u16 WorkerJobImpParserTester::st_improvement_yield_n2i (cstr name) {
    if (s_inst == NULL || s_inst->m_improvement_yield_psr == NULL) {
        return U16_KEY_NULL;
    }
    return s_inst->m_improvement_yield_psr->name_to_idx(name);
}

void WorkerJobImpParserTester::pr_u16 (cstr label, u16 value) {
    fprintf(out(), "  %s: %u\n", label, value);
}

void WorkerJobImpParserTester::pr_i16 (cstr label, i16 value) {
    fprintf(out(), "  %s: %d\n", label, (int)value);
}

void WorkerJobImpParserTester::pr_u32 (cstr label, u32 value) {
    fprintf(out(), "  %s: %u\n", label, value);
}

void WorkerJobImpParserTester::pr_reqs (cstr label, const ItemReqsStruct& reqs) {
    fprintf(out(), "  %s:\n", label);
    for (u32 j = 0; j < MAX_PREREQ_COUNT; ++j) {
        if (reqs.types[j] == ITEM_REQ_TYPE_NONE) {
            continue;
        }
        const u16 idx = reqs.indices[j];
        if (idx == U16_KEY_NULL) {
            continue;
        }
        const u8 type = reqs.types[j];

        if (type == ITEM_REQ_TYPE_BUILDING) {
            if (m_building_sd != NULL && idx < m_building_sd->get_item_count()) {
                fprintf(out(), "    [%u] type=%u %s (%u)", j, type, m_building_sd->get_name(BuildingStaticDataKey::from_raw(idx)), idx);
            } else if (m_building_psr != NULL) {
                fprintf(out(), "    [%u] type=%u %s (%u)", j, type, m_building_psr->idx_to_name(idx), idx);
            }
        } else if (type == ITEM_REQ_TYPE_FLAG) {
            if (m_toggle_city_sd != NULL && idx < m_toggle_city_sd->get_item_count()) {
                fprintf(out(), "    [%u] type=%u %s (%u)", j, type, m_toggle_city_sd->get_name(ToggleCityStaticDataKey::from_raw(idx)), idx);
            } else if (m_toggle_city_psr != NULL) {
                fprintf(out(), "    [%u] type=%u %s (%u)", j, type, m_toggle_city_psr->idx_to_name(idx), idx);
            }
        } else if (type == ITEM_REQ_TYPE_CIV) {
            if (m_civ_sd != NULL && idx < m_civ_sd->get_item_count()) {
                fprintf(out(), "    [%u] type=%u %s (%u)", j, type, m_civ_sd->get_name(CivStaticDataKey::from_raw(idx)), idx);
            } else if (m_civ_psr != NULL) {
                fprintf(out(), "    [%u] type=%u %s (%u)", j, type, m_civ_psr->idx_to_name(idx), idx);
            }
        } else if (type == ITEM_REQ_TYPE_CIV_TRAIT) {
            if (m_civ_trait_sd != NULL && idx < m_civ_trait_sd->get_item_count()) {
                fprintf(out(), "    [%u] type=%u %s (%u)", j, type, m_civ_trait_sd->get_name(CivTraitStaticDataKey::from_raw(idx)), idx);
            } else if (m_civ_trait_psr != NULL) {
                fprintf(out(), "    [%u] type=%u %s (%u)", j, type, m_civ_trait_psr->idx_to_name(idx), idx);
            }
        } else if (type == ITEM_REQ_TYPE_RESOURCE) {
            if (m_resource_sd != NULL && idx < m_resource_sd->get_item_count()) {
                fprintf(out(), "    [%u] type=%u %s (%u)", j, type, m_resource_sd->get_name(ResourceStaticDataKey::from_raw(idx)), idx);
            } else if (m_resource_psr != NULL) {
                fprintf(out(), "    [%u] type=%u %s (%u)", j, type, m_resource_psr->idx_to_name(idx), idx);
            }
        } else if (type == ITEM_REQ_TYPE_TECH) {
            if (m_tech_sd != NULL && idx < m_tech_sd->get_item_count()) {
                fprintf(out(), "    [%u] type=%u %s (%u)", j, type, m_tech_sd->get_name(TechStaticDataKey::from_raw(idx)), idx);
            } else if (m_tech_psr != NULL) {
                fprintf(out(), "    [%u] type=%u %s (%u)", j, type, m_tech_psr->idx_to_name(idx), idx);
            }
        } else if (type == ITEM_REQ_TYPE_TILE) {
            static const char* k_tile_kinds[] = { "", "terrain", "climate", "overlay", "attribute" };
            const u8 kind = reqs.added_args[j];
            cstr kind_nm = (kind <= TILE_REQ_KIND_ATTRIBUTE) ? k_tile_kinds[kind] : "?";
            cstr site_nm = "";
            if (kind == TILE_REQ_KIND_TERRAIN && m_map_terrain_psr != NULL) { site_nm = m_map_terrain_psr->idx_to_name(idx); }
            else if (kind == TILE_REQ_KIND_CLIMATE && m_map_climate_psr != NULL) { site_nm = m_map_climate_psr->idx_to_name(idx); }
            else if (kind == TILE_REQ_KIND_OVERLAY && m_map_overlay_psr != NULL) { site_nm = m_map_overlay_psr->idx_to_name(idx); }
            else if (kind == TILE_REQ_KIND_ATTRIBUTE && m_map_attribute_psr != NULL) { site_nm = m_map_attribute_psr->idx_to_name(idx); }
            fprintf(out(), "    [%u] type=%u tile(%s,%s) (%u)", j, type, kind_nm, site_nm, idx);

        } else {
            fprintf(out(), "    [%u] type=%u <unknown> (%u)", j, type, idx);
        }
        if (reqs.added_args[j] != 0) {
            fprintf(out(), " arg=%u", reqs.added_args[j]);
        }
        fprintf(out(), "\n");
    }
}

void WorkerJobImpParserTester::pr_fx (cstr label, const ItemEffectsStruct& e) {
    fprintf(out(), "  %s:\n", label);
    for (u32 j = 0; j < MAX_EFFECT_COUNT; ++j) {
        const ItemEffectStruct& slot = e.items[j];
        const u16 type_u = slot.type;
        if (type_u == static_cast<u16>(ItemEffectType::NONE)) {
            continue;
        }
        fprintf(out(), "    [%u] type=%u", j, static_cast<u32>(type_u));
        switch (static_cast<ItemEffectType>(type_u)) {
        case ItemEffectType::BOOSTER: {
            const ItemEffectBooster& b = slot.effect.booster;
            const char* tname = "?";
            switch (b.target_id) {
                case ItemEffectBoosterType::SCIENCE: tname = "SCIENCE"; break;
                case ItemEffectBoosterType::HAPPINESS: tname = "HAPPINESS"; break;
                case ItemEffectBoosterType::PRODUCTION: tname = "PRODUCTION"; break;
                case ItemEffectBoosterType::AIR_DEFENSE: tname = "AIR_DEFENSE"; break;
                case ItemEffectBoosterType::AIR_RANGE: tname = "AIR_RANGE"; break;
                case ItemEffectBoosterType::COMMERCE: tname = "COMMERCE"; break;
                case ItemEffectBoosterType::CORRUPTION: tname = "CORRUPTION"; break;
                case ItemEffectBoosterType::DEFENSE: tname = "DEFENSE"; break;
                case ItemEffectBoosterType::ESPIONAGE: tname = "ESPIONAGE"; break;
                case ItemEffectBoosterType::MOVEMENT: tname = "MOVEMENT"; break;
                case ItemEffectBoosterType::NUKE_DEFENSE: tname = "NUKE_DEFENSE"; break;
                case ItemEffectBoosterType::POLLUTION: tname = "POLLUTION"; break;
                case ItemEffectBoosterType::POP_GROWTH: tname = "POP_GROWTH"; break;
                case ItemEffectBoosterType::SEA_TRADE: tname = "SEA_TRADE"; break;
                case ItemEffectBoosterType::SHIP_DEFENSE: tname = "SHIP_DEFENSE"; break;
                case ItemEffectBoosterType::SHIP_MOVEMENT: tname = "SHIP_MOVEMENT"; break;
                case ItemEffectBoosterType::SHIP_TRAINING: tname = "SHIP_TRAINING"; break;
                case ItemEffectBoosterType::UNIT_EXP: tname = "UNIT_EXP"; break;
                case ItemEffectBoosterType::UPGRADE_COST: tname = "UPGRADE_COST"; break;
                case ItemEffectBoosterType::WAR_WEAR: tname = "WAR_WEAR"; break;
                case ItemEffectBoosterType::CULTURE: tname = "CULTURE"; break;
                case ItemEffectBoosterType::SANITATION: tname = "SANITATION"; break;
                case ItemEffectBoosterType::WORKER_DRAFT: tname = "WORKER_DRAFT"; break;
                case ItemEffectBoosterType::FOOD: tname = "FOOD"; break;
                case ItemEffectBoosterType::RESOURCE: tname = "RESOURCE"; break;
                case ItemEffectBoosterType::CIV_LAND_UNIT_SUPPORT: tname = "CIV_LAND_UNIT_SUPPORT"; break;
                case ItemEffectBoosterType::CITY_LAND_UNIT_SUPPORT: tname = "CITY_LAND_UNIT_SUPPORT"; break;
                case ItemEffectBoosterType::CIV_NAVAL_UNIT_SUPPORT: tname = "CIV_NAVAL_UNIT_SUPPORT"; break;
                case ItemEffectBoosterType::CITY_NAVAL_UNIT_SUPPORT: tname = "CITY_NAVAL_UNIT_SUPPORT"; break;
                default: break;
            }
            const char* sc = "?";
            switch (b.scope) {
                case ItemEffectsScope::LOCAL: sc = "LOCAL"; break;
                case ItemEffectsScope::CITY: sc = "CITY"; break;
                case ItemEffectsScope::GLOBAL: sc = "CIV"; break;
                default: break;
            }
            const char* am = "?";
            switch (b.amount_mode) {
                case ItemEffectAmountMode::COUNT: am = "COUNT"; break;
                case ItemEffectAmountMode::PERCENTAGE: am = "PERCENTAGE"; break;
                default: break;
            }
            fprintf(out(), " booster %s (%d)", tname, static_cast<int>(b.amount));
            fprintf(out(), " scope=%s", sc);
            fprintf(out(), " mode=%s", am);
            break;
        }
        case ItemEffectType::BUILD: {
            const ItemEffectBuild& b = slot.effect.build;
            const char* sc = "?";
            switch (b.scope) {
                case ItemEffectsScope::LOCAL: sc = "LOCAL"; break;
                case ItemEffectsScope::CITY: sc = "CITY"; break;
                case ItemEffectsScope::GLOBAL: sc = "CIV"; break;
                default: break;
            }
            const char* bm = "?";
            switch (b.build_mode) {
                case ItemEffectBuildMode::AUTO_BUILD: bm = "AUTO_BUILD"; break;
                case ItemEffectBuildMode::NO_BUILD: bm = "NO_BUILD"; break;
                default: break;
            }
            const char* um = "?";
            switch (b.upkeep_mode) {
                case ItemEffectUpkeepMode::NORMAL_UPKEEP: um = "NORMAL_UPKEEP"; break;
                case ItemEffectUpkeepMode::NO_UPKEEP: um = "NO_UPKEEP"; break;
                default: break;
            }
            if (b.building_id == U16_KEY_NULL) {
                fprintf(out(), " build");
            } else if (m_building_sd != NULL && b.building_id < m_building_sd->get_item_count()) {
                fprintf(out(), " build %s (%u)", m_building_sd->get_name(BuildingStaticDataKey::from_raw(b.building_id)), static_cast<u32>(b.building_id));
            } else if (m_building_psr != NULL) {
                fprintf(out(), " build %s (%u)", m_building_psr->idx_to_name(b.building_id), static_cast<u32>(b.building_id));
            } else {
                fprintf(out(), " build <unknown> (%u)", static_cast<u32>(b.building_id));
            }
            fprintf(out(), " scope=%s", sc);
            fprintf(out(), " build_mode=%s upkeep=%s", bm, um);
            break;
        }
        case ItemEffectType::ENABLE_CITY: {
            const ItemEffectEnable& en = slot.effect.enable;
            if (en.feature_id == U16_KEY_NULL) {
                fprintf(out(), " enableCity");
            } else if (m_toggle_city_sd != NULL && en.feature_id < m_toggle_city_sd->get_item_count()) {
                fprintf(out(), " enableCity %s (%u)", m_toggle_city_sd->get_name(ToggleCityStaticDataKey::from_raw(en.feature_id)), static_cast<u32>(en.feature_id));
            } else if (m_toggle_city_psr != NULL) {
                fprintf(out(), " enableCity %s (%u)", m_toggle_city_psr->idx_to_name(en.feature_id), static_cast<u32>(en.feature_id));
            } else {
                fprintf(out(), " enableCity <unknown> (%u)", static_cast<u32>(en.feature_id));
            }
            break;
        }
        case ItemEffectType::ENABLE_CIV: {
            const ItemEffectEnable& en = slot.effect.enable;
            if (en.feature_id == U16_KEY_NULL) {
                fprintf(out(), " enableCiv");
            } else if (m_toggle_civ_sd != NULL && en.feature_id < m_toggle_civ_sd->get_item_count()) {
                fprintf(out(), " enableCiv %s (%u)", m_toggle_civ_sd->get_name(ToggleCivStaticDataKey::from_raw(en.feature_id)), static_cast<u32>(en.feature_id));
            } else if (m_toggle_civ_psr != NULL) {
                fprintf(out(), " enableCiv %s (%u)", m_toggle_civ_psr->idx_to_name(en.feature_id), static_cast<u32>(en.feature_id));
            } else {
                fprintf(out(), " enableCiv <unknown> (%u)", static_cast<u32>(en.feature_id));
            }
            break;
        }
        case ItemEffectType::ENABLE_GLOBAL: {
            const ItemEffectEnable& en = slot.effect.enable;
            if (en.feature_id == U16_KEY_NULL) {
                fprintf(out(), " enableGlobal");
            } else if (m_toggle_global_sd != NULL && en.feature_id < m_toggle_global_sd->get_item_count()) {
                fprintf(out(), " enableGlobal %s (%u)", m_toggle_global_sd->get_name(ToggleGlobalStaticDataKey::from_raw(en.feature_id)), static_cast<u32>(en.feature_id));
            } else if (m_toggle_global_psr != NULL) {
                fprintf(out(), " enableGlobal %s (%u)", m_toggle_global_psr->idx_to_name(en.feature_id), static_cast<u32>(en.feature_id));
            } else {
                fprintf(out(), " enableGlobal <unknown> (%u)", static_cast<u32>(en.feature_id));
            }
            break;
        }
        case ItemEffectType::RESEARCH_TECH: {
            const ItemEffectResearchTech& rt = slot.effect.research_tech;
            fprintf(out(), " researchTech (%u)", static_cast<u32>(rt.tech_count));
            break;
        }
        case ItemEffectType::TRAIN: {
            const ItemEffectTrain& tr = slot.effect.train;
            if (tr.unit_id == U16_KEY_NULL) {
                fprintf(out(), " train");
            } else if (m_unit_sd != NULL && tr.unit_id < m_unit_sd->get_item_count()) {
                fprintf(out(), " train %s (%u)", m_unit_sd->get_name(UnitStaticDataKey::from_raw(tr.unit_id)), static_cast<u32>(tr.unit_id));
            } else if (m_unit_psr != NULL) {
                fprintf(out(), " train %s (%u)", m_unit_psr->idx_to_name(tr.unit_id), static_cast<u32>(tr.unit_id));
            } else {
                fprintf(out(), " train <unknown> (%u)", static_cast<u32>(tr.unit_id));
            }
            if (tr.turns_interval != 0) {
                fprintf(out(), " interval=%u", static_cast<u32>(tr.turns_interval));
            }
            break;
        }
        case ItemEffectType::SET_FLAG: {
            const ItemEffectSetFlag& sf = slot.effect.set_flag;
            const char* sc = "?";
            switch (sf.scope) {
                case ItemEffectsScope::LOCAL: sc = "LOCAL"; break;
                case ItemEffectsScope::CITY: sc = "CITY"; break;
                case ItemEffectsScope::CIV: sc = "CIV"; break;
                case ItemEffectsScope::GLOBAL: sc = "GLOBAL"; break;
                default: break;
            }
            if (sf.flag_id == U16_KEY_NULL) {
                fprintf(out(), " setFlag");
            } else if (m_toggle_city_sd != NULL && sf.flag_id < m_toggle_city_sd->get_item_count()) {
                fprintf(out(), " setFlag %s (%u)", m_toggle_city_sd->get_name(ToggleCityStaticDataKey::from_raw(sf.flag_id)), static_cast<u32>(sf.flag_id));
            } else if (m_toggle_city_psr != NULL) {
                fprintf(out(), " setFlag %s (%u)", m_toggle_city_psr->idx_to_name(sf.flag_id), static_cast<u32>(sf.flag_id));
            } else {
                fprintf(out(), " setFlag <unknown> (%u)", static_cast<u32>(sf.flag_id));
            }
            fprintf(out(), " scope=%s", sc);
            break;
        }
        case ItemEffectType::PRODUCE: {
            const ItemEffectProduce& pr = slot.effect.produce;
            if (pr.kind == ItemProduceKind::YIELD) {
                const ItemProduceYield yv = static_cast<ItemProduceYield>(pr.target_id);
                fprintf(out(), " produce %s (%u)", ItemEffectHelper::produce_yield_enum_to_str(yv), static_cast<u32>(pr.target_id));
            } else if (pr.target_id == U16_KEY_NULL) {
                fprintf(out(), " produce");
            } else if (m_resource_sd != NULL && pr.target_id < m_resource_sd->get_item_count()) {
                fprintf(out(), " produce %s (%u)", m_resource_sd->get_name(ResourceStaticDataKey::from_raw(pr.target_id)), static_cast<u32>(pr.target_id));
            } else if (m_resource_psr != NULL) {
                fprintf(out(), " produce %s (%u)", m_resource_psr->idx_to_name(pr.target_id), static_cast<u32>(pr.target_id));
            } else {
                fprintf(out(), " produce <unknown> (%u)", static_cast<u32>(pr.target_id));
            }
            fprintf(out(), " amount=%d", static_cast<int>(pr.amount));
            break;
        }
        case ItemEffectType::JOB_SLOTS: {
            const ItemEffectJobSlots& js = slot.effect.job_slots;
            if (js.job_id == U16_KEY_NULL) {
                fprintf(out(), " jobSlots");
            } else if (m_city_job_sd != NULL && js.job_id < m_city_job_sd->get_item_count()) {
                fprintf(out(), " jobSlots %s (%u)", m_city_job_sd->get_name(CityJobStaticDataKey::from_raw(js.job_id)), static_cast<u32>(js.job_id));
            } else if (m_city_job_psr != NULL) {
                fprintf(out(), " jobSlots %s (%u)", m_city_job_psr->idx_to_name(js.job_id), static_cast<u32>(js.job_id));
            } else {
                fprintf(out(), " jobSlots <unknown> (%u)", static_cast<u32>(js.job_id));
            }
            const char* sc = "?";
            switch (js.scope) {
                case ItemEffectsScope::LOCAL: sc = "LOCAL"; break;
                case ItemEffectsScope::CITY: sc = "CITY"; break;
                case ItemEffectsScope::CIV: sc = "CIV"; break;
                case ItemEffectsScope::GLOBAL: sc = "GLOBAL"; break;
                default: break;
            }
            const char* am = "?";
            switch (js.amount_mode) {
                case ItemEffectAmountMode::COUNT: am = "COUNT"; break;
                case ItemEffectAmountMode::PERCENTAGE: am = "PERCENTAGE"; break;
                default: break;
            }
            fprintf(out(), " (%d) scope=%s mode=%s", static_cast<int>(js.amount), sc, am);
            break;
        }
        case ItemEffectType::TERRAIN_BOOSTER:
            fprintf(out(), " TERRAIN_BOOSTER");
            break;
        default:
            fprintf(out(), " <unhandled>");
            break;
        }
        fprintf(out(), "\n");
    }
}

void WorkerJobImpParserTester::pr_traits (cstr label, const CivTraitStruct& traits) {
    fprintf(out(), "  %s:\n", label);
    for (u32 j = 0; j < MAX_CIV_TRAIT_COUNT; ++j) {
        const u16 tix = traits.indices[j];
        if (tix == U16_KEY_NULL) {
            continue;
        }
        if (m_civ_trait_sd != NULL && tix < m_civ_trait_sd->get_item_count()) {
            fprintf(out(), "    [%u] %s (%u)\n", j, m_civ_trait_sd->get_name(CivTraitStaticDataKey::from_raw(tix)), tix);
        } else if (m_civ_trait_psr != NULL) {
            fprintf(out(), "    [%u] %s (%u)\n", j, m_civ_trait_psr->idx_to_name(tix), tix);
        } else {
            fprintf(out(), "    [%u] <unknown> (%u)\n", j, tix);
        }
    }
}



void WorkerJobImpParserTester::pr_item (cstr name, const WorkerJobImpStaticDataStruct& item) {
    fprintf(out(), "name: %s\n", name);
    pr_u16("map_overlay_idx", item.map_overlay_idx);
    pr_u32("cost", item.cost);
    pr_reqs("reqs", item.reqs);
    pr_fx("effects", item.effects);
}

int WorkerJobImpParserTester::run () {
    s_inst = this;
    NameToIdxCbs cbs = {};

    cbs.building_name_to_idx = st_building_n2i;
    cbs.toggle_city_name_to_idx = st_toggle_city_n2i;
    cbs.toggle_civ_name_to_idx = st_toggle_civ_n2i;
    cbs.toggle_global_name_to_idx = st_toggle_global_n2i;
    cbs.city_job_name_to_idx = st_city_job_n2i;
    cbs.civ_name_to_idx = st_civ_n2i;
    cbs.civ_trait_name_to_idx = st_civ_trait_n2i;
    cbs.tile_attribute_name_to_idx = st_tile_attribute_n2i;
    cbs.resource_name_to_idx = st_resource_n2i;
    cbs.res_dist_name_to_idx = st_res_dist_n2i;
    cbs.res_type_name_to_idx = st_res_type_n2i;
    cbs.small_wonder_name_to_idx = st_small_wonder_n2i;
    cbs.tech_era_name_to_idx = st_tech_era_n2i;
    cbs.tech_age_name_to_idx = st_tech_age_n2i;
    cbs.tech_name_to_idx = st_tech_n2i;
    cbs.unit_action_name_to_idx = st_unit_action_n2i;
    cbs.unit_role_name_to_idx = st_unit_role_n2i;
    cbs.unit_type_name_to_idx = st_unit_type_n2i;
    cbs.unit_domain_name_to_idx = st_unit_domain_n2i;
    cbs.unit_name_to_idx = st_unit_n2i;
    cbs.wonder_name_to_idx = st_wonder_n2i;
    cbs.map_overlay_name_to_idx = st_map_overlay_n2i;
    cbs.map_attribute_name_to_idx = st_map_attribute_n2i;
    cbs.map_terrain_name_to_idx = st_map_terrain_n2i;
    cbs.map_climate_name_to_idx = st_map_climate_n2i;
    cbs.worker_job_target_name_to_idx = st_worker_job_target_n2i;
    cbs.worker_job_type_name_to_idx = st_worker_job_type_n2i;
    cbs.worker_job_name_to_idx = st_worker_job_n2i;
    cbs.worker_job_imp_name_to_idx = st_worker_job_imp_n2i;
    cbs.tile_yield_type_name_to_idx = st_tile_yield_type_n2i;
    cbs.improvement_yield_name_to_idx = st_improvement_yield_n2i;

    PathMng paths("../");

    StringManager building_items;
    StringManager toggle_city_items;
    StringManager toggle_civ_items;
    StringManager toggle_global_items;
    StringManager city_job_items;
    StringManager civ_items;
    StringManager civ_trait_items;
    StringManager tile_attribute_items;
    StringManager resource_items;
    StringManager res_dist_items;
    StringManager res_type_items;
    StringManager small_wonder_items;
    StringManager tech_era_items;
    StringManager tech_age_items;
    StringManager tech_items;
    StringManager unit_action_items;
    StringManager unit_role_items;
    StringManager unit_type_items;
    StringManager unit_domain_items;
    StringManager unit_items;
    StringManager wonder_items;
    StringManager map_overlay_items;
    StringManager map_attribute_items;
    StringManager map_terrain_items;
    StringManager map_climate_items;
    StringManager worker_job_target_items;
    StringManager worker_job_type_items;
    StringManager worker_job_items;
    StringManager worker_job_imp_items;
    StringManager tile_yield_type_items;
    StringManager improvement_yield_items;

    StringManager effect_items;

    ld_sm(building_items, paths.get_path_to_buildings());
    ld_sm(toggle_city_items, paths.get_path_to_toggle_city());
    ld_sm(toggle_civ_items, paths.get_path_to_toggle_civ());
    ld_sm(toggle_global_items, paths.get_path_to_toggle_global());
    ld_sm(city_job_items, paths.get_path_to_city_jobs());
    ld_sm(civ_items, paths.get_path_to_civs());
    ld_sm(civ_trait_items, paths.get_path_to_civ_traits());
    ld_sm(tile_attribute_items, paths.get_path_to_tile_attributes());
    ld_sm(resource_items, paths.get_path_to_resources());
    ld_sm(res_dist_items, paths.get_path_to_res_dists());
    ld_sm(res_type_items, paths.get_path_to_res_types());
    ld_sm(small_wonder_items, paths.get_path_to_small_wonders());
    ld_sm(tech_era_items, paths.get_path_to_tech_eras());
    ld_sm(tech_age_items, paths.get_path_to_tech_ages());
    ld_sm(tech_items, paths.get_path_to_techs());
    ld_sm(unit_action_items, paths.get_path_to_unit_actions());
    ld_sm(unit_role_items, paths.get_path_to_unit_roles());
    ld_sm(unit_type_items, paths.get_path_to_unit_types());
    ld_sm(unit_domain_items, paths.get_path_to_unit_domains());
    ld_sm(unit_items, paths.get_path_to_units());
    ld_sm(wonder_items, paths.get_path_to_wonders());
    ld_sm(map_overlay_items, paths.get_path_to_map_overlays());
    ld_sm(map_attribute_items, paths.get_path_to_map_attributes());
    ld_sm(map_terrain_items, paths.get_path_to_map_terrains());
    ld_sm(map_climate_items, paths.get_path_to_map_climates());
    ld_sm(worker_job_target_items, paths.get_path_to_worker_job_targets());
    ld_sm(worker_job_type_items, paths.get_path_to_worker_job_types());
    ld_sm(worker_job_items, paths.get_path_to_worker_jobs());
    ld_sm(worker_job_imp_items, paths.get_path_to_worker_job_imps());
    ld_sm(tile_yield_type_items, paths.get_path_to_tile_yield_types());
    ld_sm(improvement_yield_items, paths.get_path_to_improvement_yields());

    const bool fx_ok = ld_sm(effect_items, paths.get_path_to_effects());
    if (fx_ok) {
        DataParserBase::set_item_effect_handler(&cbs, &effect_items);
    }

    DataParserBase building_parser(building_items, cbs);
    DataParserBase toggle_city_parser(toggle_city_items, cbs);
    DataParserBase toggle_civ_parser(toggle_civ_items, cbs);
    DataParserBase toggle_global_parser(toggle_global_items, cbs);
    DataParserBase city_job_parser(city_job_items, cbs);
    DataParserBase civ_parser(civ_items, cbs);
    DataParserBase civ_trait_parser(civ_trait_items, cbs);
    DataParserBase tile_attribute_parser(tile_attribute_items, cbs);
    DataParserBase resource_parser(resource_items, cbs);
    DataParserBase res_dist_parser(res_dist_items, cbs);
    DataParserBase res_type_parser(res_type_items, cbs);
    DataParserBase small_wonder_parser(small_wonder_items, cbs);
    DataParserBase tech_era_parser(tech_era_items, cbs);
    DataParserBase tech_age_parser(tech_age_items, cbs);
    DataParserBase tech_parser(tech_items, cbs);
    DataParserBase unit_action_parser(unit_action_items, cbs);
    DataParserBase unit_role_parser(unit_role_items, cbs);
    DataParserBase unit_type_parser(unit_type_items, cbs);
    DataParserBase unit_domain_parser(unit_domain_items, cbs);
    DataParserBase unit_parser(unit_items, cbs);
    DataParserBase wonder_parser(wonder_items, cbs);
    DataParserBase map_overlay_parser(map_overlay_items, cbs);
    DataParserBase map_attribute_parser(map_attribute_items, cbs);
    DataParserBase map_terrain_parser(map_terrain_items, cbs);
    DataParserBase map_climate_parser(map_climate_items, cbs);
    DataParserBase worker_job_target_parser(worker_job_target_items, cbs);
    DataParserBase worker_job_type_parser(worker_job_type_items, cbs);
    DataParserBase worker_job_parser(worker_job_items, cbs);
    DataParserBase worker_job_imp_parser(worker_job_imp_items, cbs);
    DataParserBase tile_yield_type_parser(tile_yield_type_items, cbs);
    DataParserBase improvement_yield_parser(improvement_yield_items, cbs);

    m_building_psr = &building_parser;
    m_toggle_city_psr = &toggle_city_parser;
    m_toggle_civ_psr = &toggle_civ_parser;
    m_toggle_global_psr = &toggle_global_parser;
    m_city_job_psr = &city_job_parser;
    m_civ_psr = &civ_parser;
    m_civ_trait_psr = &civ_trait_parser;
    m_tile_attribute_psr = &tile_attribute_parser;
    m_resource_psr = &resource_parser;
    m_res_dist_psr = &res_dist_parser;
    m_res_type_psr = &res_type_parser;
    m_small_wonder_psr = &small_wonder_parser;
    m_tech_era_psr = &tech_era_parser;
    m_tech_age_psr = &tech_age_parser;
    m_tech_psr = &tech_parser;
    m_unit_action_psr = &unit_action_parser;
    m_unit_role_psr = &unit_role_parser;
    m_unit_type_psr = &unit_type_parser;
    m_unit_domain_psr = &unit_domain_parser;
    m_unit_psr = &unit_parser;
    m_wonder_psr = &wonder_parser;
    m_map_overlay_psr = &map_overlay_parser;
    m_map_attribute_psr = &map_attribute_parser;
    m_map_terrain_psr = &map_terrain_parser;
    m_map_climate_psr = &map_climate_parser;
    m_worker_job_target_psr = &worker_job_target_parser;
    m_worker_job_type_psr = &worker_job_type_parser;
    m_worker_job_psr = &worker_job_parser;
    m_worker_job_imp_psr = &worker_job_imp_parser;
    m_tile_yield_type_psr = &tile_yield_type_parser;
    m_improvement_yield_psr = &improvement_yield_parser;

    StringManager raw_items;
    if (!ld_sm(raw_items, paths.get_path_to_worker_job_imps())) {
        s_inst = NULL;
        return 0;
    }
    if (raw_items.get_string_count() == 0) {
        s_inst = NULL;
        return 0;
    }
    WorkerJobImpParser parser(raw_items, cbs);
    WorkerJobImpStaticDataStruct* parsed_data = parser.parse_data_dependencies();
    if (m_plvl >= 2) {
        for (u32 i = 0; i < raw_items.get_string_count(); ++i) {
            pr_item(parser.idx_to_name(i), parsed_data[i]);
            printf("-----------------------------------------------------------\n");
        }
    }
    delete[] parsed_data;
    s_inst = NULL;
    return 0;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
