//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef WORKER_JOB_IMP_ENUM_H
#define WORKER_JOB_IMP_ENUM_H

#include "game_primitives.h"

//================================================================================================================================
//=> - WorkerJobImp -
//================================================================================================================================
//
//  Fixed catalog indices for worker_job_imp rows. Member order must match game_config.worker_job_imps load order.
//
//================================================================================================================================

enum class WorkerJobImp : u16 {
    Wooden_Timbering = 0,
    Leat_Systems = 1,
    Animal_Powered_Whims = 2,
    Treadwheel_Cranes = 3,
    Dewatering_Wheels = 4,
    Washing_Tables = 5,
    Drainage_Adits = 6,
    Ventilation_Stacks = 7,
    Steam_Pumps = 8,
    Rail_Siding = 9,
    Electric_Elevators = 10,
    Heavy_Dump_Trucks = 11,
    Open_Pit_Terraces = 12,
    Steel_Headframes = 13,
    Conveyor_Networks = 14,
    Autonomous_Haulers = 15,
    Extensive_Enclosures = 16,
    Terraced_Plots = 17,
    Sluice_Irrigation = 18,
    Animal_Powered_Mills = 19,
    Well_Sweep_Networks = 20,
    Packing_Houses = 21,
    Windmills = 22,
    Steam_Powered_Mills = 23,
    Narrow_Gauge_Rail = 24,
    Mechanized_Reapers = 25,
    Cold_Storage_Plants = 26,
    Tractor_Fleets = 27,
    Pesticide_Silos = 28,
    Hydroponic_Bays = 29,
    Drone_Docks = 30,
    Vertical_Pods = 31,
    Palisade_Walls = 32,
    Dry_Moats = 33,
    Curtain_Walls = 34,
    Gatehouse_Barbicans = 35,
    Concentric_Rings = 36,
    Star_Fortifications = 37,
    Outwork_Ravelins = 38,
    Casemate_Batteries = 39,
    Caponier_Bunkers = 40,
    Polygonal_Bastions = 41,
    Concrete_Pillboxes = 42,
    Barbed_Wire_Belts = 43,
    Flak_Towers = 44,
    Hardened_Silos = 45,
    Phalanx_CIWS = 46,
    Aegis_Shields = 47
};

#endif // WORKER_JOB_IMP_ENUM_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
