//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef WORKER_JOB_IMP_ENUM_H
#define WORKER_JOB_IMP_ENUM_H

#include "game_primitives.h"

//================================================================================================================================
//=> - WorkerJobImp -
//================================================================================================================================
//
//  Fixed catalog indices for worker_job_imp rows. Member order must match game_config.worker_job_imps load order.
//
//================================================================================================================================

enum class WorkerJobImp : u16 {
    Irrigation = 0,
    Water_Mill = 1,
    Saw_Mill = 2,
    Water_Mill_3 = 3,
    Wooden_Timbering = 4,
    Leat_Systems = 5,
    Animal_Powered_Whims = 6,
    Treadwheel_Cranes = 7,
    Dewatering_Wheels = 8,
    Washing_Tables = 9,
    Drainage_Adits = 10,
    Ventilation_Stacks = 11,
    Steam_Pumps = 12,
    Rail_Siding = 13,
    Electric_Elevators = 14,
    Heavy_Dump_Trucks = 15,
    Open_Pit_Terraces = 16,
    Steel_Headframes = 17,
    Conveyor_Networks = 18,
    Autonomous_Haulers = 19,
    Extensive_Enclosures = 20,
    Terraced_Plots = 21,
    Sluice_Irrigation = 22,
    Animal_Powered_Mills = 23,
    Well_Sweep_Networks = 24,
    Packing_Houses = 25,
    Windmills = 26,
    Steam_Powered_Mills = 27,
    Narrow_Gauge_Rail = 28,
    Mechanized_Reapers = 29,
    Cold_Storage_Plants = 30,
    Tractor_Fleets = 31,
    Pesticide_Silos = 32,
    Hydroponic_Bays = 33,
    Drone_Docks = 34,
    Vertical_Pods = 35,
    Palisade_Walls = 36,
    Dry_Moats = 37,
    Curtain_Walls = 38,
    Gatehouse_Barbicans = 39,
    Concentric_Rings = 40,
    Star_Fortifications = 41,
    Outwork_Ravelins = 42,
    Casemate_Batteries = 43,
    Caponier_Bunkers = 44,
    Polygonal_Bastions = 45,
    Concrete_Pillboxes = 46,
    Barbed_Wire_Belts = 47,
    Flak_Towers = 48,
    Hardened_Silos = 49,
    Phalanx_CIWS = 50,
    Aegis_Shields = 51
};

#endif // WORKER_JOB_IMP_ENUM_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
