//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py from TEMPLATE_assessor_brute_shared.cpp
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include <cstdio>
#include <cstring>

#include "assessor_brute_shared.h"
#include "assessor_brute_write.h"
#include "general_assessor.h"
#include "bit_array.h"
#include "static_parsing_manager.h"

//================================================================================================================================
//=> - InferredReqs helpers -
//================================================================================================================================

static void add_u16 (u16* arr, u8* n, u16 v) {
    for (u8 i = 0; i < *n; ++i) {
        if (arr[i] == v) {
            return;
        }
    }
    if (*n < BRUTE_MAX_PER_TYPE) {
        arr[*n] = v;
        ++(*n);
    }
}

static void add_en (EnSlot& slot, u16 item_idx) {
    for (u16 i = 0; i < slot.m_n; ++i) {
        if (slot.m_items[i] == item_idx) {
            return;
        }
    }
    if (slot.m_n < BRUTE_MAX_ENABLED) {
        slot.m_items[slot.m_n] = item_idx;
        ++slot.m_n;
    }
}

static void set_all (BitArrayCL& tech, BitArrayCL& resource, BitArrayCL& building, BitArrayCL& city_flag, BitArrayCL& civ, const StaticParsingManager& mgr, bool building_all) {
    u32 tech_count = mgr.get_tech_count();
    for (u32 i = 0; i < tech_count; ++i) {
        tech.set_bit(i);
    }
    u32 resource_count = mgr.get_resource_count();
    for (u32 i = 0; i < resource_count; ++i) {
        resource.set_bit(i);
    }
    u32 city_flag_count = mgr.get_city_flag_count();
    for (u32 i = 0; i < city_flag_count; ++i) {
        city_flag.set_bit(i);
    }
    u32 civ_count = mgr.get_civ_count();
    for (u32 i = 0; i < civ_count; ++i) {
        civ.set_bit(i);
    }
    if (building_all) {
        u32 building_count = mgr.get_building_count();
        for (u32 i = 0; i < building_count; ++i) {
            building.set_bit(i);
        }
    }
}

static void free_en_map (EnablesMap& en) {
    delete[] en.m_tech;
    en.m_tech = nullptr;
    delete[] en.m_resource;
    en.m_resource = nullptr;
    delete[] en.m_building;
    en.m_building = nullptr;
    delete[] en.m_city_flag;
    en.m_city_flag = nullptr;
    delete[] en.m_civ;
    en.m_civ = nullptr;
}

static EnablesMap make_en_map (u32 tech_count, u32 resource_count, u32 building_count, u32 city_flag_count, u32 civ_count) {
    EnablesMap en = {};
    en.m_tech_count = tech_count;
    en.m_tech = new EnSlot[tech_count];
    for (u32 i = 0; i < tech_count; ++i) {
        en.m_tech[i] = {};
    }
    en.m_resource_count = resource_count;
    en.m_resource = new EnSlot[resource_count];
    for (u32 i = 0; i < resource_count; ++i) {
        en.m_resource[i] = {};
    }
    en.m_building_count = building_count;
    en.m_building = new EnSlot[building_count];
    for (u32 i = 0; i < building_count; ++i) {
        en.m_building[i] = {};
    }
    en.m_city_flag_count = city_flag_count;
    en.m_city_flag = new EnSlot[city_flag_count];
    for (u32 i = 0; i < city_flag_count; ++i) {
        en.m_city_flag[i] = {};
    }
    en.m_civ_count = civ_count;
    en.m_civ = new EnSlot[civ_count];
    for (u32 i = 0; i < civ_count; ++i) {
        en.m_civ[i] = {};
    }
    return en;
}

//================================================================================================================================
//=> - AssessorBrute implementation -
//================================================================================================================================

int AssessorBrute::run (const StaticParsingManager& mgr, const BruteRunCfg& cfg) {
    if (cfg.m_item_count == 0 || cfg.m_assess == nullptr) {
        return 0;
    }

    u32 tech_count = mgr.get_tech_count();
    u32 resource_count = mgr.get_resource_count();
    u32 building_count = mgr.get_building_count();
    u32 city_flag_count = mgr.get_city_flag_count();
    u32 civ_count = mgr.get_civ_count();

    BitArrayCL tech(tech_count);
    BitArrayCL resource(resource_count);
    BitArrayCL building(building_count);
    BitArrayCL city_flag(city_flag_count);
    BitArrayCL civ(civ_count);

    InferredReqs* inferred = new InferredReqs[cfg.m_item_count];
    for (u16 i = 0; i < cfg.m_item_count; ++i) {
        inferred[i] = {};
    }
    EnablesMap en = make_en_map(tech_count, resource_count, building_count, city_flag_count, civ_count);
    auto snap = [&](AssessorCtx& ctx) {
        ctx.m_tech = &tech;
        ctx.m_civ = &civ;
        ctx.m_city_idx = 0;
        ctx.m_resource_bank = nullptr;
        ctx.m_building_bank = nullptr;
        ctx.m_city_flag_bank = nullptr;
        ctx.m_resource = &resource;
        ctx.m_building = &building;
        ctx.m_city_flag = &city_flag;
    };
    bool building_for_ablation = cfg.m_init_building_all || cfg.m_building_isolate;
    auto set_base = [&]() {
        set_all(tech, resource, building, city_flag, civ, mgr, building_for_ablation);
    };
    AssessorCtx ctx = {};
    snap(ctx);
    set_base();
    BitArrayCL baseline_scratch(cfg.m_item_count);
    cfg.m_assess(&baseline_scratch, cfg.m_item_count, ctx);

    for (u32 tech_i = 0; tech_i < tech_count; ++tech_i) {
        set_base();
        tech.clear_bit(tech_i);
        snap(ctx);
        BitArrayCL cur_scratch(cfg.m_item_count);
        cfg.m_assess(&cur_scratch, cfg.m_item_count, ctx);
        for (u16 i = 0; i < cfg.m_item_count; ++i) {
            if (baseline_scratch.get_bit(i) == 1 && cur_scratch.get_bit(i) != 1) {
                add_u16(inferred[i].m_tech, &inferred[i].m_tech_n, (u16)tech_i);
                add_en(en.m_tech[tech_i], i);
            }
        }
    }
    for (u32 resource_i = 0; resource_i < resource_count; ++resource_i) {
        set_base();
        resource.clear_bit(resource_i);
        snap(ctx);
        BitArrayCL cur_scratch(cfg.m_item_count);
        cfg.m_assess(&cur_scratch, cfg.m_item_count, ctx);
        for (u16 i = 0; i < cfg.m_item_count; ++i) {
            if (baseline_scratch.get_bit(i) == 1 && cur_scratch.get_bit(i) != 1) {
                add_u16(inferred[i].m_resource, &inferred[i].m_resource_n, (u16)resource_i);
                add_en(en.m_resource[resource_i], i);
            }
        }
    }
    for (u32 city_flag_i = 0; city_flag_i < city_flag_count; ++city_flag_i) {
        set_base();
        city_flag.clear_bit(city_flag_i);
        snap(ctx);
        BitArrayCL cur_scratch(cfg.m_item_count);
        cfg.m_assess(&cur_scratch, cfg.m_item_count, ctx);
        for (u16 i = 0; i < cfg.m_item_count; ++i) {
            if (baseline_scratch.get_bit(i) == 1 && cur_scratch.get_bit(i) != 1) {
                add_u16(inferred[i].m_city_flag, &inferred[i].m_city_flag_n, (u16)city_flag_i);
                add_en(en.m_city_flag[city_flag_i], i);
            }
        }
    }
    for (u32 civ_i = 0; civ_i < civ_count; ++civ_i) {
        set_base();
        civ.clear_bit(civ_i);
        snap(ctx);
        BitArrayCL cur_scratch(cfg.m_item_count);
        cfg.m_assess(&cur_scratch, cfg.m_item_count, ctx);
        for (u16 i = 0; i < cfg.m_item_count; ++i) {
            if (baseline_scratch.get_bit(i) == 1 && cur_scratch.get_bit(i) != 1) {
                add_u16(inferred[i].m_civ, &inferred[i].m_civ_n, (u16)civ_i);
                add_en(en.m_civ[civ_i], i);
            }
        }
    }

    if (cfg.m_building_isolate) {
        for (u32 b = 0; b < building_count; ++b) {
            set_all(tech, resource, building, city_flag, civ, mgr, true);
            for (u32 i = 0; i < building_count; ++i) {
                building.set_bit(i);
            }
            building.clear_bit(b);
            snap(ctx);
            BitArrayCL bl_scratch(cfg.m_item_count);
            cfg.m_assess(&bl_scratch, cfg.m_item_count, ctx);
            for (u32 bb = 0; bb < building_count; ++bb) {
                if (bb == b) {
                    continue;
                }
                building.clear_bit(bb);
                snap(ctx);
                BitArrayCL cur_scratch(cfg.m_item_count);
                cfg.m_assess(&cur_scratch, cfg.m_item_count, ctx);
                if (bl_scratch.get_bit(b) == 1 && cur_scratch.get_bit(b) != 1) {
                    add_u16(inferred[b].m_building, &inferred[b].m_building_n, (u16)bb);
                    add_en(en.m_building[bb], b);
                }
                building.set_bit(bb);
            }
        }
    } else if (cfg.m_init_building_all) {
        for (u32 building_i = 0; building_i < building_count; ++building_i) {
            set_base();
            building.clear_bit(building_i);
            snap(ctx);
            BitArrayCL cur_scratch(cfg.m_item_count);
            cfg.m_assess(&cur_scratch, cfg.m_item_count, ctx);
            for (u16 i = 0; i < cfg.m_item_count; ++i) {
                if (baseline_scratch.get_bit(i) == 1 && cur_scratch.get_bit(i) != 1) {
                    add_u16(inferred[i].m_building, &inferred[i].m_building_n, (u16)building_i);
                    add_en(en.m_building[building_i], i);
                }
            }
        }
    }

    int rc_out = 0;
    if (cfg.m_results_to_match_path != nullptr) {
        FILE* out = std::fopen(cfg.m_results_to_match_path, "w");
        if (out == nullptr) {
            rc_out = 1;
        } else {
            for (u16 i = 0; i < cfg.m_item_count; ++i) {
                if (cfg.m_emit_line != nullptr) {
                    cfg.m_emit_line(out, i, inferred[i], cfg.m_emit_ud);
                }
            }
            std::fclose(out);
        }
    }
    if (cfg.m_results_readable_path != nullptr) {
        FILE* rout = std::fopen(cfg.m_results_readable_path, "w");
        if (rout == nullptr) {
            rc_out = 1;
        } else {
            AssessorBruteWrite::write_readable(rout, en, mgr, cfg);
            std::fclose(rout);
        }
    }
    delete[] inferred;
    free_en_map(en);
    return rc_out;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
