//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py from TEMPLATE_general_assessor.h
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef GENERAL_ASSESSOR_H
#define GENERAL_ASSESSOR_H

#include "item_reqs.h"
#include "game_primitives.h"

class BitArrayCL;
class GeneralBitBank;

struct BuildingStaticDataStruct;
struct CityFlagStaticDataStruct;
struct ResourceStaticDataStruct;
struct SmallWonderStaticDataStruct;
struct TechStaticDataStruct;
struct UnitStaticDataStruct;
struct WonderStaticDataStruct;

//================================================================================================================================
//=> - AssessorCtx -
//================================================================================================================================

struct AssessorCtx {
    const BitArrayCL* m_tech;
    const BitArrayCL* m_civ;
    u16 m_city_idx;
    const GeneralBitBank* m_resource_bank;
    const GeneralBitBank* m_building_bank;
    const GeneralBitBank* m_city_flag_bank;
    const BitArrayCL* m_resource;
    const BitArrayCL* m_building;
    const BitArrayCL* m_city_flag;
};

//================================================================================================================================
//=> - GeneralAssessor -
//================================================================================================================================

class GeneralAssessor {
public:
    static bool chk (const ItemReqsStruct& reqs, const AssessorCtx& ctx);
    
    static void assess_building (BitArrayCL* out, u16 item_count, const BuildingStaticDataStruct* items, const AssessorCtx& ctx);
    static void assess_city_flag (BitArrayCL* out, u16 item_count, const CityFlagStaticDataStruct* items, const AssessorCtx& ctx);
    static void assess_resource (BitArrayCL* out, u16 item_count, const ResourceStaticDataStruct* items, const AssessorCtx& ctx);
    static void assess_small_wonder (BitArrayCL* out, u16 item_count, const SmallWonderStaticDataStruct* items, const AssessorCtx& ctx);
    static void assess_tech (BitArrayCL* out, u16 item_count, const TechStaticDataStruct* items, const AssessorCtx& ctx);
    static void assess_unit (BitArrayCL* out, u16 item_count, const UnitStaticDataStruct* items, const AssessorCtx& ctx);
    static void assess_wonder (BitArrayCL* out, u16 item_count, const WonderStaticDataStruct* items, const AssessorCtx& ctx);

private:
    GeneralAssessor () = delete;
    GeneralAssessor (const GeneralAssessor& other) = delete;
    GeneralAssessor (GeneralAssessor&& other) = delete;
};

#endif // GENERAL_ASSESSOR_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
