#!/bin/bash
set -e

cd "$(dirname "$0")"

INC="-I. -I../game_ui -I../game -I.. -I../map_loader -I../simple_map_gen -I../adv_map_gen -I../misc -I../data_io -I../static_state -I../dyn_state -I../gen_bit_banks -I../city/effector"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ $CXXFLAGS $INC -c ../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ $CXXFLAGS $INC -c ../map_loader/map_loader.cpp -o map_loader.o
g++ $CXXFLAGS $INC -c ../game/runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c ../misc/assert_log.cpp -o assert_log.o
g++ $CXXFLAGS $INC -c ../ai_proc/test_drivers/game_array_simple_link_stubs.cpp -o game_array_simple_link_stubs.o
g++ $CXXFLAGS $INC -c ../game/game_array_simple.cpp -o game_array_simple.o
g++ $CXXFLAGS $INC -c ../game/factory_game_array_simple.cpp -o factory_game_array_simple.o
g++ $CXXFLAGS $INC -c ../game_ui/intf_snapshot_view.cpp -o intf_snapshot_view.o
g++ $CXXFLAGS $INC -c ../game_ui/intf_mk1_snapshot_view.cpp -o intf_mk1_snapshot_view.o
g++ $CXXFLAGS $INC -c ../game_ui/intf_mk1_snapshot_view_ppm.cpp -o intf_mk1_snapshot_view_ppm.o
g++ $CXXFLAGS $INC -c hlp_canvas/map_mini.cpp -o map_mini.o
g++ $CXXFLAGS $INC -c col_morph.cpp -o col_morph.o
g++ $CXXFLAGS $INC -c dat15_io.cpp -o dat15_io.o
g++ $CXXFLAGS $INC -c dat31_io.cpp -o dat31_io.o
g++ $CXXFLAGS $INC -c map_model.cpp -o map_model.o
g++ $CXXFLAGS $INC -c map_tiler.cpp -o map_tiler.o
g++ $CXXFLAGS $INC -c map_view.cpp -o map_view.o
g++ $CXXFLAGS $INC -c map_tester.cpp -o map_tester.o

g++ $CXXFLAGS -o map_tester \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    runtime_trace_dbg.o \
    assert_log.o \
    game_array_simple_link_stubs.o \
    game_array_simple.o \
    factory_game_array_simple.o \
    intf_snapshot_view.o \
    intf_mk1_snapshot_view.o \
    intf_mk1_snapshot_view_ppm.o \
    map_mini.o \
    col_morph.o \
    dat15_io.o \
    dat31_io.o \
    map_model.o \
    map_tiler.o \
    map_view.o \
    map_tester.o \
    -lSDL2 -lSDL2_image -lSDL2_ttf

rm -f map_terrain_validate.o map_terrain_data.o map_loader.o runtime_trace_dbg.o \
    assert_log.o game_array_simple_link_stubs.o game_array_simple.o \
    factory_game_array_simple.o intf_snapshot_view.o intf_mk1_snapshot_view.o \
    intf_mk1_snapshot_view_ppm.o map_mini.o col_morph.o dat15_io.o dat31_io.o \
    map_model.o map_tiler.o map_view.o map_tester.o

echo "built ./map_tester"
