#!/bin/bash

# Define the include path for the compiler
INC="-I../"

# Compile objects
g++ $INC -c bit_array.cpp -o bit_array.o
g++ $INC -c bit_array_tester.cpp -o bit_array_tester.o

# Link everything into the final testers
g++ -o bit_array_tester bit_array.o bit_array_tester.o

# Clean up
rm bit_array.o bit_array_tester.o
