//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include "city_job_bit_array.h"

//================================================================================================================================
//=> - CityJobBitArray implementation -
//================================================================================================================================

CityJobBitArray::CityJobBitArray (u16 count) :
    m_flags(count) {
}

CityJobBitArray::~CityJobBitArray () {
}

bool CityJobBitArray::is_flagged (CityJobStaticDataKey key) const {
    return m_flags.get_bit(key.value()) != 0;
}

void CityJobBitArray::set_flag (CityJobStaticDataKey key) {
    m_flags.set_bit(key.value());
}

void CityJobBitArray::clear_flag (CityJobStaticDataKey key) {
    m_flags.clear_bit(key.value());
}

bool CityJobBitArray::can_access (u16 idx, CityJobStaticDataKey& out_key) const {
    if (idx >= m_flags.get_count()) {
        return false;
    }
    if (m_flags.get_bit(idx) == 0) {
        return false;
    }
    out_key = CityJobStaticDataKey::from_raw(idx);
    return true;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
