//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef CITY_JOB_BIT_ARRAY_H
#define CITY_JOB_BIT_ARRAY_H

#include "bit_array.h"
#include "game_primitives.h"
#include "city_job_static_key.h"

class GeneralAssessor;
class KeyHolder;

//================================================================================================================================
//=> - CityJobBitArray class -
//================================================================================================================================

class CityJobBitArray {
public:
    explicit CityJobBitArray (u16 count);
    ~CityJobBitArray ();

    bool is_flagged (u16 index) const;
    void set_flag (CityJobStaticDataKey key);
    void clear_flag (CityJobStaticDataKey key);

    bool can_access (u16 idx, CityJobStaticDataKey& out_key) const;

private:
    CityJobBitArray (const CityJobBitArray& other) = delete;
    CityJobBitArray (CityJobBitArray&& other) = delete;

    BitArrayCL m_flags;
};

#endif // CITY_JOB_BIT_ARRAY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
