//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef CIV_TRAIT_BIT_ARRAY_H
#define CIV_TRAIT_BIT_ARRAY_H

#include "bit_array.h"
#include "game_primitives.h"
#include "civ_trait_static_key.h"

class GeneralAssessor;
class KeyHolder;

//================================================================================================================================
//=> - CivTraitBitArray class -
//================================================================================================================================

class CivTraitBitArray {
public:
    explicit CivTraitBitArray (u16 count);
    ~CivTraitBitArray ();

    bool is_flagged (u16 index) const;
    void set_flag (CivTraitStaticDataKey key);
    void clear_flag (CivTraitStaticDataKey key);

    bool can_access (u16 idx, CivTraitStaticDataKey& out_key) const;

private:
    CivTraitBitArray (const CivTraitBitArray& other) = delete;
    CivTraitBitArray (CivTraitBitArray&& other) = delete;

    BitArrayCL m_flags;
};

#endif // CIV_TRAIT_BIT_ARRAY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
