//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include "map_terrain_bit_array.h"

//================================================================================================================================
//=> - MapTerrainBitArray implementation -
//================================================================================================================================

MapTerrainBitArray::MapTerrainBitArray (u16 count) :
    m_flags(count) {
}

MapTerrainBitArray::~MapTerrainBitArray () {
}

bool MapTerrainBitArray::is_flagged (MapTerrainStaticDataKey key) const {
    return m_flags.get_bit(key.value()) != 0;
}

void MapTerrainBitArray::set_flag (MapTerrainStaticDataKey key) {
    m_flags.set_bit(key.value());
}

void MapTerrainBitArray::clear_flag (MapTerrainStaticDataKey key) {
    m_flags.clear_bit(key.value());
}

bool MapTerrainBitArray::can_access (u16 idx, MapTerrainStaticDataKey& out_key) const {
    if (idx >= m_flags.get_count()) {
        return false;
    }
    if (m_flags.get_bit(idx) == 0) {
        return false;
    }
    out_key = MapTerrainStaticDataKey::from_raw(idx);
    return true;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
