//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef MAP_OVERLAY_BIT_ARRAY_H
#define MAP_OVERLAY_BIT_ARRAY_H

#include "bit_array.h"
#include "game_primitives.h"
#include "map_overlay_static_key.h"

class GeneralAssessor;
class KeyHolder;

//================================================================================================================================
//=> - MapOverlayBitArray class -
//================================================================================================================================

class MapOverlayBitArray {
public:
    explicit MapOverlayBitArray (u16 count);
    ~MapOverlayBitArray ();

    bool is_flagged (u16 index) const;
    void set_flag (MapOverlayStaticDataKey key);
    void clear_flag (MapOverlayStaticDataKey key);

    bool can_access (u16 idx, MapOverlayStaticDataKey& out_key) const;

private:
    MapOverlayBitArray (const MapOverlayBitArray& other) = delete;
    MapOverlayBitArray (MapOverlayBitArray&& other) = delete;

    BitArrayCL m_flags;
};

#endif // MAP_OVERLAY_BIT_ARRAY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
