//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include "map_overlay_bit_array.h"

//================================================================================================================================
//=> - MapOverlayBitArray implementation -
//================================================================================================================================

MapOverlayBitArray::MapOverlayBitArray (u16 count) :
    m_flags(count) {
}

MapOverlayBitArray::~MapOverlayBitArray () {
}

bool MapOverlayBitArray::is_flagged (MapOverlayStaticDataKey key) const {
    return m_flags.get_bit(key.value()) != 0;
}

void MapOverlayBitArray::set_flag (MapOverlayStaticDataKey key) {
    m_flags.set_bit(key.value());
}

void MapOverlayBitArray::clear_flag (MapOverlayStaticDataKey key) {
    m_flags.clear_bit(key.value());
}

bool MapOverlayBitArray::can_access (u16 idx, MapOverlayStaticDataKey& out_key) const {
    if (idx >= m_flags.get_count()) {
        return false;
    }
    if (m_flags.get_bit(idx) == 0) {
        return false;
    }
    out_key = MapOverlayStaticDataKey::from_raw(idx);
    return true;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
