//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef MAP_TERRAIN_BIT_ARRAY_H
#define MAP_TERRAIN_BIT_ARRAY_H

#include "bit_array.h"
#include "game_primitives.h"
#include "map_terrain_static_key.h"

class GeneralAssessor;
class KeyHolder;

//================================================================================================================================
//=> - MapTerrainBitArray class -
//================================================================================================================================

class MapTerrainBitArray {
public:
    explicit MapTerrainBitArray (u16 count);
    ~MapTerrainBitArray ();

    bool is_flagged (u16 index) const;
    void set_flag (MapTerrainStaticDataKey key);
    void clear_flag (MapTerrainStaticDataKey key);

    bool can_access (u16 idx, MapTerrainStaticDataKey& out_key) const;

private:
    MapTerrainBitArray (const MapTerrainBitArray& other) = delete;
    MapTerrainBitArray (MapTerrainBitArray&& other) = delete;

    BitArrayCL m_flags;
};

#endif // MAP_TERRAIN_BIT_ARRAY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
