//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef MVT_COST_BIT_ARRAY_H
#define MVT_COST_BIT_ARRAY_H

#include "bit_array.h"
#include "game_primitives.h"
#include "mvt_cost_static_key.h"

class GeneralAssessor;
class KeyHolder;

//================================================================================================================================
//=> - MvtCostBitArray class -
//================================================================================================================================

class MvtCostBitArray {
public:
    explicit MvtCostBitArray (u16 count);
    ~MvtCostBitArray ();

    bool is_flagged (u16 index) const;
    void set_flag (MvtCostStaticDataKey key);
    void clear_flag (MvtCostStaticDataKey key);

    bool can_access (u16 idx, MvtCostStaticDataKey& out_key) const;

private:
    MvtCostBitArray (const MvtCostBitArray& other) = delete;
    MvtCostBitArray (MvtCostBitArray&& other) = delete;

    BitArrayCL m_flags;
};

#endif // MVT_COST_BIT_ARRAY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
