//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef RES_TYPE_BIT_ARRAY_H
#define RES_TYPE_BIT_ARRAY_H

#include "bit_array.h"
#include "game_primitives.h"
#include "res_type_static_key.h"

class GeneralAssessor;
class KeyHolder;

//================================================================================================================================
//=> - ResTypeBitArray class -
//================================================================================================================================

class ResTypeBitArray {
public:
    explicit ResTypeBitArray (u16 count);
    ~ResTypeBitArray ();

    bool is_flagged (u16 index) const;
    void set_flag (ResTypeStaticDataKey key);
    void clear_flag (ResTypeStaticDataKey key);

    bool can_access (u16 idx, ResTypeStaticDataKey& out_key) const;

private:
    ResTypeBitArray (const ResTypeBitArray& other) = delete;
    ResTypeBitArray (ResTypeBitArray&& other) = delete;

    BitArrayCL m_flags;
};

#endif // RES_TYPE_BIT_ARRAY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
