//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef SMALL_WONDER_BIT_ARRAY_H
#define SMALL_WONDER_BIT_ARRAY_H

#include "bit_array.h"
#include "game_primitives.h"
#include "small_wonder_static_key.h"

class GeneralAssessor;
class KeyHolder;

//================================================================================================================================
//=> - SmallWonderBitArray class -
//================================================================================================================================

class SmallWonderBitArray {
public:
    explicit SmallWonderBitArray (u16 count);
    ~SmallWonderBitArray ();

    bool is_flagged (u16 index) const;
    void set_flag (SmallWonderStaticDataKey key);
    void clear_flag (SmallWonderStaticDataKey key);

    bool can_access (u16 idx, SmallWonderStaticDataKey& out_key) const;

private:
    SmallWonderBitArray (const SmallWonderBitArray& other) = delete;
    SmallWonderBitArray (SmallWonderBitArray&& other) = delete;

    BitArrayCL m_flags;
};

#endif // SMALL_WONDER_BIT_ARRAY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
