#!/bin/bash

INC="-I.. -I../misc -I../static_state -I../gen_static_state -I../static_variable_state"

g++ $INC -c ../misc/bit_array.cpp -o bit_array.o
g++ $INC -c small_wonder_bit_array.cpp -o small_wonder_bit_array.o
g++ $INC -c small_wonder_static_data.cpp -o small_wonder_static_data.o

g++ -o small_wonder_bit_array_tester \
    bit_array.o \
    small_wonder_bit_array.o \
    small_wonder_static_data.o

rm -f \
    bit_array.o \
    small_wonder_bit_array.o \
    small_wonder_static_data.o
