//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include "tech_era_bit_array.h"

//================================================================================================================================
//=> - TechEraBitArray implementation -
//================================================================================================================================

TechEraBitArray::TechEraBitArray (u16 count) :
    m_flags(count) {
}

TechEraBitArray::~TechEraBitArray () {
}

bool TechEraBitArray::is_flagged (TechEraStaticDataKey key) const {
    return m_flags.get_bit(key.value()) != 0;
}

void TechEraBitArray::set_flag (TechEraStaticDataKey key) {
    m_flags.set_bit(key.value());
}

void TechEraBitArray::clear_flag (TechEraStaticDataKey key) {
    m_flags.clear_bit(key.value());
}

bool TechEraBitArray::can_access (u16 idx, TechEraStaticDataKey& out_key) const {
    if (idx >= m_flags.get_count()) {
        return false;
    }
    if (m_flags.get_bit(idx) == 0) {
        return false;
    }
    out_key = TechEraStaticDataKey::from_raw(idx);
    return true;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
