//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef TECH_BIT_ARRAY_H
#define TECH_BIT_ARRAY_H

#include "bit_array.h"
#include "game_primitives.h"
#include "tech_static_key.h"

class GeneralAssessor;
class KeyHolder;

//================================================================================================================================
//=> - TechBitArray class -
//================================================================================================================================

class TechBitArray {
public:
    explicit TechBitArray (u16 count);
    ~TechBitArray ();

    bool is_flagged (u16 index) const;
    void set_flag (TechStaticDataKey key);
    void clear_flag (TechStaticDataKey key);

    bool can_access (u16 idx, TechStaticDataKey& out_key) const;

private:
    TechBitArray (const TechBitArray& other) = delete;
    TechBitArray (TechBitArray&& other) = delete;

    BitArrayCL m_flags;
};

#endif // TECH_BIT_ARRAY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
