#!/bin/bash

INC="-I.. -I../misc -I../static_state -I../gen_static_state -I../static_variable_state"

g++ $INC -c ../misc/bit_array.cpp -o bit_array.o
g++ $INC -c tech_bit_array.cpp -o tech_bit_array.o
g++ $INC -c tech_static_data.cpp -o tech_static_data.o

g++ -o tech_bit_array_tester \
    bit_array.o \
    tech_bit_array.o \
    tech_static_data.o

rm -f \
    bit_array.o \
    tech_bit_array.o \
    tech_static_data.o
