//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include "tile_attribute_bit_array.h"

//================================================================================================================================
//=> - TileAttributeBitArray implementation -
//================================================================================================================================

TileAttributeBitArray::TileAttributeBitArray (u16 count) :
    m_flags(count) {
}

TileAttributeBitArray::~TileAttributeBitArray () {
}

bool TileAttributeBitArray::is_flagged (TileAttributeStaticDataKey key) const {
    return m_flags.get_bit(key.value()) != 0;
}

void TileAttributeBitArray::set_flag (TileAttributeStaticDataKey key) {
    m_flags.set_bit(key.value());
}

void TileAttributeBitArray::clear_flag (TileAttributeStaticDataKey key) {
    m_flags.clear_bit(key.value());
}

bool TileAttributeBitArray::can_access (u16 idx, TileAttributeStaticDataKey& out_key) const {
    if (idx >= m_flags.get_count()) {
        return false;
    }
    if (m_flags.get_bit(idx) == 0) {
        return false;
    }
    out_key = TileAttributeStaticDataKey::from_raw(idx);
    return true;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
