//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include "toggle_civ_bit_array.h"

//================================================================================================================================
//=> - ToggleCivBitArray implementation -
//================================================================================================================================

ToggleCivBitArray::ToggleCivBitArray (u16 count) :
    m_flags(count) {
}

ToggleCivBitArray::~ToggleCivBitArray () {
}

bool ToggleCivBitArray::is_flagged (ToggleCivStaticDataKey key) const {
    return m_flags.get_bit(key.value()) != 0;
}

void ToggleCivBitArray::set_flag (ToggleCivStaticDataKey key) {
    m_flags.set_bit(key.value());
}

void ToggleCivBitArray::clear_flag (ToggleCivStaticDataKey key) {
    m_flags.clear_bit(key.value());
}

bool ToggleCivBitArray::can_access (u16 idx, ToggleCivStaticDataKey& out_key) const {
    if (idx >= m_flags.get_count()) {
        return false;
    }
    if (m_flags.get_bit(idx) == 0) {
        return false;
    }
    out_key = ToggleCivStaticDataKey::from_raw(idx);
    return true;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
