//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef TOGGLE_CITY_BIT_ARRAY_H
#define TOGGLE_CITY_BIT_ARRAY_H

#include "bit_array.h"
#include "game_primitives.h"
#include "toggle_city_static_key.h"

class GeneralAssessor;
class KeyHolder;

//================================================================================================================================
//=> - ToggleCityBitArray class -
//================================================================================================================================

class ToggleCityBitArray {
public:
    explicit ToggleCityBitArray (u16 count);
    ~ToggleCityBitArray ();

    bool is_flagged (u16 index) const;
    void set_flag (ToggleCityStaticDataKey key);
    void clear_flag (ToggleCityStaticDataKey key);

    bool can_access (u16 idx, ToggleCityStaticDataKey& out_key) const;

private:
    ToggleCityBitArray (const ToggleCityBitArray& other) = delete;
    ToggleCityBitArray (ToggleCityBitArray&& other) = delete;

    BitArrayCL m_flags;
};

#endif // TOGGLE_CITY_BIT_ARRAY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
