//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include "unit_domain_bit_array.h"

//================================================================================================================================
//=> - UnitDomainBitArray implementation -
//================================================================================================================================

UnitDomainBitArray::UnitDomainBitArray (u16 count) :
    m_flags(count) {
}

UnitDomainBitArray::~UnitDomainBitArray () {
}

bool UnitDomainBitArray::is_flagged (UnitDomainStaticDataKey key) const {
    return m_flags.get_bit(key.value()) != 0;
}

void UnitDomainBitArray::set_flag (UnitDomainStaticDataKey key) {
    m_flags.set_bit(key.value());
}

void UnitDomainBitArray::clear_flag (UnitDomainStaticDataKey key) {
    m_flags.clear_bit(key.value());
}

bool UnitDomainBitArray::can_access (u16 idx, UnitDomainStaticDataKey& out_key) const {
    if (idx >= m_flags.get_count()) {
        return false;
    }
    if (m_flags.get_bit(idx) == 0) {
        return false;
    }
    out_key = UnitDomainStaticDataKey::from_raw(idx);
    return true;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
