//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include "unit_role_bit_array.h"

//================================================================================================================================
//=> - UnitRoleBitArray implementation -
//================================================================================================================================

UnitRoleBitArray::UnitRoleBitArray (u16 count) :
    m_flags(count) {
}

UnitRoleBitArray::~UnitRoleBitArray () {
}

bool UnitRoleBitArray::is_flagged (UnitRoleStaticDataKey key) const {
    return m_flags.get_bit(key.value()) != 0;
}

void UnitRoleBitArray::set_flag (UnitRoleStaticDataKey key) {
    m_flags.set_bit(key.value());
}

void UnitRoleBitArray::clear_flag (UnitRoleStaticDataKey key) {
    m_flags.clear_bit(key.value());
}

bool UnitRoleBitArray::can_access (u16 idx, UnitRoleStaticDataKey& out_key) const {
    if (idx >= m_flags.get_count()) {
        return false;
    }
    if (m_flags.get_bit(idx) == 0) {
        return false;
    }
    out_key = UnitRoleStaticDataKey::from_raw(idx);
    return true;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
