//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef UNIT_BIT_ARRAY_H
#define UNIT_BIT_ARRAY_H

#include "bit_array.h"
#include "game_primitives.h"
#include "unit_static_key.h"

class GeneralAssessor;
class KeyHolder;

//================================================================================================================================
//=> - UnitBitArray class -
//================================================================================================================================

class UnitBitArray {
public:
    explicit UnitBitArray (u16 count);
    ~UnitBitArray ();

    bool is_flagged (u16 index) const;
    void set_flag (UnitStaticDataKey key);
    void clear_flag (UnitStaticDataKey key);

    bool can_access (u16 idx, UnitStaticDataKey& out_key) const;

private:
    UnitBitArray (const UnitBitArray& other) = delete;
    UnitBitArray (UnitBitArray&& other) = delete;

    BitArrayCL m_flags;
};

#endif // UNIT_BIT_ARRAY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
