//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef WORKER_JOB_IMP_BIT_ARRAY_H
#define WORKER_JOB_IMP_BIT_ARRAY_H

#include "bit_array.h"
#include "game_primitives.h"
#include "worker_job_imp_static_key.h"

class GeneralAssessor;
class KeyHolder;

//================================================================================================================================
//=> - WorkerJobImpBitArray class -
//================================================================================================================================

class WorkerJobImpBitArray {
public:
    explicit WorkerJobImpBitArray (u16 count);
    ~WorkerJobImpBitArray ();

    bool is_flagged (u16 index) const;
    void set_flag (WorkerJobImpStaticDataKey key);
    void clear_flag (WorkerJobImpStaticDataKey key);

    bool can_access (u16 idx, WorkerJobImpStaticDataKey& out_key) const;

private:
    WorkerJobImpBitArray (const WorkerJobImpBitArray& other) = delete;
    WorkerJobImpBitArray (WorkerJobImpBitArray&& other) = delete;

    BitArrayCL m_flags;
};

#endif // WORKER_JOB_IMP_BIT_ARRAY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
