//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef WORKER_JOB_TARGET_BIT_ARRAY_H
#define WORKER_JOB_TARGET_BIT_ARRAY_H

#include "bit_array.h"
#include "game_primitives.h"
#include "worker_job_target_static_key.h"

class GeneralAssessor;
class KeyHolder;

//================================================================================================================================
//=> - WorkerJobTargetBitArray class -
//================================================================================================================================

class WorkerJobTargetBitArray {
public:
    explicit WorkerJobTargetBitArray (u16 count);
    ~WorkerJobTargetBitArray ();

    bool is_flagged (u16 index) const;
    void set_flag (WorkerJobTargetStaticDataKey key);
    void clear_flag (WorkerJobTargetStaticDataKey key);

    bool can_access (u16 idx, WorkerJobTargetStaticDataKey& out_key) const;

private:
    WorkerJobTargetBitArray (const WorkerJobTargetBitArray& other) = delete;
    WorkerJobTargetBitArray (WorkerJobTargetBitArray&& other) = delete;

    BitArrayCL m_flags;
};

#endif // WORKER_JOB_TARGET_BIT_ARRAY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
