//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include "worker_job_bit_array.h"

//================================================================================================================================
//=> - WorkerJobBitArray implementation -
//================================================================================================================================

WorkerJobBitArray::WorkerJobBitArray (u16 count) :
    m_flags(count) {
}

WorkerJobBitArray::~WorkerJobBitArray () {
}

bool WorkerJobBitArray::is_flagged (WorkerJobStaticDataKey key) const {
    return m_flags.get_bit(key.value()) != 0;
}

void WorkerJobBitArray::set_flag (WorkerJobStaticDataKey key) {
    m_flags.set_bit(key.value());
}

void WorkerJobBitArray::clear_flag (WorkerJobStaticDataKey key) {
    m_flags.clear_bit(key.value());
}

bool WorkerJobBitArray::can_access (u16 idx, WorkerJobStaticDataKey& out_key) const {
    if (idx >= m_flags.get_count()) {
        return false;
    }
    if (m_flags.get_bit(idx) == 0) {
        return false;
    }
    out_key = WorkerJobStaticDataKey::from_raw(idx);
    return true;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
