//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes and globals -
//================================================================================================================================

#include "worker_job_imp_bit_array.h"

//================================================================================================================================
//=> - WorkerJobImpBitArray implementation -
//================================================================================================================================

WorkerJobImpBitArray::WorkerJobImpBitArray (u16 count) :
    m_flags(count) {
}

WorkerJobImpBitArray::~WorkerJobImpBitArray () {
}

bool WorkerJobImpBitArray::is_flagged (WorkerJobImpStaticDataKey key) const {
    return m_flags.get_bit(key.value()) != 0;
}

void WorkerJobImpBitArray::set_flag (WorkerJobImpStaticDataKey key) {
    m_flags.set_bit(key.value());
}

void WorkerJobImpBitArray::clear_flag (WorkerJobImpStaticDataKey key) {
    m_flags.clear_bit(key.value());
}

bool WorkerJobImpBitArray::can_access (u16 idx, WorkerJobImpStaticDataKey& out_key) const {
    if (idx >= m_flags.get_count()) {
        return false;
    }
    if (m_flags.get_bit(idx) == 0) {
        return false;
    }
    out_key = WorkerJobImpStaticDataKey::from_raw(idx);
    return true;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
