#!/bin/bash

INC="-I.. -I../.. -I../../game -I../../map_loader -I../../simple_map_gen -I../../misc -I../river_explore -I../distant_explore"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_loader.cpp -o map_loader.o
g++ $CXXFLAGS $INC -c ../../game/runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c ../../game/game_array_simple.cpp -o game_array_simple.o
g++ $CXXFLAGS $INC -c ../../game/factory_game_array_simple.cpp -o factory_game_array_simple.o
g++ $CXXFLAGS $INC -c near_explore_mk1.cpp -o near_explore_mk1.o
g++ $CXXFLAGS $INC -c near_explore_mk1_tester.cpp -o near_explore_mk1_tester.o
g++ $CXXFLAGS $INC -c near_explore_mk1_adv_tester.cpp -o near_explore_mk1_adv_tester.o
g++ $CXXFLAGS $INC -c near_explore_mk1_hybrid_tester.cpp -o near_explore_mk1_hybrid_tester.o
g++ $CXXFLAGS $INC -c ../../misc/map_bit_overlay.cpp -o map_bit_overlay.o
g++ $CXXFLAGS $INC -c ../short_range_pathing.cpp -o short_range_pathing.o
g++ $CXXFLAGS $INC -c ../river_explore/river_explore_mk2.cpp -o river_explore_mk2.o
g++ $CXXFLAGS $INC -c ../ai_whiteboard.cpp -o ai_whiteboard.o
g++ $CXXFLAGS $INC -c ../generate_distance_to_ocean_coast.cpp -o generate_distance_to_ocean_coast.o
g++ $CXXFLAGS $INC -c ../generate_distance_to_coastal_point.cpp -o generate_distance_to_coastal_point.o
g++ $CXXFLAGS $INC -c ../distant_explore/explore_distant_mk1.cpp -o explore_distant_mk1.o
g++ $CXXFLAGS $INC -c ../distant_explore/explore_distant_mk3.cpp -o explore_distant_mk3.o

g++ $CXXFLAGS -o near_explore_mk1_tester \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    runtime_trace_dbg.o \
    game_array_simple.o \
    factory_game_array_simple.o \
    near_explore_mk1.o \
    near_explore_mk1_tester.o

g++ $CXXFLAGS -o near_explore_mk1_adv_tester \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    runtime_trace_dbg.o \
    game_array_simple.o \
    factory_game_array_simple.o \
    near_explore_mk1.o \
    near_explore_mk1_adv_tester.o

g++ $CXXFLAGS -o near_explore_mk1_hybrid_tester \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    runtime_trace_dbg.o \
    game_array_simple.o \
    factory_game_array_simple.o \
    map_bit_overlay.o \
    ai_whiteboard.o \
    generate_distance_to_ocean_coast.o \
    generate_distance_to_coastal_point.o \
    short_range_pathing.o \
    explore_distant_mk1.o \
    explore_distant_mk3.o \
    river_explore_mk2.o \
    near_explore_mk1.o \
    near_explore_mk1_hybrid_tester.o

rm map_terrain_validate.o map_terrain_data.o map_loader.o runtime_trace_dbg.o \
    game_array_simple.o factory_game_array_simple.o map_bit_overlay.o \
    ai_whiteboard.o generate_distance_to_ocean_coast.o generate_distance_to_coastal_point.o \
    short_range_pathing.o explore_distant_mk1.o explore_distant_mk3.o river_explore_mk2.o \
    near_explore_mk1.o near_explore_mk1_tester.o near_explore_mk1_adv_tester.o \
    near_explore_mk1_hybrid_tester.o
