//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef [PROF_GUARD_TAG]
#define [PROF_GUARD_TAG]

#include "game_primitives.h"
#include "log_dbg_toggles.h"

//================================================================================================================================
//=> - [PROF_CLASS_TAG] -
//================================================================================================================================

#if defined(LOG_DBG_SO_BUILD) || defined(LOG_DBG_FORCE_ALL) || (defined(LOG_DBG_ENABLE) && defined([PROF_ENABLE_TAG]))

class [PROF_CLASS_TAG] {
public:
    static void SETUP (cstr dir);

    class Guard {
    public:
        explicit Guard (cstr func);
        ~Guard ();

    private:
        Guard (const Guard&) = delete;
        Guard& operator= (const Guard&) = delete;

        cstr m_fn; // Entered function name; must match stack top on destroy
    };
};

#define [PROF_SETUP_MACRO_TAG](dir) ::[PROF_CLASS_TAG]::SETUP(dir)
#define [PROF_ENTER_MACRO_TAG](fn) ::[PROF_CLASS_TAG]::Guard _prof_guard_##__LINE__(fn)

#else

#define [PROF_SETUP_MACRO_TAG](dir) ((void)(dir))
#define [PROF_ENTER_MACRO_TAG](fn) ((void)(fn))

#endif

#endif // [PROF_GUARD_TAG]

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
