#!/bin/bash

# Define the include path for the compiler
INC="-I.. -I../misc"

# Compile objects
g++ $INC -c ../misc/bit_array.cpp -o bit_array.o
g++ $INC -c buildings_built_array.cpp -o buildings_built_array.o
g++ $INC -c buildings_built_array_tester.cpp -o buildings_built_array_tester.o

# Link everything into the final tester
g++ -o buildings_built_array_tester bit_array.o buildings_built_array.o buildings_built_array_tester.o

# Clean up
rm bit_array.o buildings_built_array.o buildings_built_array_tester.o