#!/bin/bash

# Define the include path for the compiler
INC="-I.. -I../misc"

# Compile objects
g++ $INC -c ../misc/bit_array.cpp -o bit_array.o
g++ $INC -c resources_available_array.cpp -o resources_available_array.o
g++ $INC -c resources_available_array_tester.cpp -o resources_available_array_tester.o

# Link everything into the final tester
g++ -o resources_available_array_tester bit_array.o resources_available_array.o resources_available_array_tester.o

# Clean up
rm bit_array.o resources_available_array.o resources_available_array_tester.o