#!/bin/bash

INC="-I.. -I../static_state"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c building_static_data.cpp -o building_static_data.o
g++ $CXXFLAGS $INC -c building_static_data_tester.cpp -o building_static_data_tester.o

g++ $CXXFLAGS -o building_static_data_tester building_static_data.o building_static_data_tester.o

rm building_static_data.o building_static_data_tester.o
