#!/bin/bash

# Define the include path for the compiler
INC="-I.."

# Compile objects
g++ $INC -c city_flag_static_data.cpp -o city_flag_static_data.o
g++ $INC -c city_flag_static_data_tester.cpp -o city_flag_static_data_tester.o

# Link everything into the final tester
g++ -o city_flag_static_data_tester city_flag_static_data.o city_flag_static_data_tester.o

# Clean up
rm city_flag_static_data.o city_flag_static_data_tester.o