#!/bin/bash

INC="-I.. -I../static_state"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c city_flag_static_data.cpp -o city_flag_static_data.o
g++ $CXXFLAGS $INC -c city_flag_static_data_tester.cpp -o city_flag_static_data_tester.o

g++ $CXXFLAGS -o city_flag_static_data_tester city_flag_static_data.o city_flag_static_data_tester.o

rm city_flag_static_data.o city_flag_static_data_tester.o
