#!/bin/bash

INC="-I.. -I../static_state"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c civ_static_data.cpp -o civ_static_data.o
g++ $CXXFLAGS $INC -c civ_static_data_tester.cpp -o civ_static_data_tester.o

g++ $CXXFLAGS -o civ_static_data_tester civ_static_data.o civ_static_data_tester.o

rm civ_static_data.o civ_static_data_tester.o
