//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include "civ_static_data.h"

//================================================================================================================================
//=> - CivStaticData implementation -
//================================================================================================================================

void CivStaticData::set_items (CivStaticDataStruct* items, u16 item_count) {
    m_item_array = items;
    m_item_count = item_count;
}

void CivStaticData::take_ownership () {
    CivStaticDataStruct* tmp_array = m_item_array;
    m_item_array = new CivStaticDataStruct[m_item_count];
    for (u16 i = 0; i < m_item_count; ++i) {
        m_item_array[i] = tmp_array[i];
    }
    delete[] tmp_array;
}

void CivStaticData::release_items () {
    delete[] m_item_array;
    m_item_array = nullptr;
    m_item_count = 0;
}

const CivStaticDataStruct& CivStaticData::get_item (CivStaticDataKey key) const {
    u16 idx = key.value();
    return m_item_array[idx];
}

u16 CivStaticData::get_item_count () const {
    return m_item_count;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
