//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_config_settings.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef CONFIG_SETTINGS_STATIC_H
#define CONFIG_SETTINGS_STATIC_H

#include "unit_static_key.h"
#include "game_primitives.h"

//================================================================================================================================
//=> - Limits -
//================================================================================================================================

#define MAX_CONFIG_LIST_ITEMS 8

//================================================================================================================================
//=> - ConfigListUnit -
//================================================================================================================================

struct ConfigListUnit {
    UnitStaticDataKey keys[MAX_CONFIG_LIST_ITEMS];
    u16 n;
};

//================================================================================================================================
//=> - ConfigSettingsData -
//================================================================================================================================

struct ConfigSettingsData {
    u16 m_mov_pt_per_turn;
    ConfigListUnit m_start_units;
    ConfigListUnit m_start_exp_units;
    u16 m_unit_heal_in_city;
    u16 m_unit_heal_default;
    u16 m_upgrade_cost_per_prod;
    u16 m_upgrade_cost_per_stat_pt;
    u16 m_tech_age_unlock_pct;
    u16 m_default_culture_per_turn;
};

//================================================================================================================================
//=> - GameConfigSettings -
//================================================================================================================================

class GameConfigSettings {
public:
    GameConfigSettings ();
    ~GameConfigSettings ();

    void reset ();
    bool is_default () const;

    u16 get_mov_pt_per_turn () const;
    void set_mov_pt_per_turn (u16 v);

    ConfigListUnit get_start_units () const;
    void set_start_units (ConfigListUnit v);

    ConfigListUnit get_start_exp_units () const;
    void set_start_exp_units (ConfigListUnit v);

    u16 get_unit_heal_in_city () const;
    void set_unit_heal_in_city (u16 v);

    u16 get_unit_heal_default () const;
    void set_unit_heal_default (u16 v);

    u16 get_upgrade_cost_per_prod () const;
    void set_upgrade_cost_per_prod (u16 v);

    u16 get_upgrade_cost_per_stat_pt () const;
    void set_upgrade_cost_per_stat_pt (u16 v);

    u16 get_tech_age_unlock_pct () const;
    void set_tech_age_unlock_pct (u16 v);

    u16 get_default_culture_per_turn () const;
    void set_default_culture_per_turn (u16 v);

private:
    GameConfigSettings (const GameConfigSettings& o) = delete;
    GameConfigSettings& operator= (const GameConfigSettings& o) = delete;

    void ensure_ovr ();
    const ConfigSettingsData& cur () const;

    bool m_is_default;
    ConfigSettingsData m_defaults;
    ConfigSettingsData* m_cfg;
};

#endif // CONFIG_SETTINGS_STATIC_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
