//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_config_settings.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include <cstdio>
#include <cstdlib>

#include "config_settings_parse.h"
#include "static_parsing_manager.h"

//================================================================================================================================
//=> - Globals -
//================================================================================================================================

typedef const char* cstr;

static const StaticParsingManager* g_st = nullptr;

static const char* G_PATH_OFFSET = "../";
static const char* G_CFG_PATH = "../game_config.settings";

//================================================================================================================================
//=> - NameToIdxCbs glue -
//================================================================================================================================

static u16 st_building_n2i (cstr name) {
    return g_st->get_building_name_parser().name_to_idx(name);
}

static u16 st_city_flag_n2i (cstr name) {
    return g_st->get_city_flag_name_parser().name_to_idx(name);
}

static u16 st_civ_n2i (cstr name) {
    return g_st->get_civ_name_parser().name_to_idx(name);
}

static u16 st_civ_trait_n2i (cstr name) {
    return g_st->get_civ_trait_name_parser().name_to_idx(name);
}

static u16 st_mvt_cost_n2i (cstr name) {
    return g_st->get_mvt_cost_name_parser().name_to_idx(name);
}

static u16 st_resource_n2i (cstr name) {
    return g_st->get_resource_name_parser().name_to_idx(name);
}

static u16 st_res_dist_n2i (cstr name) {
    return g_st->get_res_dist_name_parser().name_to_idx(name);
}

static u16 st_small_wonder_n2i (cstr name) {
    return g_st->get_small_wonder_name_parser().name_to_idx(name);
}

static u16 st_tech_n2i (cstr name) {
    return g_st->get_tech_name_parser().name_to_idx(name);
}

static u16 st_unit_n2i (cstr name) {
    return g_st->get_unit_name_parser().name_to_idx(name);
}

static u16 st_unit_action_n2i (cstr name) {
    return g_st->get_unit_action_name_parser().name_to_idx(name);
}

static u16 st_unit_type_n2i (cstr name) {
    return g_st->get_unit_type_name_parser().name_to_idx(name);
}

static u16 st_wonder_n2i (cstr name) {
    return g_st->get_wonder_name_parser().name_to_idx(name);
}

static void fill_cbs (NameToIdxCbs* cbs) {
    cbs->building_name_to_idx = st_building_n2i;
    cbs->city_flag_name_to_idx = st_city_flag_n2i;
    cbs->civ_name_to_idx = st_civ_n2i;
    cbs->civ_trait_name_to_idx = st_civ_trait_n2i;
    cbs->mvt_cost_name_to_idx = st_mvt_cost_n2i;
    cbs->resource_name_to_idx = st_resource_n2i;
    cbs->res_dist_name_to_idx = st_res_dist_n2i;
    cbs->small_wonder_name_to_idx = st_small_wonder_n2i;
    cbs->tech_name_to_idx = st_tech_n2i;
    cbs->unit_name_to_idx = st_unit_n2i;
    cbs->unit_action_name_to_idx = st_unit_action_n2i;
    cbs->unit_type_name_to_idx = st_unit_type_n2i;
    cbs->wonder_name_to_idx = st_wonder_n2i;
}

static cstr unit_idx_to_name (u16 idx) {
    return g_st->get_unit_name_parser().idx_to_name(idx);
}

//================================================================================================================================
//=> - Print -
//================================================================================================================================

static void print_config (const GameConfigSettings& cfg) {
    std::printf("GameConfigSettings is_default=%d\n", cfg.is_default() ? 1 : 0);
    std::printf("  PATH_MP_TURN: %u\n", cfg.get_mov_pt_per_turn());
    {
        ConfigListUnit lst = cfg.get_start_units();
        std::printf("  START_UNITS:");
        for (u16 i = 0; i < lst.n; ++i) {
            std::printf(" %s", unit_idx_to_name(lst.keys[i].value()));
        }
        std::printf("\n");
    }
    {
        ConfigListUnit lst = cfg.get_start_exp_units();
        std::printf("  START_EXP_UNITS:");
        for (u16 i = 0; i < lst.n; ++i) {
            std::printf(" %s", unit_idx_to_name(lst.keys[i].value()));
        }
        std::printf("\n");
    }
}

//================================================================================================================================
//=> - Main -
//================================================================================================================================

int main (int argc, char* argv[]) {
    cstr path_offset = G_PATH_OFFSET;
    cstr cfg_path = G_CFG_PATH;
    if (argc > 1) {
        cfg_path = argv[1];
    }
    if (argc > 2) {
        path_offset = argv[2];
    }
    StaticParsingManager st(path_offset);
    g_st = &st;
    NameToIdxCbs cbs = {};
    fill_cbs(&cbs);
    GameConfigSettingsParser psr(cbs);
    GameConfigSettings cfg;
    if (!psr.load_file(cfg_path, &cfg)) {
        return 1;
    }
    print_config(cfg);
    return 0;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
