//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef IMPROVEMENT_YIELD_STATIC_KEY_H
#define IMPROVEMENT_YIELD_STATIC_KEY_H

#include "game_primitives.h"

//================================================================================================================================
//=> - ImprovementYieldStaticDataKey class -
//================================================================================================================================

class ImprovementYieldStaticDataKey {
    friend class ImprovementYieldStaticData;
    friend class ImprovementYieldBitArray;
    friend class GeneralAssessor;
    friend class KeyHolder;
public:
    constexpr ImprovementYieldStaticDataKey() : m_val(U16_KEY_NULL) {}

    constexpr bool operator==(ImprovementYieldStaticDataKey other) const {
        return m_val == other.m_val; 
    }

    constexpr bool operator!=(ImprovementYieldStaticDataKey other) const { 
        return m_val != other.m_val; 
    }

    constexpr bool is_null() const { 
        return m_val == U16_KEY_NULL; 
    }

    constexpr bool is_valid() const { 
        return m_val != U16_KEY_NULL; 
    }

    static constexpr ImprovementYieldStaticDataKey None() { 
        return ImprovementYieldStaticDataKey(U16_KEY_NULL); 
    }

    static constexpr ImprovementYieldStaticDataKey from_raw(u16 val) {
        return ImprovementYieldStaticDataKey(val);
    }

    constexpr u16 value() const {
        return m_val;
    }

private:
    u16 m_val;

    explicit constexpr ImprovementYieldStaticDataKey(u16 val) : 
        m_val(val) {
    }    
};

#endif // IMPROVEMENT_YIELD_STATIC_KEY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
