//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef IMPROVEMENT_YIELD_STATIC_DATA_H
#define IMPROVEMENT_YIELD_STATIC_DATA_H

#include "improvement_yield_static_key.h"
#include "item_reqs.h"
#include "item_effects.h"
#include "res_placement.h"
#include "combat_mod.h"
#include "game_primitives.h"
#include "static_string_pool.h"

class DataParserBase;

//================================================================================================================================
//=> - ImprovementYieldStaticDataStruct -
//================================================================================================================================

typedef struct ImprovementYieldStaticDataStruct {
    u16 site_idx;
    u16 site_kind;
    u16 yield_type;
    i16 amount;
    u16 cond_attr;
} ImprovementYieldStaticDataStruct;

//================================================================================================================================
//=> - ImprovementYieldStaticData class -
//================================================================================================================================

class ImprovementYieldStaticData {
public:
    ImprovementYieldStaticData () = default;
    ~ImprovementYieldStaticData ();
    void set_items (ImprovementYieldStaticDataStruct* items, u16 item_count);
    bool load_names (cstr const* names, u16 n);
    bool load_names_from (const DataParserBase& psr, u16 n);
    void take_ownership ();
    void release_items ();
    const ImprovementYieldStaticDataStruct& get_item (ImprovementYieldStaticDataKey key) const;
    cstr get_name (ImprovementYieldStaticDataKey key) const;
    u16 get_item_count () const;

private:
    ImprovementYieldStaticData (const ImprovementYieldStaticData& other) = delete;
    ImprovementYieldStaticData (ImprovementYieldStaticData&& other) = delete;

    ImprovementYieldStaticDataStruct* m_item_array = nullptr;
    u16 m_item_count = 0;
    bool m_owns_array = false;
    StaticStringPool m_name_pool;
};

#endif // IMPROVEMENT_YIELD_STATIC_DATA_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
