//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef MAP_ATTRIBUTE_STATIC_DATA_H
#define MAP_ATTRIBUTE_STATIC_DATA_H

#include "map_attribute_static_key.h"
#include "item_reqs.h"
#include "item_effects.h"
#include "res_placement.h"
#include "combat_mod.h"
#include "game_primitives.h"
#include "static_string_pool.h"

class DataParserBase;

//================================================================================================================================
//=> - MapAttributeStaticDataStruct -
//================================================================================================================================

typedef struct MapAttributeStaticDataStruct {

} MapAttributeStaticDataStruct;

//================================================================================================================================
//=> - MapAttributeStaticData class -
//================================================================================================================================

class MapAttributeStaticData {
public:
    MapAttributeStaticData () = default;
    ~MapAttributeStaticData ();
    void set_items (MapAttributeStaticDataStruct* items, u16 item_count);
    bool load_names (cstr const* names, u16 n);
    bool load_names_from (const DataParserBase& psr, u16 n);
    void take_ownership ();
    void release_items ();
    const MapAttributeStaticDataStruct& get_item (MapAttributeStaticDataKey key) const;
    cstr get_name (MapAttributeStaticDataKey key) const;
    u16 get_item_count () const;

private:
    MapAttributeStaticData (const MapAttributeStaticData& other) = delete;
    MapAttributeStaticData (MapAttributeStaticData&& other) = delete;

    MapAttributeStaticDataStruct* m_item_array = nullptr;
    u16 m_item_count = 0;
    bool m_owns_array = false;
    StaticStringPool m_name_pool;
};

#endif // MAP_ATTRIBUTE_STATIC_DATA_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
