//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef MVT_COST_STATIC_DATA_H
#define MVT_COST_STATIC_DATA_H

#include "mvt_cost_static_key.h"
#include "item_reqs.h"
#include "item_effects.h"
#include "res_placement.h"
#include "game_primitives.h"
#include "static_string_pool.h"

class DataParserBase;

//================================================================================================================================
//=> - MvtCostStaticDataStruct -
//================================================================================================================================

typedef struct MvtCostStaticDataStruct {
    u16 cost;
} MvtCostStaticDataStruct;

//================================================================================================================================
//=> - MvtCostStaticData class -
//================================================================================================================================

class MvtCostStaticData {
public:
    MvtCostStaticData () = default;
    ~MvtCostStaticData ();
    void set_items (MvtCostStaticDataStruct* items, u16 item_count);
    bool load_names (cstr const* names, u16 n);
    bool load_names_from (const DataParserBase& psr, u16 n);
    void take_ownership ();
    void release_items ();
    const MvtCostStaticDataStruct& get_item (MvtCostStaticDataKey key) const;
    cstr get_name (MvtCostStaticDataKey key) const;
    u16 get_item_count () const;

private:
    MvtCostStaticData (const MvtCostStaticData& other) = delete;
    MvtCostStaticData (MvtCostStaticData&& other) = delete;

    MvtCostStaticDataStruct* m_item_array = nullptr;
    u16 m_item_count = 0;
    bool m_owns_array = false;
    StaticStringPool m_name_pool;
};

#endif // MVT_COST_STATIC_DATA_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
