//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef RES_DIST_STATIC_KEY_H
#define RES_DIST_STATIC_KEY_H

#include "game_primitives.h"

//================================================================================================================================
//=> - ResDistStaticDataKey class -
//================================================================================================================================

class ResDistStaticDataKey {
    friend class ResDistStaticData;
    friend class ResDistBitArray;
    friend class GeneralAssessor;
    friend class KeyHolder;
public:
    constexpr ResDistStaticDataKey() : m_val(U16_KEY_NULL) {}

    constexpr bool operator==(ResDistStaticDataKey other) const {
        return m_val == other.m_val; 
    }

    constexpr bool operator!=(ResDistStaticDataKey other) const { 
        return m_val != other.m_val; 
    }

    constexpr bool is_null() const { 
        return m_val == U16_KEY_NULL; 
    }

    constexpr bool is_valid() const { 
        return m_val != U16_KEY_NULL; 
    }

    static constexpr ResDistStaticDataKey None() { 
        return ResDistStaticDataKey(U16_KEY_NULL); 
    }

    static constexpr ResDistStaticDataKey from_raw(u16 val) {
        return ResDistStaticDataKey(val);
    }

    constexpr u16 value() const {
        return m_val;
    }

private:
    u16 m_val;

    explicit constexpr ResDistStaticDataKey(u16 val) : 
        m_val(val) {
    }    
};

#endif // RES_DIST_STATIC_KEY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
