#!/bin/bash

INC="-I.. -I../static_state"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c resource_static_data.cpp -o resource_static_data.o
g++ $CXXFLAGS $INC -c resource_static_data_tester.cpp -o resource_static_data_tester.o

g++ $CXXFLAGS -o resource_static_data_tester resource_static_data.o resource_static_data_tester.o

rm resource_static_data.o resource_static_data_tester.o
