#!/bin/bash

INC="-I.. -I../static_state"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c small_wonder_static_data.cpp -o small_wonder_static_data.o
g++ $CXXFLAGS $INC -c small_wonder_static_data_tester.cpp -o small_wonder_static_data_tester.o

g++ $CXXFLAGS -o small_wonder_static_data_tester small_wonder_static_data.o small_wonder_static_data_tester.o

rm small_wonder_static_data.o small_wonder_static_data_tester.o
