//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include "small_wonder_static_data.h"

//================================================================================================================================
//=> - SmallWonderStaticData implementation -
//================================================================================================================================

void SmallWonderStaticData::set_items (SmallWonderStaticDataStruct* items, u16 item_count) {
    m_item_array = items;
    m_item_count = item_count;
}

void SmallWonderStaticData::take_ownership () {
    SmallWonderStaticDataStruct* tmp_array = m_item_array;
    m_item_array = new SmallWonderStaticDataStruct[m_item_count];
    for (u16 i = 0; i < m_item_count; ++i) {
        m_item_array[i] = tmp_array[i];
    }
    delete[] tmp_array;
}

void SmallWonderStaticData::release_items () {
    delete[] m_item_array;
    m_item_array = nullptr;
    m_item_count = 0;
}

const SmallWonderStaticDataStruct& SmallWonderStaticData::get_item (SmallWonderStaticDataKey key) const {
    u16 idx = key.value();
    return m_item_array[idx];
}

u16 SmallWonderStaticData::get_item_count () const {
    return m_item_count;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
