//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef SMALL_WONDER_STATIC_DATA_H
#define SMALL_WONDER_STATIC_DATA_H

#include "small_wonder_static_key.h"
#include "item_reqs.h"
#include "item_effects.h"
#include "res_placement.h"
#include "game_primitives.h"
#include "static_string_pool.h"

class DataParserBase;

//================================================================================================================================
//=> - SmallWonderStaticDataStruct -
//================================================================================================================================

typedef struct SmallWonderStaticDataStruct {
    ItemReqsStruct reqs;
    u32 cost;
    ItemEffectsStruct effects;
} SmallWonderStaticDataStruct;

//================================================================================================================================
//=> - SmallWonderStaticData class -
//================================================================================================================================

class SmallWonderStaticData {
public:
    SmallWonderStaticData () = default;
    ~SmallWonderStaticData ();
    void set_items (SmallWonderStaticDataStruct* items, u16 item_count);
    bool load_names (cstr const* names, u16 n);
    bool load_names_from (const DataParserBase& psr, u16 n);
    void take_ownership ();
    void release_items ();
    const SmallWonderStaticDataStruct& get_item (SmallWonderStaticDataKey key) const;
    cstr get_name (SmallWonderStaticDataKey key) const;
    u16 get_item_count () const;

private:
    SmallWonderStaticData (const SmallWonderStaticData& other) = delete;
    SmallWonderStaticData (SmallWonderStaticData&& other) = delete;

    SmallWonderStaticDataStruct* m_item_array = nullptr;
    u16 m_item_count = 0;
    bool m_owns_array = false;
    StaticStringPool m_name_pool;
};

#endif // SMALL_WONDER_STATIC_DATA_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
