//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef TECH_STATIC_DATA_H
#define TECH_STATIC_DATA_H

#include <string>

#include "tech_static_key.h"
#include "item_reqs.h"
#include "item_effects.h"
#include "game_primitives.h"

//================================================================================================================================
//=> - TechStaticDataStruct -
//================================================================================================================================

typedef struct TechStaticDataStruct {
    std::string name;
    ItemReqsStruct reqs;
    ItemEffectsStruct effects;
    u32 cost;
    u16 tier;
} TechStaticDataStruct;

//================================================================================================================================
//=> - TechStaticData class -
//================================================================================================================================

class TechStaticData {
public:
    TechStaticData () = default;
    void set_items (TechStaticDataStruct* items, u16 item_count);
    void take_ownership ();
    void release_items ();
    const TechStaticDataStruct& get_item (TechStaticDataKey key) const;
    u16 get_item_count () const;

private:
    TechStaticData (const TechStaticData& other) = delete;
    TechStaticData (TechStaticData&& other) = delete;

    TechStaticDataStruct* m_item_array = nullptr;
    u16 m_item_count = 0;
};

#endif // TECH_STATIC_DATA_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
