//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef TECH_AGE_STATIC_DATA_H
#define TECH_AGE_STATIC_DATA_H

#include "tech_age_static_key.h"
#include "item_reqs.h"
#include "item_effects.h"
#include "res_placement.h"
#include "combat_mod.h"
#include "game_primitives.h"
#include "static_string_pool.h"

class DataParserBase;

//================================================================================================================================
//=> - TechAgeStaticDataStruct -
//================================================================================================================================

typedef struct TechAgeStaticDataStruct {
    u16 era;
} TechAgeStaticDataStruct;

//================================================================================================================================
//=> - TechAgeStaticData class -
//================================================================================================================================

class TechAgeStaticData {
public:
    TechAgeStaticData () = default;
    ~TechAgeStaticData ();
    void set_items (TechAgeStaticDataStruct* items, u16 item_count);
    bool load_names (cstr const* names, u16 n);
    bool load_names_from (const DataParserBase& psr, u16 n);
    void take_ownership ();
    void release_items ();
    const TechAgeStaticDataStruct& get_item (TechAgeStaticDataKey key) const;
    cstr get_name (TechAgeStaticDataKey key) const;
    u16 get_item_count () const;

private:
    TechAgeStaticData (const TechAgeStaticData& other) = delete;
    TechAgeStaticData (TechAgeStaticData&& other) = delete;

    TechAgeStaticDataStruct* m_item_array = nullptr;
    u16 m_item_count = 0;
    bool m_owns_array = false;
    StaticStringPool m_name_pool;
};

#endif // TECH_AGE_STATIC_DATA_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
