#!/bin/bash

# Define the include path for the compiler
INC="-I.."

# Compile objects
g++ $INC -c tech_static_data.cpp -o tech_static_data.o
g++ $INC -c tech_static_data_tester.cpp -o tech_static_data_tester.o

# Link everything into the final tester
g++ -o tech_static_data_tester tech_static_data.o tech_static_data_tester.o

# Clean up
rm tech_static_data.o tech_static_data_tester.o