#!/bin/bash

INC="-I.. -I../static_state"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c tech_static_data.cpp -o tech_static_data.o
g++ $CXXFLAGS $INC -c tech_static_data_tester.cpp -o tech_static_data_tester.o

g++ $CXXFLAGS -o tech_static_data_tester tech_static_data.o tech_static_data_tester.o

rm tech_static_data.o tech_static_data_tester.o
