//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef TOGGLE_GLOBAL_STATIC_KEY_H
#define TOGGLE_GLOBAL_STATIC_KEY_H

#include "game_primitives.h"

//================================================================================================================================
//=> - ToggleGlobalStaticDataKey class -
//================================================================================================================================

class ToggleGlobalStaticDataKey {
    friend class ToggleGlobalStaticData;
    friend class ToggleGlobalBitArray;
    friend class GeneralAssessor;
    friend class KeyHolder;
public:
    constexpr ToggleGlobalStaticDataKey() : m_val(U16_KEY_NULL) {}

    constexpr bool operator==(ToggleGlobalStaticDataKey other) const {
        return m_val == other.m_val; 
    }

    constexpr bool operator!=(ToggleGlobalStaticDataKey other) const { 
        return m_val != other.m_val; 
    }

    constexpr bool is_null() const { 
        return m_val == U16_KEY_NULL; 
    }

    constexpr bool is_valid() const { 
        return m_val != U16_KEY_NULL; 
    }

    static constexpr ToggleGlobalStaticDataKey None() { 
        return ToggleGlobalStaticDataKey(U16_KEY_NULL); 
    }

    static constexpr ToggleGlobalStaticDataKey from_raw(u16 val) {
        return ToggleGlobalStaticDataKey(val);
    }

    constexpr u16 value() const {
        return m_val;
    }

private:
    u16 m_val;

    explicit constexpr ToggleGlobalStaticDataKey(u16 val) : 
        m_val(val) {
    }    
};

#endif // TOGGLE_GLOBAL_STATIC_KEY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
