//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef TOGGLE_CITY_STATIC_DATA_H
#define TOGGLE_CITY_STATIC_DATA_H

#include "toggle_city_static_key.h"
#include "item_reqs.h"
#include "item_effects.h"
#include "res_placement.h"
#include "combat_mod.h"
#include "game_primitives.h"
#include "static_string_pool.h"

class DataParserBase;

//================================================================================================================================
//=> - ToggleCityStaticDataStruct -
//================================================================================================================================

typedef struct ToggleCityStaticDataStruct {
    ItemReqsStruct reqs;
    ItemEffectsStruct effects;
} ToggleCityStaticDataStruct;

//================================================================================================================================
//=> - ToggleCityStaticData class -
//================================================================================================================================

class ToggleCityStaticData {
public:
    ToggleCityStaticData () = default;
    ~ToggleCityStaticData ();
    void set_items (ToggleCityStaticDataStruct* items, u16 item_count);
    bool load_names (cstr const* names, u16 n);
    bool load_names_from (const DataParserBase& psr, u16 n);
    void take_ownership ();
    void release_items ();
    const ToggleCityStaticDataStruct& get_item (ToggleCityStaticDataKey key) const;
    cstr get_name (ToggleCityStaticDataKey key) const;
    u16 get_item_count () const;

private:
    ToggleCityStaticData (const ToggleCityStaticData& other) = delete;
    ToggleCityStaticData (ToggleCityStaticData&& other) = delete;

    ToggleCityStaticDataStruct* m_item_array = nullptr;
    u16 m_item_count = 0;
    bool m_owns_array = false;
    StaticStringPool m_name_pool;
};

#endif // TOGGLE_CITY_STATIC_DATA_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
