//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef UNIT_STATIC_DATA_H
#define UNIT_STATIC_DATA_H

#include <string>

#include "unit_static_key.h"
#include "item_reqs.h"
#include "item_effects.h"
#include "game_primitives.h"

//================================================================================================================================
//=> - UnitStaticDataStruct -
//================================================================================================================================

typedef struct UnitStaticDataStruct {
    std::string name;
    ItemReqsStruct reqs;
    u32 cost;
    u16 type;
    u16 attack;
    u16 defense;
    u16 mvt_pts;
} UnitStaticDataStruct;

//================================================================================================================================
//=> - UnitStaticData class -
//================================================================================================================================

class UnitStaticData {
public:
    UnitStaticData () = default;
    void set_items (UnitStaticDataStruct* items, u16 item_count);
    void take_ownership ();
    void release_items ();
    const UnitStaticDataStruct& get_item (UnitStaticDataKey key) const;
    u16 get_item_count () const;

private:
    UnitStaticData (const UnitStaticData& other) = delete;
    UnitStaticData (UnitStaticData&& other) = delete;

    UnitStaticDataStruct* m_item_array = nullptr;
    u16 m_item_count = 0;
};

#endif // UNIT_STATIC_DATA_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
