#!/bin/bash

INC="-I.. -I../static_state"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c unit_static_data.cpp -o unit_static_data.o
g++ $CXXFLAGS $INC -c unit_static_data_tester.cpp -o unit_static_data_tester.o

g++ $CXXFLAGS -o unit_static_data_tester unit_static_data.o unit_static_data_tester.o

rm unit_static_data.o unit_static_data_tester.o
