#!/bin/bash

# Define the include path for the compiler
INC="-I.."

# Compile objects
g++ $INC -c unit_static_data.cpp -o unit_static_data.o
g++ $INC -c unit_static_data_tester.cpp -o unit_static_data_tester.o

# Link everything into the final tester
g++ -o unit_static_data_tester unit_static_data.o unit_static_data_tester.o

# Clean up
rm unit_static_data.o unit_static_data_tester.o