//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef UNIT_ROLE_STATIC_KEY_H
#define UNIT_ROLE_STATIC_KEY_H

#include "game_primitives.h"

//================================================================================================================================
//=> - UnitRoleStaticDataKey class -
//================================================================================================================================

class UnitRoleStaticDataKey {
    friend class UnitRoleStaticData;
    friend class UnitRoleBitArray;
    friend class GeneralAssessor;
    friend class KeyHolder;
public:
    constexpr UnitRoleStaticDataKey() : m_val(U16_KEY_NULL) {}

    constexpr bool operator==(UnitRoleStaticDataKey other) const {
        return m_val == other.m_val; 
    }

    constexpr bool operator!=(UnitRoleStaticDataKey other) const { 
        return m_val != other.m_val; 
    }

    constexpr bool is_null() const { 
        return m_val == U16_KEY_NULL; 
    }

    constexpr bool is_valid() const { 
        return m_val != U16_KEY_NULL; 
    }

    static constexpr UnitRoleStaticDataKey None() { 
        return UnitRoleStaticDataKey(U16_KEY_NULL); 
    }

    static constexpr UnitRoleStaticDataKey from_raw(u16 val) {
        return UnitRoleStaticDataKey(val);
    }

    constexpr u16 value() const {
        return m_val;
    }

private:
    u16 m_val;

    explicit constexpr UnitRoleStaticDataKey(u16 val) : 
        m_val(val) {
    }    
};

#endif // UNIT_ROLE_STATIC_KEY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
