//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef UNIT_ACTION_STATIC_DATA_H
#define UNIT_ACTION_STATIC_DATA_H

#include <string>

#include "unit_action_static_key.h"
#include "item_reqs.h"
#include "item_effects.h"
#include "game_primitives.h"

//================================================================================================================================
//=> - UnitActionStaticDataStruct -
//================================================================================================================================

typedef struct UnitActionStaticDataStruct {
    std::string name;
} UnitActionStaticDataStruct;

//================================================================================================================================
//=> - UnitActionStaticData class -
//================================================================================================================================

class UnitActionStaticData {
public:
    UnitActionStaticData () = default;
    void set_items (UnitActionStaticDataStruct* items, u16 item_count);
    void take_ownership ();
    void release_items ();
    const UnitActionStaticDataStruct& get_item (UnitActionStaticDataKey key) const;
    u16 get_item_count () const;

private:
    UnitActionStaticData (const UnitActionStaticData& other) = delete;
    UnitActionStaticData (UnitActionStaticData&& other) = delete;

    UnitActionStaticDataStruct* m_item_array = nullptr;
    u16 m_item_count = 0;
};

#endif // UNIT_ACTION_STATIC_DATA_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
