//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef WONDER_STATIC_DATA_H
#define WONDER_STATIC_DATA_H

#include "wonder_static_key.h"
#include "item_reqs.h"
#include "item_effects.h"
#include "res_placement.h"
#include "game_primitives.h"
#include "static_string_pool.h"

class DataParserBase;

//================================================================================================================================
//=> - WonderStaticDataStruct -
//================================================================================================================================

typedef struct WonderStaticDataStruct {
    ItemReqsStruct reqs;
    u32 cost;
    ItemEffectsStruct effects;
} WonderStaticDataStruct;

//================================================================================================================================
//=> - WonderStaticData class -
//================================================================================================================================

class WonderStaticData {
public:
    WonderStaticData () = default;
    ~WonderStaticData ();
    void set_items (WonderStaticDataStruct* items, u16 item_count);
    bool load_names (cstr const* names, u16 n);
    bool load_names_from (const DataParserBase& psr, u16 n);
    void take_ownership ();
    void release_items ();
    const WonderStaticDataStruct& get_item (WonderStaticDataKey key) const;
    cstr get_name (WonderStaticDataKey key) const;
    u16 get_item_count () const;

private:
    WonderStaticData (const WonderStaticData& other) = delete;
    WonderStaticData (WonderStaticData&& other) = delete;

    WonderStaticDataStruct* m_item_array = nullptr;
    u16 m_item_count = 0;
    bool m_owns_array = false;
    StaticStringPool m_name_pool;
};

#endif // WONDER_STATIC_DATA_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
