//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include <cstring>

#include "wonder_static_data.h"

//================================================================================================================================
//=> - WonderStaticData implementation -
//================================================================================================================================

WonderStaticData::~WonderStaticData () {
    release_items();
}

void WonderStaticData::set_items (WonderStaticDataStruct* items, u16 item_count) {
    m_item_array = items;
    m_item_count = item_count;
    m_owns_array = false;
}

bool WonderStaticData::load_names (cstr const* names, u16 n) {
    if (!names || n == 0) {
        return false;
    }
    u32 char_n = 0;
    for (u16 i = 0; i < n; ++i) {
        char_n += (u32)std::strlen(names[i] ? names[i] : "");
    }
    StaticStringPool built(n, char_n);
    for (u16 i = 0; i < n; ++i) {
        u16 k = 0;
        if (!built.add(names[i], &k) || k != i) {
            return false;
        }
    }
    m_name_pool = built;
    return true;
}

void WonderStaticData::take_ownership () {
    WonderStaticDataStruct* tmp_array = m_item_array;
    bool tmp_owned = m_owns_array;
    StaticStringPool tmp_pool(m_name_pool);
    m_item_array = new WonderStaticDataStruct[m_item_count];
    for (u16 i = 0; i < m_item_count; ++i) {
        m_item_array[i] = tmp_array[i];
    }
    if (tmp_owned) {
        delete[] tmp_array;
    }
    m_name_pool = tmp_pool;
    m_owns_array = true;
}

void WonderStaticData::release_items () {
    if (m_owns_array) {
        delete[] m_item_array;
        m_owns_array = false;
    }
    m_item_array = nullptr;
    m_item_count = 0;
    m_name_pool.reset();
}

const WonderStaticDataStruct& WonderStaticData::get_item (WonderStaticDataKey key) const {
    u16 idx = key.value();
    return m_item_array[idx];
}

cstr WonderStaticData::get_name (WonderStaticDataKey key) const {
    return m_name_pool.get(key.value());
}

u16 WonderStaticData::get_item_count () const {
    return m_item_count;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
