//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef WORKER_JOB_STATIC_KEY_H
#define WORKER_JOB_STATIC_KEY_H

#include "game_primitives.h"

//================================================================================================================================
//=> - WorkerJobStaticDataKey class -
//================================================================================================================================

class WorkerJobStaticDataKey {
    friend class WorkerJobStaticData;
    friend class WorkerJobBitArray;
    friend class GeneralAssessor;
    friend class KeyHolder;
public:
    constexpr WorkerJobStaticDataKey() : m_val(U16_KEY_NULL) {}

    constexpr bool operator==(WorkerJobStaticDataKey other) const {
        return m_val == other.m_val; 
    }

    constexpr bool operator!=(WorkerJobStaticDataKey other) const { 
        return m_val != other.m_val; 
    }

    constexpr bool is_null() const { 
        return m_val == U16_KEY_NULL; 
    }

    constexpr bool is_valid() const { 
        return m_val != U16_KEY_NULL; 
    }

    static constexpr WorkerJobStaticDataKey None() { 
        return WorkerJobStaticDataKey(U16_KEY_NULL); 
    }

    static constexpr WorkerJobStaticDataKey from_raw(u16 val) {
        return WorkerJobStaticDataKey(val);
    }

    constexpr u16 value() const {
        return m_val;
    }

private:
    u16 m_val;

    explicit constexpr WorkerJobStaticDataKey(u16 val) : 
        m_val(val) {
    }    
};

#endif // WORKER_JOB_STATIC_KEY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
