//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef WORKER_JOB_TYPE_STATIC_DATA_H
#define WORKER_JOB_TYPE_STATIC_DATA_H

#include "worker_job_type_static_key.h"
#include "item_reqs.h"
#include "item_effects.h"
#include "res_placement.h"
#include "combat_mod.h"
#include "game_primitives.h"
#include "static_string_pool.h"

class DataParserBase;

//================================================================================================================================
//=> - WorkerJobTypeStaticDataStruct -
//================================================================================================================================

typedef struct WorkerJobTypeStaticDataStruct {

} WorkerJobTypeStaticDataStruct;

//================================================================================================================================
//=> - WorkerJobTypeStaticData class -
//================================================================================================================================

class WorkerJobTypeStaticData {
public:
    WorkerJobTypeStaticData () = default;
    ~WorkerJobTypeStaticData ();
    void set_items (WorkerJobTypeStaticDataStruct* items, u16 item_count);
    bool load_names (cstr const* names, u16 n);
    bool load_names_from (const DataParserBase& psr, u16 n);
    void take_ownership ();
    void release_items ();
    const WorkerJobTypeStaticDataStruct& get_item (WorkerJobTypeStaticDataKey key) const;
    cstr get_name (WorkerJobTypeStaticDataKey key) const;
    u16 get_item_count () const;

private:
    WorkerJobTypeStaticData (const WorkerJobTypeStaticData& other) = delete;
    WorkerJobTypeStaticData (WorkerJobTypeStaticData&& other) = delete;

    WorkerJobTypeStaticDataStruct* m_item_array = nullptr;
    u16 m_item_count = 0;
    bool m_owns_array = false;
    StaticStringPool m_name_pool;
};

#endif // WORKER_JOB_TYPE_STATIC_DATA_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
