//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef WORKER_JOB_TYPE_STATIC_KEY_H
#define WORKER_JOB_TYPE_STATIC_KEY_H

#include "game_primitives.h"

//================================================================================================================================
//=> - WorkerJobTypeStaticDataKey class -
//================================================================================================================================

class WorkerJobTypeStaticDataKey {
    friend class WorkerJobTypeStaticData;
    friend class WorkerJobTypeBitArray;
    friend class GeneralAssessor;
    friend class KeyHolder;
public:
    constexpr WorkerJobTypeStaticDataKey() : m_val(U16_KEY_NULL) {}

    constexpr bool operator==(WorkerJobTypeStaticDataKey other) const {
        return m_val == other.m_val; 
    }

    constexpr bool operator!=(WorkerJobTypeStaticDataKey other) const { 
        return m_val != other.m_val; 
    }

    constexpr bool is_null() const { 
        return m_val == U16_KEY_NULL; 
    }

    constexpr bool is_valid() const { 
        return m_val != U16_KEY_NULL; 
    }

    static constexpr WorkerJobTypeStaticDataKey None() { 
        return WorkerJobTypeStaticDataKey(U16_KEY_NULL); 
    }

    static constexpr WorkerJobTypeStaticDataKey from_raw(u16 val) {
        return WorkerJobTypeStaticDataKey(val);
    }

    constexpr u16 value() const {
        return m_val;
    }

private:
    u16 m_val;

    explicit constexpr WorkerJobTypeStaticDataKey(u16 val) : 
        m_val(val) {
    }    
};

#endif // WORKER_JOB_TYPE_STATIC_KEY_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
