#!/bin/bash

python3 tool_to_ppm.py "/home/w/Projects/img-content/colors-mtn-bottom-dark4.png"

./tool_palette_maker "/home/w/Projects/img-content/colors-mtn-bottom-dark4.ppm" 16

python3 tool_img_patch_analysis.py "/home/w/Projects/img-content/colors-mtn-bottom-dark4_palette.ppm"

./tool_patch_texture "/home/w/Projects/img-content/colors-mtn-bottom-dark4_palette_patches.txt" 400 400 3 5

python3 tool_tile_noise.py "/home/w/Projects/img-content/colors-mtn-bottom-dark4_palette_texture.ppm"
python3 tool_tile_test.py "/home/w/Projects/img-content/colors-mtn-bottom-dark4_palette_texture_blurred.png"
