#!/bin/bash

python3 tool_to_ppm.py "/home/w/Projects/img-content/colors-tundra1.png"

./tool_palette_maker "/home/w/Projects/img-content/colors-tundra1.ppm"

python3 tool_img_patch_analysis.py "/home/w/Projects/img-content/colors-tundra1_palette.ppm"

./tool_patch_texture "/home/w/Projects/img-content/colors-tundra1_palette_patches.txt" 1600 800 3 5

python3 tool_tile_noise.py "/home/w/Projects/img-content/colors-tundra1_palette_texture.ppm"
python3 tool_tile_test.py "/home/w/Projects/img-content/colors-tundra1_palette_texture_blurred.png"