#!/bin/bash

./tool_patch_texture "/home/w/Projects/img-content/colors-desert1_palette_patches.txt" 1600 800 1 5

python3 tool_tile_noise.py "/home/w/Projects/img-content/colors-desert1_palette_texture.ppm"
python3 tool_tile_test.py "/home/w/Projects/img-content/colors-desert1_palette_texture_blurred.png"