#!/bin/bash

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

INC="-I. -I.. -I../map_loader -I../static_state -I../misc -I../data_io"

g++ -std=c++11 $INC -c ../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ -std=c++11 $INC -c ../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ -std=c++11 $INC -c map_gen_loader.cpp -o map_gen_loader.o
g++ -std=c++11 $INC -c map_gen_tester.cpp -o map_gen_tester.o

g++ -std=c++11 -o map_gen_tester map_terrain_validate.o map_terrain_data.o map_gen_loader.o map_gen_tester.o -ldl

rm map_terrain_validate.o map_terrain_data.o map_gen_loader.o map_gen_tester.o
