#!/bin/bash

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

source p1_build_core_map_objs.sh

INC="-I. -I.. -I../map_loader -I../static_state -I../misc -I../res_dist -I../data_io -I../simple_map_gen -I../ai_pathing/walk_general -I../city -I../city/effector -I../gen_bit_banks -I../game"

g++ -std=c++11 $INC -c mtn_line_ends.cpp -o mtn_line_ends.o
g++ -std=c++11 $INC -c mtn_line_ends_tester.cpp -o mtn_line_ends_tester.o

g++ -std=c++11 -o mtn_line_ends_tester \
    $CORE_MAP_OBJS \
    mtn_line_ends.o \
    mtn_line_ends_tester.o \
    -ldl \
    ../data_io/runtime_static_loader_lib.so \
    -Wl,-rpath,'$ORIGIN/../data_io' -lm

./mtn_line_ends_tester "$@"
RC=$?

rm -f $CORE_MAP_OBJS mtn_line_ends.o mtn_line_ends_tester.o
exit $RC
