#!/bin/bash

set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

source p1_build_river_chain_objs.sh

INC="-I. -I.. -I../map_loader"

g++ -std=c++11 $INC -c p1_adj_river_lakes_tester.cpp -o p1_adj_river_lakes_tester.o

g++ -std=c++11 -o p1_adj_river_lakes_tester \
    $RIV_CHAIN_LAKE_OBJS \
    $RIV_CHAIN_MAP_OBJS \
    p1_adj_river_lakes_tester.o -lm

rm $RIV_CHAIN_LAKE_OBJS $RIV_CHAIN_MAP_OBJS p1_adj_river_lakes_tester.o
