#!/bin/bash

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

source p1_build_core_map_objs.sh

INC="-I. -I.. -I../map_loader -I../static_state"

g++ -std=c++11 $INC -c p1_adj_ensure_mtn_foothills_tester.cpp -o p1_adj_ensure_mtn_foothills_tester.o

g++ -std=c++11 -o p1_adj_ensure_mtn_foothills_tester \
    $CORE_MAP_OBJS \
    p1_adj_ensure_mtn_foothills_tester.o -lm

rm $CORE_MAP_OBJS p1_adj_ensure_mtn_foothills_tester.o
