#!/bin/bash

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

source p1_build_core_map_objs.sh

INC="-I. -I.. -I../map_loader -I../static_state -I../misc"

g++ -std=c++11 $INC -c ../misc/profile_time.cpp -o profile_time.o
g++ -std=c++11 $INC -c p1_adj_delta_swamps.cpp -o p1_adj_delta_swamps.o
g++ -std=c++11 $INC -c p1_adj_delta_swamps_view.cpp -o p1_adj_delta_swamps_view.o
g++ -std=c++11 $INC -c p1_adj_delta_swamps_tester.cpp -o p1_adj_delta_swamps_tester.o

CORE_NO_DELTA="${CORE_MAP_OBJS/p1_adj_delta_swamps.o/}"
CORE_NO_DELTA="${CORE_NO_DELTA/profile_time.o/}"

g++ -std=c++11 -o p1_adj_delta_swamps_tester \
    $CORE_NO_DELTA \
    profile_time.o \
    p1_adj_delta_swamps.o \
    p1_adj_delta_swamps_view.o \
    p1_adj_delta_swamps_tester.o -lm

rm $CORE_MAP_OBJS profile_time.o p1_adj_delta_swamps_view.o p1_adj_delta_swamps_tester.o
rm -f p1_adj_delta_swamps.o
