#!/bin/bash

INC="-I. -I.. -I../map_loader -I../static_state -I../misc"

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"
source p1_build_early_map_objs.sh

g++ -std=c++11 $INC -c p1_gen_river_network.cpp -o p1_gen_river_network.o
g++ -std=c++11 $INC -c p1_gen_river_network_view.cpp -o p1_gen_river_network_view.o
g++ -std=c++11 $INC -c p1_gen_river_network_tester.cpp -o p1_gen_river_network_tester.o

g++ -std=c++11 -o p1_gen_river_network_tester \
    $EARLY_MAP_OBJS \
    p1_gen_river_network.o \
    p1_gen_river_network_view.o \
    p1_gen_river_network_tester.o -lm

rm p1_gen_river_network.o p1_gen_river_network_view.o p1_gen_river_network_tester.o
