#!/bin/bash

set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

source p1_build_core_map_objs.sh

INC="-I. -I.. -I../map_loader -I../static_state -I../misc"

g++ -std=c++11 $INC -c ../misc/profile_time.cpp -o profile_time.o
g++ -std=c++11 $INC -c p1_gen_rich_coast_fertility.cpp -o p1_gen_rich_coast_fertility.o
g++ -std=c++11 $INC -c p1_gen_rich_coast_fertility_tester.cpp -o p1_gen_rich_coast_fertility_tester.o

CORE_NO_RCF="${CORE_MAP_OBJS/p1_gen_rich_coast_fertility.o/}"
CORE_NO_RCF="${CORE_NO_RCF/profile_time.o/}"

g++ -std=c++11 -o p1_gen_rich_coast_fertility_tester \
    $CORE_NO_RCF \
    profile_time.o \
    p1_gen_rich_coast_fertility.o \
    p1_gen_rich_coast_fertility_tester.o -lm

rm $CORE_MAP_OBJS profile_time.o p1_gen_rich_coast_fertility_tester.o
rm -f p1_gen_rich_coast_fertility.o
