#!/bin/bash

INC="-I. -I.."

g++ -std=c++11 $INC -c generator_constants.cpp -o generator_constants.o
g++ -std=c++11 $INC -c perlin_noise.cpp -o perlin_noise.o
g++ -std=c++11 $INC -c whiteboard.cpp -o whiteboard.o
g++ -std=c++11 $INC -c p1_gen_outline.cpp -o p1_gen_outline.o
g++ -std=c++11 $INC -c p1_gen_land_depth.cpp -o p1_gen_land_depth.o
g++ -std=c++11 $INC -c p1_gen_noise_perlin.cpp -o p1_gen_noise_perlin.o
g++ -std=c++11 $INC -c p1_adj_outline_fill.cpp -o p1_adj_outline_fill.o
g++ -std=c++11 $INC -c p1_gen_shaped_outline.cpp -o p1_gen_shaped_outline.o
g++ -std=c++11 $INC -c p1_gen_river_pts.cpp -o p1_gen_river_pts.o
g++ -std=c++11 $INC -c p1_gen_river_sectors.cpp -o p1_gen_river_sectors.o
g++ -std=c++11 $INC -c p1_gen_river_network.cpp -o p1_gen_river_network.o
g++ -std=c++11 $INC -c p1_gen_river_lines.cpp -o p1_gen_river_lines.o
g++ -std=c++11 $INC -c p1_adj_river_lakes.cpp -o p1_adj_river_lakes.o
g++ -std=c++11 $INC -c p1_adj_river_inlets.cpp -o p1_adj_river_inlets.o
g++ -std=c++11 $INC -c p1_gen_watershed_mountains.cpp -o p1_gen_watershed_mountains.o
g++ -std=c++11 $INC -c p1_gen_watershed_mountain_line_sets.cpp -o p1_gen_watershed_mountain_line_sets.o
g++ -std=c++11 $INC -c p1_gen_nearness_to_watershed_mtn.cpp -o p1_gen_nearness_to_watershed_mtn.o
g++ -std=c++11 $INC -c p1_gen_nearness_to_watershed_mtn_tester.cpp -o p1_gen_nearness_to_watershed_mtn_tester.o

g++ -std=c++11 -o p1_gen_nearness_to_watershed_mtn_tester \
    generator_constants.o \
    perlin_noise.o \
    whiteboard.o \
    p1_gen_outline.o \
    p1_gen_land_depth.o \
    p1_gen_noise_perlin.o \
    p1_adj_outline_fill.o \
    p1_gen_shaped_outline.o \
    p1_gen_river_pts.o \
    p1_gen_river_sectors.o \
    p1_gen_river_network.o \
    p1_gen_river_lines.o \
    p1_adj_river_lakes.o \
    p1_adj_river_inlets.o \
    p1_gen_watershed_mountains.o \
    p1_gen_watershed_mountain_line_sets.o \
    p1_gen_nearness_to_watershed_mtn.o \
    p1_gen_nearness_to_watershed_mtn_tester.o -lm

rm generator_constants.o \
    perlin_noise.o \
    whiteboard.o \
    p1_gen_outline.o \
    p1_gen_land_depth.o \
    p1_gen_noise_perlin.o \
    p1_adj_outline_fill.o \
    p1_gen_shaped_outline.o \
    p1_gen_river_pts.o \
    p1_gen_river_sectors.o \
    p1_gen_river_network.o \
    p1_gen_river_lines.o \
    p1_adj_river_lakes.o \
    p1_adj_river_inlets.o \
    p1_gen_watershed_mountains.o \
    p1_gen_watershed_mountain_line_sets.o \
    p1_gen_nearness_to_watershed_mtn.o \
    p1_gen_nearness_to_watershed_mtn_tester.o
