#!/bin/bash

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

source p1_build_core_map_objs.sh

g++ -std=c++11 -I. -I.. -I../map_loader -c p1_gen_rich_coast_fertility_tester.cpp -o p1_gen_rich_coast_fertility_tester.o

g++ -std=c++11 -o p1_gen_rich_coast_fertility_tester \
    $CORE_MAP_OBJS \
    p1_gen_rich_coast_fertility_tester.o -lm

rm $CORE_MAP_OBJS p1_gen_rich_coast_fertility_tester.o
