#!/bin/bash

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

source p1_build_core_map_objs.sh

INC="-I. -I.. -I../map_loader -I../static_state -I../simple_map_gen -I../misc"

g++ -std=c++11 $INC -c p1_gen_noise_perlin_tester.cpp -o p1_gen_noise_perlin_tester.o

g++ -std=c++11 -o p1_gen_noise_perlin_tester \
    $CORE_MAP_OBJS \
    p1_gen_noise_perlin_tester.o -lm

rm $CORE_MAP_OBJS p1_gen_noise_perlin_tester.o
