#!/bin/bash

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

source p1_build_core_map_objs.sh

g++ -std=c++11 $INC -c p1_gen_forest_overlay_tester.cpp -o p1_gen_forest_overlay_tester.o

g++ -std=c++11 -o p1_gen_forest_overlay_tester \
    $CORE_MAP_OBJS \
    p1_gen_forest_overlay_tester.o -lm

rm $CORE_MAP_OBJS p1_gen_forest_overlay_tester.o
