#!/bin/bash

INC="-I. -I.. -I../simple_map_gen"

g++ -std=c++11 $INC -c generator_constants.cpp -o generator_constants.o
g++ -std=c++11 $INC -c perlin_noise.cpp -o perlin_noise.o
g++ -std=c++11 $INC -c whiteboard.cpp -o whiteboard.o
g++ -std=c++11 $INC -c p1_gen_outline.cpp -o p1_gen_outline.o
g++ -std=c++11 $INC -c ../simple_map_gen/generate_terrain_rotation.cpp -o generate_terrain_rotation.o
g++ -std=c++11 $INC -c p1_gen_cont_outlines.cpp -o p1_gen_cont_outlines.o
g++ -std=c++11 $INC -c p1_gen_cont_outlines_tester.cpp -o p1_gen_cont_outlines_tester.o
g++ -std=c++11 $INC -c p1_gen_cont_outlines_seq_tester.cpp -o p1_gen_cont_outlines_seq_tester.o

g++ -std=c++11 -o p1_gen_cont_outlines_tester \
    generator_constants.o \
    perlin_noise.o \
    whiteboard.o \
    p1_gen_outline.o \
    generate_terrain_rotation.o \
    p1_gen_cont_outlines.o \
    p1_gen_cont_outlines_tester.o -lm

g++ -std=c++11 -o p1_gen_cont_outlines_seq_tester \
    generator_constants.o \
    perlin_noise.o \
    whiteboard.o \
    p1_gen_outline.o \
    generate_terrain_rotation.o \
    p1_gen_cont_outlines.o \
    p1_gen_cont_outlines_seq_tester.o -lm

rm generator_constants.o \
    perlin_noise.o \
    whiteboard.o \
    p1_gen_outline.o \
    generate_terrain_rotation.o \
    p1_gen_cont_outlines.o \
    p1_gen_cont_outlines_tester.o \
    p1_gen_cont_outlines_seq_tester.o
