#!/bin/bash

set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

source p1_build_core_map_objs.sh

INC="-I. -I.. -I../map_loader -I../static_state -I../misc"

g++ -std=c++11 $INC -c ../misc/profile_time.cpp -o profile_time.o
g++ -std=c++11 $INC -c p1_gen_watershed_mountains.cpp -o p1_gen_watershed_mountains.o
g++ -std=c++11 $INC -c p1_gen_watershed_mountains_tester.cpp -o p1_gen_watershed_mountains_tester.o

CORE_NO_WSHED="${CORE_MAP_OBJS/p1_gen_watershed_mountains.o/}"
CORE_NO_WSHED="${CORE_NO_WSHED/profile_time.o/}"

g++ -std=c++11 -o p1_gen_watershed_mountains_tester \
    $CORE_NO_WSHED \
    profile_time.o \
    p1_gen_watershed_mountains.o \
    p1_gen_watershed_mountains_tester.o -lm

rm $CORE_MAP_OBJS profile_time.o p1_gen_watershed_mountains_tester.o
rm -f p1_gen_watershed_mountains.o
