#!/bin/bash

INC="-I. -I.."

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"
source p1_build_tester_cli_obj.sh

g++ -std=c++11 $INC -c generator_constants.cpp -o generator_constants.o
g++ -std=c++11 $INC -c perlin_noise.cpp -o perlin_noise.o
g++ -std=c++11 $INC -c whiteboard.cpp -o whiteboard.o
g++ -std=c++11 $INC -c wb_sheet.cpp -o wb_sheet.o
g++ -std=c++11 $INC -c wb_que_xy.cpp -o wb_que_xy.o
g++ -std=c++11 $INC -c p1_gen_outline.cpp -o p1_gen_outline.o
g++ -std=c++11 $INC -I../simple_map_gen -c ../simple_map_gen/generate_terrain_rotation.cpp -o generate_terrain_rotation.o
g++ -std=c++11 $INC -I../simple_map_gen -c p1_gen_cont_outlines.cpp -o p1_gen_cont_outlines.o
g++ -std=c++11 $INC -c p1_gen_land_depth.cpp -o p1_gen_land_depth.o
g++ -std=c++11 $INC -c p1_adj_outline_fill.cpp -o p1_adj_outline_fill.o
g++ -std=c++11 $INC -c p1_gen_shaped_outline.cpp -o p1_gen_shaped_outline.o
g++ -std=c++11 $INC -c p1_gen_river_pts.cpp -o p1_gen_river_pts.o
g++ -std=c++11 $INC -c p1_gen_river_sectors.cpp -o p1_gen_river_sectors.o
g++ -std=c++11 $INC -c p1_gen_coastal_mtn_limits.cpp -o p1_gen_coastal_mtn_limits.o
g++ -std=c++11 $INC -c p1_gen_coastal_mtn_limits_tester.cpp -o p1_gen_coastal_mtn_limits_tester.o

g++ -std=c++11 -o p1_gen_coastal_mtn_limits_tester \
    p1_tester_cli.o \
    generator_constants.o \
    perlin_noise.o \
    whiteboard.o \
    wb_sheet.o \
    wb_que_xy.o \
    p1_gen_outline.o \
    generate_terrain_rotation.o \
    p1_gen_cont_outlines.o \
    p1_gen_land_depth.o \
    p1_adj_outline_fill.o \
    p1_gen_shaped_outline.o \
    p1_gen_river_pts.o \
    p1_gen_river_sectors.o \
    p1_gen_coastal_mtn_limits.o \
    p1_gen_coastal_mtn_limits_tester.o -lm

rm generator_constants.o \
    perlin_noise.o \
    whiteboard.o \
    wb_sheet.o \
    wb_que_xy.o \
    p1_gen_outline.o \
    generate_terrain_rotation.o \
    p1_gen_cont_outlines.o \
    p1_gen_land_depth.o \
    p1_adj_outline_fill.o \
    p1_gen_shaped_outline.o \
    p1_gen_river_pts.o \
    p1_gen_river_sectors.o \
    p1_gen_coastal_mtn_limits.o \
    p1_tester_cli.o \
    p1_gen_coastal_mtn_limits_tester.o
