#!/bin/bash

set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

source p1_build_river_chain_objs.sh

INC="-I. -I.. -I../map_loader"

g++ -std=c++11 $INC -c p1_gen_river_lines_tester.cpp -o p1_gen_river_lines_tester.o

g++ -std=c++11 -o p1_gen_river_lines_tester \
    $RIV_CHAIN_LINE_OBJS \
    p1_gen_river_lines_tester.o -lm

rm $RIV_CHAIN_LINE_OBJS p1_gen_river_lines_tester.o
