#!/bin/bash

INC="-I. -I.."

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"
source p1_build_tester_cli_obj.sh

g++ -std=c++11 $INC -c generator_constants.cpp -o generator_constants.o
g++ -std=c++11 $INC -c perlin_noise.cpp -o perlin_noise.o
g++ -std=c++11 $INC -c whiteboard.cpp -o whiteboard.o
g++ -std=c++11 $INC -c p1_gen_outline.cpp -o p1_gen_outline.o
g++ -std=c++11 $INC -I../simple_map_gen -c ../simple_map_gen/generate_terrain_rotation.cpp -o generate_terrain_rotation.o
g++ -std=c++11 $INC -I../simple_map_gen -c p1_gen_cont_outlines.cpp -o p1_gen_cont_outlines.o
g++ -std=c++11 $INC -c p1_gen_land_depth.cpp -o p1_gen_land_depth.o
g++ -std=c++11 $INC -c p1_gen_noise_perlin.cpp -o p1_gen_noise_perlin.o
g++ -std=c++11 $INC -c p1_adj_outline_fill.cpp -o p1_adj_outline_fill.o
g++ -std=c++11 $INC -c p1_gen_shaped_outline.cpp -o p1_gen_shaped_outline.o
g++ -std=c++11 $INC -c p1_gen_river_pts.cpp -o p1_gen_river_pts.o
g++ -std=c++11 $INC -c wb_sheet.cpp -o wb_sheet.o
g++ -std=c++11 $INC -c wb_que_xy.cpp -o wb_que_xy.o
g++ -std=c++11 $INC -c p1_gen_river_sectors.cpp -o p1_gen_river_sectors.o
g++ -std=c++11 $INC -c p1_gen_coastal_mtn_limits.cpp -o p1_gen_coastal_mtn_limits.o
g++ -std=c++11 $INC -c p1_gen_river_network.cpp -o p1_gen_river_network.o
g++ -std=c++11 $INC -c p1_gen_river_lines.cpp -o p1_gen_river_lines.o
 g++ -std=c++11 $INC -c p1_adj_coastal_mtn_rivers.cpp -o p1_adj_coastal_mtn_rivers.o
g++ -std=c++11 $INC -c p1_adj_river_lakes.cpp -o p1_adj_river_lakes.o
g++ -std=c++11 $INC -c p1_adj_river_inlets.cpp -o p1_adj_river_inlets.o
g++ -std=c++11 $INC -c p1_gen_watershed_mountains.cpp -o p1_gen_watershed_mountains.o
g++ -std=c++11 $INC -c p1_gen_watershed_mountain_line_sets.cpp -o p1_gen_watershed_mountain_line_sets.o
g++ -std=c++11 $INC -c p1_gen_watershed_mountain_line_sets_tester.cpp -o p1_gen_watershed_mountain_line_sets_tester.o

g++ -std=c++11 -o p1_gen_watershed_mountain_line_sets_tester \
    generator_constants.o \
    perlin_noise.o \
    whiteboard.o \
    wb_sheet.o \
    wb_que_xy.o \
    p1_gen_outline.o \
generate_terrain_rotation.o \
    p1_tester_cli.o \
    p1_gen_cont_outlines.o \
        p1_gen_land_depth.o \
    p1_gen_noise_perlin.o \
    p1_adj_outline_fill.o \
    p1_gen_shaped_outline.o \
    p1_gen_river_pts.o \
    p1_gen_river_sectors.o \
    p1_gen_coastal_mtn_limits.o \
    p1_gen_river_network.o \
    p1_gen_river_lines.o \
    p1_adj_coastal_mtn_rivers.o \
    p1_adj_river_lakes.o \
    p1_adj_river_inlets.o \
    p1_gen_watershed_mountains.o \
    p1_gen_watershed_mountain_line_sets.o \
    p1_gen_watershed_mountain_line_sets_tester.o -lm

rm generator_constants.o \
    perlin_noise.o \
    whiteboard.o \
    wb_sheet.o \
    wb_que_xy.o \
    p1_gen_outline.o \
generate_terrain_rotation.o \
    p1_gen_cont_outlines.o \
        p1_gen_land_depth.o \
    p1_gen_noise_perlin.o \
    p1_adj_outline_fill.o \
    p1_gen_shaped_outline.o \
    p1_gen_river_pts.o \
    p1_gen_river_sectors.o \
    p1_gen_coastal_mtn_limits.o \
    p1_gen_river_network.o \
    p1_gen_river_lines.o \
    p1_adj_coastal_mtn_rivers.o \
    p1_adj_river_lakes.o \
    p1_adj_river_inlets.o \
    p1_gen_watershed_mountains.o \
    p1_gen_watershed_mountain_line_sets.o \
    p1_gen_watershed_mountain_line_sets_tester.o
