#!/bin/bash

INC="-I. -I.."

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"
source p1_build_tester_cli_obj.sh

g++ -std=c++11 $INC -c generator_constants.cpp -o generator_constants.o
g++ -std=c++11 $INC -c perlin_noise.cpp -o perlin_noise.o
g++ -std=c++11 $INC -c whiteboard.cpp -o whiteboard.o
g++ -std=c++11 $INC -c p1_gen_outline.cpp -o p1_gen_outline.o
g++ -std=c++11 $INC -c p1_gen_outline_tester.cpp -o p1_gen_outline_tester.o

g++ -std=c++11 -o p1_gen_outline_tester \
    p1_tester_cli.o \
    generator_constants.o \
    perlin_noise.o \
    whiteboard.o \
    p1_gen_outline.o \
    p1_gen_outline_tester.o -lm

rm generator_constants.o \
    perlin_noise.o \
    whiteboard.o \
    p1_gen_outline.o \
    p1_tester_cli.o \
    p1_gen_outline_tester.o
