#!/bin/bash

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

source p1_build_core_map_objs.sh

INC="-I. -I.. -I../map_loader -I../static_state -I../misc"

g++ -std=c++11 $INC -c ../misc/profile_time.cpp -o profile_time.o
g++ -std=c++11 $INC -c p1_gen_climate.cpp -o p1_gen_climate.o
g++ -std=c++11 $INC -c p1_tester_chain_core.cpp -o p1_tester_chain_core.o
g++ -std=c++11 $INC -c p1_gen_climate_tester.cpp -o p1_gen_climate_tester.o

CORE_NO_TRACE="${CORE_MAP_OBJS/p1_gen_climate.o/}"
CORE_NO_TRACE="${CORE_NO_TRACE/p1_tester_chain_core.o/}"
CORE_NO_TRACE="${CORE_NO_TRACE/profile_time.o/}"

g++ -std=c++11 -o p1_gen_climate_tester \
    $CORE_NO_TRACE \
    profile_time.o \
    p1_gen_climate.o \
    p1_tester_chain_core.o \
    p1_gen_climate_tester.o -lm

rm $CORE_MAP_OBJS p1_gen_climate_tester.o
rm -f p1_gen_climate.o p1_tester_chain_core.o profile_time.o
