#!/bin/bash

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

source p1_build_core_map_objs.sh

INC="-I. -I.. -I../map_loader -I../static_state -I../misc -I../res_dist -I../data_io -I../ai_pathing/walk_general"

g++ -std=c++11 $INC -DP1_ENABLE_TIMING -c p1_make_map.cpp -o p1_make_map.o
g++ -std=c++11 $INC -c p1_make_map_tester.cpp -o p1_make_map_tester.o

g++ -std=c++11 -o p1_make_map_tester \
    $CORE_MAP_OBJS \
    p1_make_map_tester.o \
    -ldl \
    ../data_io/runtime_static_loader_lib.so \
    -Wl,-rpath,'$ORIGIN/../data_io' -lm

rm $CORE_MAP_OBJS p1_make_map_tester.o
