#!/bin/bash

INC="-I../ -I../misc -I../data_io -I../static_state"
CXXFLAGS="-std=c++17"
LIB_SO="../data_io/runtime_static_loader_lib.so"

if [ ! -f "$LIB_SO" ]; then
    echo "missing $LIB_SO - run ../data_io/runtime_static_loader_lib_comp first"
    exit 1
fi

g++ $CXXFLAGS $INC -c ../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
g++ $CXXFLAGS $INC -c res_statics.cpp -o res_statics.o
g++ $CXXFLAGS $INC -c resource_parsing_tester.cpp -o resource_parsing_tester.o

g++ $CXXFLAGS -o resource_parsing_tester \
    runtime_static_loader.o \
    res_statics.o \
    resource_parsing_tester.o \
    -ldl \
    $LIB_SO \
    -Wl,-rpath,'$ORIGIN/../data_io'

rm runtime_static_loader.o res_statics.o resource_parsing_tester.o
