#!/bin/bash
set -e

cd "$(dirname "$0")"

INC="-I.. -I../.. -I../../game"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../circular_tile_areas.cpp -o circular_tile_areas.o
g++ $CXXFLAGS $INC -c circular_tile_areas_tester.cpp -o circular_tile_areas_tester.o
g++ $CXXFLAGS -o circular_tile_areas_tester circular_tile_areas.o circular_tile_areas_tester.o
rm circular_tile_areas.o circular_tile_areas_tester.o
