#!/bin/bash
set -e

cd "$(dirname "$0")"

INC="-I.. -I../.. -I../../game -I../../map_loader -I../../simple_map_gen -I../../misc -I../../adv_map_gen"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../circular_tile_areas.cpp -o circular_tile_areas.o
g++ $CXXFLAGS $INC -c ../city_blocking_mask.cpp -o city_blocking_mask.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_loader.cpp -o map_loader.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ $CXXFLAGS $INC -c ../../game/runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c ../../game/game_array_simple.cpp -o game_array_simple.o
g++ $CXXFLAGS $INC -c ../../game/factory_game_array_simple.cpp -o factory_game_array_simple.o
g++ $CXXFLAGS $INC -c city_blocking_mask_tester.cpp -o city_blocking_mask_tester.o
g++ $CXXFLAGS -o city_blocking_mask_tester \
    circular_tile_areas.o \
    city_blocking_mask.o \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    runtime_trace_dbg.o \
    game_array_simple.o \
    factory_game_array_simple.o \
    city_blocking_mask_tester.o
./city_blocking_mask_tester
rm -f circular_tile_areas.o city_blocking_mask.o map_terrain_validate.o map_terrain_data.o \
    map_loader.o runtime_trace_dbg.o game_array_simple.o factory_game_array_simple.o \
    city_blocking_mask_tester.o
