#!/bin/bash
set -e

cd "$(dirname "$0")"

LIB_SO="../../data_io/runtime_static_loader_lib.so"
if [ ! -f "$LIB_SO" ]; then
    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
    exit 1
fi

INC="-I../../ \
     -I../../misc \
     -I../../data_io \
     -I../../static_state \
     -I../ \
     -I../effector \
     -I../assessor \
     -I../../dyn_state \
     -I../../gen_bit_banks \
     -I../../game \
     -I../../map_loader \
     -I../../adv_map_gen \
     -I../../simple_map_gen \
     -I."
CXXFLAGS="-std=c++17 -Wall -Wextra"

OBJS=(
    runtime_static_loader.o
    bit_array.o
    map_bit_overlay.o
    map_bit_array_overlay.o
    map_terrain_validate.o
    map_terrain_data.o
    map_loader.o
    runtime_trace_dbg.o
    general_bit_bank.o
    general_assessor.o
    effect_ctx.o
    effect_enabler.o
    booster_effect_register.o
    local_unit_exp_booster_register.o
    civ_ship_training_booster_register.o
    city_commerce_booster_register.o
    unit_add_vector.o
    unit_movement_mng.o
    fort_add_vector.o
    mine_add_vector.o
    monastery_add_vector.o
    outpost_add_vector.o
    plantation_add_vector.o
    shipyard_add_vector.o
    trade_post_add_vector.o
    game_array_simple.o
    factory_game_array_simple.o
    game_state.o
    player_ledger.o
    civ_relations.o
    city_array.o
    city.o
)

compile_core () {
    g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
    g++ $CXXFLAGS $INC -c ../../misc/bit_array.cpp -o bit_array.o
    g++ $CXXFLAGS $INC -c ../../misc/map_bit_overlay.cpp -o map_bit_overlay.o
    g++ $CXXFLAGS $INC -c ../../misc/map_bit_array_overlay.cpp -o map_bit_array_overlay.o
    g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
    g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_data.cpp -o map_terrain_data.o
    g++ $CXXFLAGS $INC -c ../../map_loader/map_loader.cpp -o map_loader.o
    g++ $CXXFLAGS $INC -c ../../game/runtime_trace_dbg.cpp -o runtime_trace_dbg.o
    g++ $CXXFLAGS $INC -c ../../gen_bit_banks/general_bit_bank.cpp -o general_bit_bank.o
    g++ $CXXFLAGS $INC -c ../assessor/general_assessor.cpp -o general_assessor.o
    g++ $CXXFLAGS $INC -c ../effect_ctx.cpp -o effect_ctx.o
    g++ $CXXFLAGS $INC -c ../effector/effect_enabler.cpp -o effect_enabler.o
    g++ $CXXFLAGS $INC -c ../effector/booster_effect_register.cpp -o booster_effect_register.o
    g++ $CXXFLAGS $INC -c ../effector/local_unit_exp_booster_register.cpp -o local_unit_exp_booster_register.o
    g++ $CXXFLAGS $INC -c ../effector/civ_ship_training_booster_register.cpp -o civ_ship_training_booster_register.o
    g++ $CXXFLAGS $INC -c ../effector/city_commerce_booster_register.cpp -o city_commerce_booster_register.o
    g++ $CXXFLAGS $INC -c ../../dyn_state/unit_add_vector.cpp -o unit_add_vector.o
    g++ $CXXFLAGS $INC -c ../../dyn_state/unit_movement_mng.cpp -o unit_movement_mng.o
    g++ $CXXFLAGS $INC -c ../../dyn_state/fort_add_vector.cpp -o fort_add_vector.o
    g++ $CXXFLAGS $INC -c ../../dyn_state/mine_add_vector.cpp -o mine_add_vector.o
    g++ $CXXFLAGS $INC -c ../../dyn_state/monastery_add_vector.cpp -o monastery_add_vector.o
    g++ $CXXFLAGS $INC -c ../../dyn_state/outpost_add_vector.cpp -o outpost_add_vector.o
    g++ $CXXFLAGS $INC -c ../../dyn_state/plantation_add_vector.cpp -o plantation_add_vector.o
    g++ $CXXFLAGS $INC -c ../../dyn_state/shipyard_add_vector.cpp -o shipyard_add_vector.o
    g++ $CXXFLAGS $INC -c ../../dyn_state/trade_post_add_vector.cpp -o trade_post_add_vector.o
    g++ $CXXFLAGS $INC -c ../../game/game_array_simple.cpp -o game_array_simple.o
    g++ $CXXFLAGS $INC -c ../../game/factory_game_array_simple.cpp -o factory_game_array_simple.o
    g++ $CXXFLAGS $INC -c ../../game/game_state.cpp -o game_state.o
    g++ $CXXFLAGS $INC -c ../../game/player_ledger.cpp -o player_ledger.o
    g++ $CXXFLAGS $INC -c ../../game/civ_relations.cpp -o civ_relations.o
    g++ $CXXFLAGS $INC -c ../../game/city_array.cpp -o city_array.o
    g++ $CXXFLAGS $INC -c ../city.cpp -o city.o
}

link_driver () {
    local src="$1"
    local out="$2"
    g++ $CXXFLAGS $INC -c "$src" -o "${out}.o"
    g++ $CXXFLAGS -o "$out" "${OBJS[@]}" "${out}.o" -ldl $LIB_SO -Wl,-rpath,'$ORIGIN/../../data_io'
    rm "${out}.o"
}

compile_core

link_driver city_unit_level_booster_tester.cpp city_unit_level_booster_tester
link_driver city_sea_training_booster_tester.cpp city_sea_training_booster_tester
link_driver city_commerce_booster_tester.cpp city_commerce_booster_tester

echo "--- running city_unit_level_booster_tester ---"
./city_unit_level_booster_tester
echo "--- running city_sea_training_booster_tester ---"
./city_sea_training_booster_tester
echo "--- running city_commerce_booster_tester ---"
./city_commerce_booster_tester

rm "${OBJS[@]}"
