#!/bin/bash
set -e

cd "$(dirname "$0")"

INC="-I. -I.. -I../.. -I../../game -I../../misc -I../../data_io -I../../map_loader -I../../simple_map_gen -I../../adv_map_gen -I../../city -I../../city/effector -I../../static_state -I../../dyn_state -I../../gen_bit_banks"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_loader.cpp -o map_loader.o
g++ $CXXFLAGS $INC -c ../../game/runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c ../../misc/assert_log.cpp -o assert_log.o
g++ $CXXFLAGS $INC -c ../../ai_proc/test_drivers/game_array_simple_link_stubs.cpp -o game_array_simple_link_stubs.o
g++ $CXXFLAGS $INC -c ../../game/game_array_simple.cpp -o game_array_simple.o
g++ $CXXFLAGS $INC -c ../../game/factory_game_array_simple.cpp -o factory_game_array_simple.o
g++ $CXXFLAGS $INC -c sector_network.cpp -o sector_network.o
g++ $CXXFLAGS $INC -c sector_network_tester.cpp -o sector_network_tester.o

g++ $CXXFLAGS -o sector_network_tester \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    runtime_trace_dbg.o \
    assert_log.o \
    game_array_simple_link_stubs.o \
    game_array_simple.o \
    factory_game_array_simple.o \
    sector_network.o \
    sector_network_tester.o

./sector_network_tester "$@"
RC=$?

rm -f map_terrain_validate.o map_terrain_data.o map_loader.o runtime_trace_dbg.o assert_log.o \
    game_array_simple_link_stubs.o game_array_simple.o factory_game_array_simple.o \
    sector_network.o sector_network_tester.o sector_network_tester

exit $RC
