//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef ASSERT_SECTOR_SUPPORT_BOUND_H
#define ASSERT_SECTOR_SUPPORT_BOUND_H

#include "game_primitives.h"
#include "log_dbg_toggles.h"

//================================================================================================================================
//=> - ASSERT_SECTOR_SUPPORT_BOUND -
//================================================================================================================================

#if defined(LOG_DBG_SO_BUILD) || defined(LOG_DBG_FORCE_ALL) || (defined(LOG_DBG_ENABLE) && defined(ENABLED_ASSERT_SECTOR_SUPPORT_BOUND))

class ASSERT_SECTOR_SUPPORT_BOUND {
public:
    static void ASSERT (bool ok);

private:
    ASSERT_SECTOR_SUPPORT_BOUND () = delete;
};

#else

class ASSERT_SECTOR_SUPPORT_BOUND {
public:
    static void ASSERT (bool ok) { (void)ok; }

private:
    ASSERT_SECTOR_SUPPORT_BOUND () = delete;
};

#endif

#endif // ASSERT_SECTOR_SUPPORT_BOUND_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
