//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef ASSERT_CITY_JOB_ARE_COVERED_H
#define ASSERT_CITY_JOB_ARE_COVERED_H

#include "game_primitives.h"
#include "log_dbg_toggles.h"

//================================================================================================================================
//=> - ASSERT_CITY_JOB_ARE_COVERED -
//================================================================================================================================

#if defined(LOG_DBG_SO_BUILD) || defined(LOG_DBG_FORCE_ALL) || (defined(LOG_DBG_ENABLE) && defined(ENABLED_ASSERT_CITY_JOB_ARE_COVERED))

class ASSERT_CITY_JOB_ARE_COVERED {
public:
    static void ASSERT (bool ok);

private:
    ASSERT_CITY_JOB_ARE_COVERED () = delete;
};

#else

class ASSERT_CITY_JOB_ARE_COVERED {
public:
    static void ASSERT (bool ok) { (void)ok; }

private:
    ASSERT_CITY_JOB_ARE_COVERED () = delete;
};

#endif

#endif // ASSERT_CITY_JOB_ARE_COVERED_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
