//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef LOG_WAR_MUSTER_GRAD_FAIL_H
#define LOG_WAR_MUSTER_GRAD_FAIL_H

#include "game_primitives.h"
#include "log_dbg_toggles.h"

 

//================================================================================================================================
//=> - LOG_WAR_MUSTER_GRAD_FAIL -
//================================================================================================================================

class LOG_WAR_MUSTER_GRAD_FAIL {
public:
#if defined(LOG_DBG_SO_BUILD) || defined(LOG_DBG_FORCE_ALL) || (defined(LOG_DBG_ENABLE) && defined(ENABLED_LOG_WAR_MUSTER_GRAD_FAIL))
    static void LOG (unsigned seat, unsigned sx, unsigned sy, unsigned turn);
#else
    static void LOG (unsigned seat, unsigned sx, unsigned sy, unsigned turn) {
        (void)seat;
        (void)sx;
        (void)sy;
        (void)turn;
    }
#endif
    static bool PARSE (const char* line, unsigned* seat, unsigned* sx, unsigned* sy, unsigned* turn);

private:
    LOG_WAR_MUSTER_GRAD_FAIL () = delete;
};

#endif // LOG_WAR_MUSTER_GRAD_FAIL_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
