//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef LOG_WAR_TILE_ENTRY_RESOLVE_H
#define LOG_WAR_TILE_ENTRY_RESOLVE_H

#include "game_primitives.h"
#include "log_dbg_toggles.h"

 

//================================================================================================================================
//=> - LOG_WAR_TILE_ENTRY_RESOLVE -
//================================================================================================================================

class LOG_WAR_TILE_ENTRY_RESOLVE {
public:
#if defined(LOG_DBG_SO_BUILD) || defined(LOG_DBG_FORCE_ALL) || (defined(LOG_DBG_ENABLE) && defined(ENABLED_LOG_WAR_TILE_ENTRY_RESOLVE))
    static void LOG (unsigned seat, unsigned unit, unsigned x, unsigned y, unsigned reason, unsigned outcome, unsigned turn);
#else
    static void LOG (unsigned seat, unsigned unit, unsigned x, unsigned y, unsigned reason, unsigned outcome, unsigned turn) {
        (void)seat;
        (void)unit;
        (void)x;
        (void)y;
        (void)reason;
        (void)outcome;
        (void)turn;
    }
#endif
    static bool PARSE (const char* line, unsigned* seat, unsigned* unit, unsigned* x, unsigned* y, unsigned* reason, unsigned* outcome, unsigned* turn);

private:
    LOG_WAR_TILE_ENTRY_RESOLVE () = delete;
};

#endif // LOG_WAR_TILE_ENTRY_RESOLVE_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
