//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//  - Real body always compiled into log_dbg.so (LOG_DBG_SO_BUILD).
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#define LOG_DBG_SO_BUILD
#include "log_war_own_free_comp_fail.h"

#include "trace_sink.h"

#include <cstdio>

//================================================================================================================================
//=> - LOG_WAR_OWN_FREE_COMP_FAIL -
//================================================================================================================================

void LOG_WAR_OWN_FREE_COMP_FAIL::LOG (unsigned seat, unsigned turn, unsigned reason) {
    TraceSink::printf("war own free comp fail seat=%u turn=%u reason=%u\n", seat, turn, reason);
}

bool LOG_WAR_OWN_FREE_COMP_FAIL::PARSE (const char* line, unsigned* seat, unsigned* turn, unsigned* reason) {
    if (line == nullptr || seat == nullptr || turn == nullptr || reason == nullptr) {
        return false;
    }
    unsigned t0 = 0;
    unsigned t1 = 0;
    unsigned t2 = 0;
    if (std::sscanf(line, "war own free comp fail seat=%u turn=%u reason=%u", &t0, &t1, &t2) != 3) {
        return false;
    }
    *seat = t0;
    *turn = t1;
    *reason = t2;
    return true;
}

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
