//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef LOG_CITY_JOB_PRODUCTION_H
#define LOG_CITY_JOB_PRODUCTION_H

#include "game_primitives.h"
#include "log_dbg_toggles.h"



//================================================================================================================================
//=> - LOG_CITY_JOB_PRODUCTION -
//================================================================================================================================

#if defined(LOG_DBG_SO_BUILD) || defined(LOG_DBG_FORCE_ALL) || (defined(LOG_DBG_ENABLE) && defined(ENABLED_LOG_CITY_JOB_PRODUCTION))

class LOG_CITY_JOB_PRODUCTION {
public:
    static void LOG (u16 jobs, u16 yield);

private:
    LOG_CITY_JOB_PRODUCTION () = delete;
};

#else

class LOG_CITY_JOB_PRODUCTION {
public:
    static void LOG (u16 jobs, u16 yield) {
        (void)jobs;
        (void)yield;
    }

private:
    LOG_CITY_JOB_PRODUCTION () = delete;
};

#endif

#endif // LOG_CITY_JOB_PRODUCTION_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
