//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef LOG_WAR_ARMY_UPGRADE_H
#define LOG_WAR_ARMY_UPGRADE_H

#include "game_primitives.h"
#include "log_dbg_toggles.h"

 

//================================================================================================================================
//=> - LOG_WAR_ARMY_UPGRADE -
//================================================================================================================================

class LOG_WAR_ARMY_UPGRADE {
public:
#if defined(LOG_DBG_SO_BUILD) || defined(LOG_DBG_FORCE_ALL) || (defined(LOG_DBG_ENABLE) && defined(ENABLED_LOG_WAR_ARMY_UPGRADE))
    static void LOG (unsigned seat, unsigned civ, unsigned from_u, unsigned to_u, unsigned turn);
#else
    static void LOG (unsigned seat, unsigned civ, unsigned from_u, unsigned to_u, unsigned turn) {
        (void)seat;
        (void)civ;
        (void)from_u;
        (void)to_u;
        (void)turn;
    }
#endif
    static bool PARSE (const char* line, unsigned* seat, unsigned* civ, unsigned* from_u, unsigned* to_u, unsigned* turn);

private:
    LOG_WAR_ARMY_UPGRADE () = delete;
};

#endif // LOG_WAR_ARMY_UPGRADE_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
