//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//  - Real body always compiled into log_dbg.so (LOG_DBG_SO_BUILD).
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#define LOG_DBG_SO_BUILD
#include "log_unit_state.h"

#include "trace_sink.h"

#include <cstdio>

//================================================================================================================================
//=> - LOG_UNIT_STATE -
//================================================================================================================================

void LOG_UNIT_STATE::LOG (u16 owner, u16 unit, u16 x, u16 y) {
    TraceSink::printf("unit state owner=%u unit=%u at=(%u,%u)\n", owner, unit, x, y);
}

bool LOG_UNIT_STATE::PARSE (const char* line, u16* owner, u16* unit, u16* x, u16* y) {
    if (line == nullptr || owner == nullptr || unit == nullptr || x == nullptr || y == nullptr) {
        return false;
    }
    unsigned t0 = 0;
    unsigned t1 = 0;
    unsigned t2 = 0;
    unsigned t3 = 0;
    if (std::sscanf(line, "unit state owner=%u unit=%u at=(%u,%u)", &t0, &t1, &t2, &t3) != 4) {
        return false;
    }
    *owner = static_cast<u16>(t0);
    *unit = static_cast<u16>(t1);
    *x = static_cast<u16>(t2);
    *y = static_cast<u16>(t3);
    return true;
}

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
