//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef LOG_NEED_MASK_H
#define LOG_NEED_MASK_H

#include "game_primitives.h"

//================================================================================================================================
//=> - LogNeedMask -
//================================================================================================================================
//
//  One u8 per log channel (0 = not required). Drivers set desired channels to 1+.
//
//================================================================================================================================

static const u16 LOG_NEED_N = 20u;

struct LogNeedMask {
    u8 m_new_turn;
    u8 m_city_foundation;
    u8 m_civ_spawn_pt;
    u8 m_unit_spawn;
    u8 m_war_muster;
    u8 m_war_peace_mock;
    u8 m_war_army_size;
    u8 m_war_city_capture;
    u8 m_city_job_food;
    u8 m_city_job_production;
    u8 m_city_job_commerce;
    u8 m_city_job_culture;
    u8 m_city_job_science;
    u8 m_city_job_religion;
    u8 m_city_job_yields;
    u8 m_player_commerce;
    u8 m_player_commerce_raw;
    u8 m_player_science;
    u8 m_player_research_perc;
    u8 m_player_tech_discover;

    LogNeedMask ();
    bool any () const;
    u8* bytes ();
    const u8* bytes () const;
    static u16 n ();
    static cstr nm (u16 i);
};

inline LogNeedMask::LogNeedMask ()
    : m_new_turn(0),
      m_city_foundation(0),
      m_civ_spawn_pt(0),
      m_unit_spawn(0),
      m_war_muster(0),
      m_war_peace_mock(0),
      m_war_army_size(0),
      m_war_city_capture(0),
      m_city_job_food(0),
      m_city_job_production(0),
      m_city_job_commerce(0),
      m_city_job_culture(0),
      m_city_job_science(0),
      m_city_job_religion(0),
      m_city_job_yields(0),
      m_player_commerce(0),
      m_player_commerce_raw(0),
      m_player_science(0),
      m_player_research_perc(0),
      m_player_tech_discover(0) {
}

inline bool LogNeedMask::any () const {
    const u8* b = bytes();
    for (u16 i = 0; i < LOG_NEED_N; ++i) {
        if (b[i] != 0) {
            return true;
        }
    }
    return false;
}

inline u8* LogNeedMask::bytes () {
    return &m_new_turn;
}

inline const u8* LogNeedMask::bytes () const {
    return &m_new_turn;
}

inline u16 LogNeedMask::n () {
    return LOG_NEED_N;
}

inline cstr LogNeedMask::nm (u16 i) {
    static const cstr k_nm[LOG_NEED_N] = {
        "NewTurn",
        "CityFoundation",
        "CivSpawnPt",
        "UnitSpawn",
        "WarMuster",
        "WarPeaceMock",
        "WarArmySize",
        "WarCityCapture",
        "CityJobFood",
        "CityJobProduction",
        "CityJobCommerce",
        "CityJobCulture",
        "CityJobScience",
        "CityJobReligion",
        "CityJobYields",
        "PlayerCommerce",
        "PlayerCommerceRaw",
        "PlayerScience",
        "PlayerResearchPerc",
        "PlayerTechDiscover",
    };
    if (i >= LOG_NEED_N) {
        return "";
    }
    return k_nm[i];
}

#endif // LOG_NEED_MASK_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
