//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef LOG_WAR_REJOIN_MOVE_FAIL_H
#define LOG_WAR_REJOIN_MOVE_FAIL_H

#include "game_primitives.h"
#include "log_dbg_toggles.h"

 

//================================================================================================================================
//=> - LOG_WAR_REJOIN_MOVE_FAIL -
//================================================================================================================================

class LOG_WAR_REJOIN_MOVE_FAIL {
public:
#if defined(LOG_DBG_SO_BUILD) || defined(LOG_DBG_FORCE_ALL) || (defined(LOG_DBG_ENABLE) && defined(ENABLED_LOG_WAR_REJOIN_MOVE_FAIL))
    static void LOG (unsigned seat, unsigned enemy, unsigned army_i, unsigned turn, unsigned reason, unsigned sx, unsigned sy, unsigned dx, unsigned dy);
#else
    static void LOG (unsigned seat, unsigned enemy, unsigned army_i, unsigned turn, unsigned reason, unsigned sx, unsigned sy, unsigned dx, unsigned dy) {
        (void)seat;
        (void)enemy;
        (void)army_i;
        (void)turn;
        (void)reason;
        (void)sx;
        (void)sy;
        (void)dx;
        (void)dy;
    }
#endif
    static bool PARSE (const char* line, unsigned* seat, unsigned* enemy, unsigned* army_i, unsigned* turn, unsigned* reason, unsigned* sx, unsigned* sy, unsigned* dx, unsigned* dy);

private:
    LOG_WAR_REJOIN_MOVE_FAIL () = delete;
};

#endif // LOG_WAR_REJOIN_MOVE_FAIL_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
