//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//  - Real body always compiled into log_dbg.so (LOG_DBG_SO_BUILD).
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#define LOG_DBG_SO_BUILD
#include "log_war_tile_entry_resolve.h"

#include "trace_sink.h"

#include <cstdio>

//================================================================================================================================
//=> - LOG_WAR_TILE_ENTRY_RESOLVE -
//================================================================================================================================

void LOG_WAR_TILE_ENTRY_RESOLVE::LOG (unsigned seat, unsigned unit, unsigned x, unsigned y, unsigned reason, unsigned outcome, unsigned turn) {
    TraceSink::printf("war tile entry resolve seat=%u unit=%u at=(%u,%u) reason=%u outcome=%u turn=%u\n", seat, unit, x, y, reason, outcome, turn);
}

bool LOG_WAR_TILE_ENTRY_RESOLVE::PARSE (const char* line, unsigned* seat, unsigned* unit, unsigned* x, unsigned* y, unsigned* reason, unsigned* outcome, unsigned* turn) {
    if (line == nullptr || seat == nullptr || unit == nullptr || x == nullptr || y == nullptr || reason == nullptr || outcome == nullptr || turn == nullptr) {
        return false;
    }
    unsigned t0 = 0;
    unsigned t1 = 0;
    unsigned t2 = 0;
    unsigned t3 = 0;
    unsigned t4 = 0;
    unsigned t5 = 0;
    unsigned t6 = 0;
    if (std::sscanf(line, "war tile entry resolve seat=%u unit=%u at=(%u,%u) reason=%u outcome=%u turn=%u", &t0, &t1, &t2, &t3, &t4, &t5, &t6) != 7) {
        return false;
    }
    *seat = t0;
    *unit = t1;
    *x = t2;
    *y = t3;
    *reason = t4;
    *outcome = t5;
    *turn = t6;
    return true;
}

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
