//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef LOG_WAR_CITY_CAPTURE_H
#define LOG_WAR_CITY_CAPTURE_H

#include "game_primitives.h"
#include "log_dbg_toggles.h"

 

//================================================================================================================================
//=> - LOG_WAR_CITY_CAPTURE -
//================================================================================================================================

class LOG_WAR_CITY_CAPTURE {
public:
#if defined(LOG_DBG_SO_BUILD) || defined(LOG_DBG_FORCE_ALL) || (defined(LOG_DBG_ENABLE) && defined(ENABLED_LOG_WAR_CITY_CAPTURE))
    static void LOG (unsigned seat, unsigned from, unsigned x, unsigned y, unsigned turn);
#else
    static void LOG (unsigned seat, unsigned from, unsigned x, unsigned y, unsigned turn) {
        (void)seat;
        (void)from;
        (void)x;
        (void)y;
        (void)turn;
    }
#endif
    static bool PARSE (const char* line, unsigned* seat, unsigned* from, unsigned* x, unsigned* y, unsigned* turn);

private:
    LOG_WAR_CITY_CAPTURE () = delete;
};

#endif // LOG_WAR_CITY_CAPTURE_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
