//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//  - Real body always compiled into log_dbg.so (LOG_DBG_SO_BUILD).
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#define LOG_DBG_SO_BUILD
#include "log_war_targets.h"

#include "trace_sink.h"

#include <cstdio>

//================================================================================================================================
//=> - LOG_WAR_TARGETS -
//================================================================================================================================

void LOG_WAR_TARGETS::LOG (unsigned seat, unsigned enemy, unsigned tn, unsigned turn) {
    TraceSink::printf("war targets seat=%u enemy=%u n=%u turn=%u\n", seat, enemy, tn, turn);
}

bool LOG_WAR_TARGETS::PARSE (const char* line, unsigned* seat, unsigned* enemy, unsigned* tn, unsigned* turn) {
    if (line == nullptr || seat == nullptr || enemy == nullptr || tn == nullptr || turn == nullptr) {
        return false;
    }
    unsigned t0 = 0;
    unsigned t1 = 0;
    unsigned t2 = 0;
    unsigned t3 = 0;
    if (std::sscanf(line, "war targets seat=%u enemy=%u n=%u turn=%u", &t0, &t1, &t2, &t3) != 4) {
        return false;
    }
    *seat = t0;
    *enemy = t1;
    *tn = t2;
    *turn = t3;
    return true;
}

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
