//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//  - Real body always compiled into log_dbg.so (LOG_DBG_SO_BUILD).
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#define LOG_DBG_SO_BUILD
#include "log_war_army_upgrade.h"

#include "trace_sink.h"

#include <cstdio>

//================================================================================================================================
//=> - LOG_WAR_ARMY_UPGRADE -
//================================================================================================================================

void LOG_WAR_ARMY_UPGRADE::LOG (unsigned seat, unsigned civ, unsigned from_u, unsigned to_u, unsigned turn) {
    TraceSink::printf("war army upgrade seat=%u civ=%u from=%u to=%u turn=%u\n", seat, civ, from_u, to_u, turn);
}

bool LOG_WAR_ARMY_UPGRADE::PARSE (const char* line, unsigned* seat, unsigned* civ, unsigned* from_u, unsigned* to_u, unsigned* turn) {
    if (line == nullptr || seat == nullptr || civ == nullptr || from_u == nullptr || to_u == nullptr || turn == nullptr) {
        return false;
    }
    unsigned t0 = 0;
    unsigned t1 = 0;
    unsigned t2 = 0;
    unsigned t3 = 0;
    unsigned t4 = 0;
    if (std::sscanf(line, "war army upgrade seat=%u civ=%u from=%u to=%u turn=%u", &t0, &t1, &t2, &t3, &t4) != 5) {
        return false;
    }
    *seat = t0;
    *civ = t1;
    *from_u = t2;
    *to_u = t3;
    *turn = t4;
    return true;
}

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
