//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef LOG_WAR_START_CAMP_FAIL_H
#define LOG_WAR_START_CAMP_FAIL_H

#include "game_primitives.h"
#include "log_dbg_toggles.h"

 

//================================================================================================================================
//=> - LOG_WAR_START_CAMP_FAIL -
//================================================================================================================================

class LOG_WAR_START_CAMP_FAIL {
public:
#if defined(LOG_DBG_SO_BUILD) || defined(LOG_DBG_FORCE_ALL) || (defined(LOG_DBG_ENABLE) && defined(ENABLED_LOG_WAR_START_CAMP_FAIL))
    static void LOG (unsigned seat, unsigned enemy, unsigned turn, unsigned reason);
#else
    static void LOG (unsigned seat, unsigned enemy, unsigned turn, unsigned reason) {
        (void)seat;
        (void)enemy;
        (void)turn;
        (void)reason;
    }
#endif
    static bool PARSE (const char* line, unsigned* seat, unsigned* enemy, unsigned* turn, unsigned* reason);

private:
    LOG_WAR_START_CAMP_FAIL () = delete;
};

#endif // LOG_WAR_START_CAMP_FAIL_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
