//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef LOG_WAR_ARMY_CANT_FIGHT_H
#define LOG_WAR_ARMY_CANT_FIGHT_H

#include "game_primitives.h"
#include "log_dbg_toggles.h"

 

//================================================================================================================================
//=> - LOG_WAR_ARMY_CANT_FIGHT -
//================================================================================================================================

class LOG_WAR_ARMY_CANT_FIGHT {
public:
#if defined(LOG_DBG_SO_BUILD) || defined(LOG_DBG_FORCE_ALL) || (defined(LOG_DBG_ENABLE) && defined(ENABLED_LOG_WAR_ARMY_CANT_FIGHT))
    static void LOG (unsigned seat, unsigned enemy, unsigned army_i, unsigned turn);
#else
    static void LOG (unsigned seat, unsigned enemy, unsigned army_i, unsigned turn) {
        (void)seat;
        (void)enemy;
        (void)army_i;
        (void)turn;
    }
#endif
    static bool PARSE (const char* line, unsigned* seat, unsigned* enemy, unsigned* army_i, unsigned* turn);

private:
    LOG_WAR_ARMY_CANT_FIGHT () = delete;
};

#endif // LOG_WAR_ARMY_CANT_FIGHT_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
