//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef PROF_TH_WAR_H
#define PROF_TH_WAR_H

#include "game_primitives.h"
#include "log_dbg_toggles.h"

//================================================================================================================================
//=> - PROF_TH_WAR -
//================================================================================================================================

#if defined(LOG_DBG_SO_BUILD) || defined(LOG_DBG_FORCE_ALL) || (defined(LOG_DBG_ENABLE) && defined(ENABLED_PROF_TH_WAR))

class PROF_TH_WAR {
public:
    static void SETUP (cstr dir);

    class Guard {
    public:
        explicit Guard (cstr func);
        ~Guard ();

    private:
        Guard (const Guard&) = delete;
        Guard& operator= (const Guard&) = delete;

        cstr m_fn; // Entered function name; must match stack top on destroy
    };
};

#define PROF_TH_WAR_SETUP(dir) ::PROF_TH_WAR::SETUP(dir)
#define PROF_TH_WAR_ENTER(fn) ::PROF_TH_WAR::Guard _prof_guard_##__LINE__(fn)

#else

#define PROF_TH_WAR_SETUP(dir) ((void)(dir))
#define PROF_TH_WAR_ENTER(fn) ((void)(fn))

#endif

#endif // PROF_TH_WAR_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
