//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by gen_log_dbg.py
//  - Do not edit this file manually.
//  - Real body always compiled into log_dbg.so (LOG_DBG_SO_BUILD).
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#define LOG_DBG_SO_BUILD
#include "prof_game_loop.h"

#include <chrono>
#include <cstdio>
#include <cstring>
#include <cstdlib>

//================================================================================================================================
//=> - Backend -
//================================================================================================================================

static const u16 k_stack_cap = 256u;
static const char* k_file_name = "prof_game_loop.txt";

struct ProfFrame {
    cstr m_fn;
    u64 m_t0_ns;
};

static std::FILE* s_fp = nullptr;
static ProfFrame s_stack[k_stack_cap];
static u16 s_n = 0u;

static u64 prof_now_ns () {
    const auto t = std::chrono::steady_clock::now().time_since_epoch();
    return static_cast<u64>(std::chrono::duration_cast<std::chrono::nanoseconds>(t).count());
}

static void prof_fatal (cstr msg) {
    if (s_fp != nullptr) {
        std::fflush(s_fp);
    }
    std::fprintf(stderr, "PROF_GAME_LOOP fatal: %s\n", msg);
    std::exit(1);
}

//================================================================================================================================
//=> - PROF_GAME_LOOP -
//================================================================================================================================

void PROF_GAME_LOOP::SETUP (cstr dir) {
    if (s_fp != nullptr) {
        std::fclose(s_fp);
        s_fp = nullptr;
    }
    s_n = 0u;
    char path[512];
    if (dir != nullptr && dir[0] != 0) {
        if (std::snprintf(path, sizeof(path), "%s/%s", dir, k_file_name) <= 0) {
            prof_fatal("bad prof path");
        }
    } else if (std::snprintf(path, sizeof(path), "%s", k_file_name) <= 0) {
        prof_fatal("bad prof path");
    }
    s_fp = std::fopen(path, "w");
    if (s_fp == nullptr) {
        prof_fatal("fopen failed");
    }
}

PROF_GAME_LOOP::Guard::Guard (cstr func) : m_fn(func) {
    if (func == nullptr || func[0] == 0) {
        prof_fatal("enter null func");
    }
    if (s_fp == nullptr) {
        prof_fatal("enter before setup");
    }
    if (s_n >= k_stack_cap) {
        prof_fatal("stack overflow");
    }
    s_stack[s_n].m_fn = func;
    s_stack[s_n].m_t0_ns = prof_now_ns();
    s_n = static_cast<u16>(s_n + 1u);
}

PROF_GAME_LOOP::Guard::~Guard () {
    if (s_n == 0u) {
        prof_fatal("return empty stack");
    }
    const u16 i = static_cast<u16>(s_n - 1u);
    const ProfFrame fr = s_stack[i];
    if (fr.m_fn == nullptr || m_fn == nullptr || std::strcmp(fr.m_fn, m_fn) != 0) {
        prof_fatal("return name mismatch");
    }
    s_n = i;
    const u64 dt = prof_now_ns() - fr.m_t0_ns;
    std::fprintf(s_fp, "%s=%llu\n", fr.m_fn, static_cast<unsigned long long>(dt));
}

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
