#!/bin/bash

cd "$(dirname "$0")"

INC="-I. -I.. -I../game -I../map_loader -I../simple_map_gen -I../adv_map_gen"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ $CXXFLAGS $INC -c ../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ $CXXFLAGS $INC -c ../map_loader/map_loader.cpp -o map_loader.o
g++ $CXXFLAGS $INC -c ../game/runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c ../game/game_array_simple.cpp -o game_array_simple.o
g++ $CXXFLAGS $INC -c ../game/factory_game_array_simple.cpp -o factory_game_array_simple.o
g++ $CXXFLAGS $INC -c city_network_stubs.cpp -o city_network_stubs.o
g++ $CXXFLAGS $INC -c city_network.cpp -o city_network.o
g++ $CXXFLAGS $INC -c city_network_router.cpp -o city_network_router.o
g++ $CXXFLAGS $INC -c city_network_router_tester.cpp -o city_network_router_tester.o

g++ $CXXFLAGS -o city_network_router_tester \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    runtime_trace_dbg.o \
    game_array_simple.o \
    factory_game_array_simple.o \
    city_network_stubs.o \
    city_network.o \
    city_network_router.o \
    city_network_router_tester.o

rm map_terrain_validate.o map_terrain_data.o map_loader.o runtime_trace_dbg.o \
    game_array_simple.o factory_game_array_simple.o \
    city_network_stubs.o city_network.o city_network_router.o city_network_router_tester.o
