#!/bin/bash

INC="-I.. -I../misc -I../static_state -I../gen_static_state -I../static_variable_state"

g++ $INC -c ../misc/bit_array.cpp -o bit_array.o
g++ $INC -c [MEMBER_TAG]_bit_array.cpp -o [MEMBER_TAG]_bit_array.o
g++ $INC -c [MEMBER_TAG]_static_data.cpp -o [MEMBER_TAG]_static_data.o

g++ -o [MEMBER_TAG]_bit_array_tester \
    bit_array.o \
    [MEMBER_TAG]_bit_array.o \
    [MEMBER_TAG]_static_data.o

rm -f \
    bit_array.o \
    [MEMBER_TAG]_bit_array.o \
    [MEMBER_TAG]_static_data.o
