//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef [MACRO_PREFIX]_STATIC_DATA_H
#define [MACRO_PREFIX]_STATIC_DATA_H

#include "[MEMBER_TAG]_static_key.h"
#include "item_reqs.h"
#include "item_effects.h"
#include "res_placement.h"
#include "game_primitives.h"
#include "static_string_pool.h"

class DataParserBase;

//================================================================================================================================
//=> - [DATA_STRUCT] -
//================================================================================================================================

typedef struct [DATA_STRUCT] {
[STRUCT_MEMBERS]
} [DATA_STRUCT];

//================================================================================================================================
//=> - [CLASS_NAME] class -
//================================================================================================================================

class [CLASS_NAME] {
public:
    [CLASS_NAME] () = default;
    ~[CLASS_NAME] ();
    void set_items ([DATA_STRUCT]* items, u16 item_count);
    bool load_names (cstr const* names, u16 n);
    bool load_names_from (const DataParserBase& psr, u16 n);
    void take_ownership ();
    void release_items ();
    const [DATA_STRUCT]& get_item ([DATA_KEY] key) const;
    cstr get_name ([DATA_KEY] key) const;
    u16 get_item_count () const;

private:
    [CLASS_NAME] (const [CLASS_NAME]& other) = delete;
    [CLASS_NAME] ([CLASS_NAME]&& other) = delete;

    [DATA_STRUCT]* m_item_array = nullptr;
    u16 m_item_count = 0;
    bool m_owns_array = false;
    StaticStringPool m_name_pool;
};

#endif // [MACRO_PREFIX]_STATIC_DATA_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
