#!/bin/bash

INC="-I.. -I../static_state"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c [MEMBER_TAG]_static_data.cpp -o [MEMBER_TAG]_static_data.o
g++ $CXXFLAGS $INC -c [MEMBER_TAG]_static_data_tester.cpp -o [MEMBER_TAG]_static_data_tester.o

g++ $CXXFLAGS -o [MEMBER_TAG]_static_data_tester [MEMBER_TAG]_static_data.o [MEMBER_TAG]_static_data_tester.o

rm [MEMBER_TAG]_static_data.o [MEMBER_TAG]_static_data_tester.o
