//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_config_settings.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include "config_settings_static.h"

//================================================================================================================================
//=> - Helpers -
//================================================================================================================================

static void clr_list_unit (ConfigListUnit* lst) {
    lst->n = 0;
    for (u16 i = 0; i < MAX_CONFIG_LIST_ITEMS; ++i) {
        lst->keys[i] = UnitStaticDataKey::None();
    }
}

static void assign_u16 (u16* dst, u16 src) {
    *dst = src;
}

static void assign_list_unit (ConfigListUnit* dst, ConfigListUnit src) {
    dst->n = src.n;
    for (u16 i = 0; i < MAX_CONFIG_LIST_ITEMS; ++i) {
        dst->keys[i] = src.keys[i];
    }
}

static bool eq_u16 (u16 a, u16 b) {
    return a == b;
}

static bool eq_list_unit (ConfigListUnit a, ConfigListUnit b) {
    if (a.n != b.n) {
        return false;
    }
    for (u16 i = 0; i < a.n; ++i) {
        if (a.keys[i] != b.keys[i]) {
            return false;
        }
    }
    return true;
}

static void clr_data (ConfigSettingsData* d) {
    [CONFIG_CLR_DATA_BODY_TAG]
}

//================================================================================================================================
//=> - GameConfigSettings -
//================================================================================================================================

GameConfigSettings::GameConfigSettings () :
    m_is_default(true),
    m_cfg(nullptr) 
{
    clr_data(&m_defaults);
}

GameConfigSettings::~GameConfigSettings () {
    reset();
}

void GameConfigSettings::reset () {
    delete m_cfg;
    m_cfg = nullptr;
    m_is_default = true;
}

bool GameConfigSettings::is_default () const {
    return m_is_default;
}

void GameConfigSettings::ensure_ovr () {
    if (!m_is_default) {
        return;
    }
    m_cfg = new ConfigSettingsData(m_defaults);
    m_is_default = false;
}

const ConfigSettingsData& GameConfigSettings::cur () const {
    if (m_is_default) {
        return m_defaults;
    }
    return *m_cfg;
}

//================================================================================================================================
//=> - Getters and setters -
//================================================================================================================================

[CONFIG_ACCESSOR_IMPLS_TAG]

//================================================================================================================================
//=> - End -
//================================================================================================================================
