//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef WONDER_STATIC_DATA_H
#define WONDER_STATIC_DATA_H

#include <string>

#include "wonder_static_key.h"
#include "item_reqs.h"
#include "item_effects.h"
#include "game_primitives.h"

//================================================================================================================================
//=> - WonderStaticDataStruct -
//================================================================================================================================

typedef struct WonderStaticDataStruct {
    std::string name;
    ItemReqsStruct reqs;
    u32 cost;
    ItemEffectsStruct effects;
} WonderStaticDataStruct;

//================================================================================================================================
//=> - WonderStaticData class -
//================================================================================================================================

class WonderStaticData {
public:
    WonderStaticData () = default;
    void set_items (WonderStaticDataStruct* items, u16 item_count);
    void take_ownership ();
    void release_items ();
    const WonderStaticDataStruct& get_item (WonderStaticDataKey key) const;
    u16 get_item_count () const;

private:
    WonderStaticData (const WonderStaticData& other) = delete;
    WonderStaticData (WonderStaticData&& other) = delete;

    WonderStaticDataStruct* m_item_array = nullptr;
    u16 m_item_count = 0;
};

#endif // WONDER_STATIC_DATA_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
