#!/bin/bash

INC="-I.. -I../static_state"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c wonder_static_data.cpp -o wonder_static_data.o
g++ $CXXFLAGS $INC -c wonder_static_data_tester.cpp -o wonder_static_data_tester.o

g++ $CXXFLAGS -o wonder_static_data_tester wonder_static_data.o wonder_static_data_tester.o

rm wonder_static_data.o wonder_static_data_tester.o
