//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_static_data_and_test.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include "wonder_static_data.h"

//================================================================================================================================
//=> - WonderStaticData implementation -
//================================================================================================================================

void WonderStaticData::set_items (WonderStaticDataStruct* items, u16 item_count) {
    m_item_array = items;
    m_item_count = item_count;
}

void WonderStaticData::take_ownership () {
    WonderStaticDataStruct* tmp_array = m_item_array;
    m_item_array = new WonderStaticDataStruct[m_item_count];
    for (u16 i = 0; i < m_item_count; ++i) {
        m_item_array[i] = tmp_array[i];
    }
    delete[] tmp_array;
}

void WonderStaticData::release_items () {
    delete[] m_item_array;
    m_item_array = nullptr;
    m_item_count = 0;
}

const WonderStaticDataStruct& WonderStaticData::get_item (WonderStaticDataKey key) const {
    u16 idx = key.value();
    return m_item_array[idx];
}

u16 WonderStaticData::get_item_count () const {
    return m_item_count;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
