#!/bin/bash

# Define the include path for the compiler
INC="-I../misc -I../buildings -I../resources -I../city"

# Compile objects (Adding the path to files in misc)
g++ $INC -c ../misc/str_mng.cpp -o str_mng.o
g++ $INC -c ../misc/bit_array.cpp -o bit_array.o
g++ $INC -c ../buildings/building_vector.cpp -o building_vector.o
g++ $INC -c ../resources/resources_vector.cpp -o resources_vector.o
g++ $INC -c buildable_assessor.cpp -o buildable_assessor.o
g++ $INC -c buildable_assessor_tester.cpp -o buildable_assessor_tester.o

# Link everything into the final tester
g++ -o buildable_assessor_tester str_mng.o bit_array.o building_vector.o resources_vector.o buildable_assessor.o buildable_assessor_tester.o

# Clean up
rm str_mng.o bit_array.o building_vector.o resources_vector.o buildable_assessor.o buildable_assessor_tester.o