//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py from TEMPLATE_general_assessor.h
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef GENERAL_ASSESSOR_H
#define GENERAL_ASSESSOR_H

#include "item_reqs.h"
#include "game_primitives.h"

class BitArrayCL;

//================================================================================================================================
//=> - AssessorCtx -
//================================================================================================================================

struct AssessorCtx {
    const BitArrayCL* m_tech;
    const BitArrayCL* m_resource;
    const BitArrayCL* m_building;
    const BitArrayCL* m_city_flag;
    const BitArrayCL* m_civ;
};

//================================================================================================================================
//=> - GeneralAssessor -
//================================================================================================================================

class GeneralAssessor {
public:
    static bool chk (const ItemReqsStruct& reqs, const AssessorCtx& ctx);
    static BitArrayCL* assess (u16 item_count, const ItemReqsStruct* reqs_per_item, const AssessorCtx& ctx);

private:
    GeneralAssessor () = delete;
    GeneralAssessor (const GeneralAssessor& other) = delete;
    GeneralAssessor (GeneralAssessor&& other) = delete;
};

#endif // GENERAL_ASSESSOR_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
