//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate.py from TEMPLATE_general_assessor.h
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef GENERAL_ASSESSOR_H
#define GENERAL_ASSESSOR_H

#include "item_reqs.h"
#include "game_primitives.h"

class BitArrayCL;

struct BuildingStaticDataStruct;
struct CityFlagStaticDataStruct;
struct ResourceStaticDataStruct;
struct SmallWonderStaticDataStruct;
struct TechStaticDataStruct;
struct UnitStaticDataStruct;
struct WonderStaticDataStruct;

//================================================================================================================================
//=> - AssessorCtx -
//================================================================================================================================

struct AssessorCtx {
    const BitArrayCL* m_tech;
    const BitArrayCL* m_resource;
    const BitArrayCL* m_building;
    const BitArrayCL* m_city_flag;
    const BitArrayCL* m_civ;
};

//================================================================================================================================
//=> - GeneralAssessor -
//================================================================================================================================

class GeneralAssessor {
public:
    static bool chk (const ItemReqsStruct& reqs, const AssessorCtx& ctx);
    
    static BitArrayCL* assess_building (u16 item_count, const BuildingStaticDataStruct* items, const AssessorCtx& ctx);
    static BitArrayCL* assess_city_flag (u16 item_count, const CityFlagStaticDataStruct* items, const AssessorCtx& ctx);
    static BitArrayCL* assess_resource (u16 item_count, const ResourceStaticDataStruct* items, const AssessorCtx& ctx);
    static BitArrayCL* assess_small_wonder (u16 item_count, const SmallWonderStaticDataStruct* items, const AssessorCtx& ctx);
    static BitArrayCL* assess_tech (u16 item_count, const TechStaticDataStruct* items, const AssessorCtx& ctx);
    static BitArrayCL* assess_unit (u16 item_count, const UnitStaticDataStruct* items, const AssessorCtx& ctx);
    static BitArrayCL* assess_wonder (u16 item_count, const WonderStaticDataStruct* items, const AssessorCtx& ctx);

private:
    GeneralAssessor () = delete;
    GeneralAssessor (const GeneralAssessor& other) = delete;
    GeneralAssessor (GeneralAssessor&& other) = delete;
};

#endif // GENERAL_ASSESSOR_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
