#!/bin/bash
set -e

cd "$(dirname "$0")"

LIB_SO="../../data_io/runtime_static_loader_lib.so"
if [ ! -f "$LIB_SO" ]; then
    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
    exit 1
fi

INC="-I../.. \
     -I.. \
     -I../../misc \
     -I../../map_loader \
     -I../../simple_map_gen \
     -I../../dyn_state \
     -I../../data_io \
     -I../../static_state \
     -I../../gen_bit_banks \
     -I../../game \
     -I../../game/game_helpers \
     -I../../city \
     -I../../city/assessor \
     -I../../city/effector \
     -I../../ai_pathing/walk_general \
     -I../../ai_pathing/walk_cities \
     -I../../adv_map_gen"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_loader.cpp -o map_loader.o
g++ $CXXFLAGS $INC -c ../../game/runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c ../../misc/map_bit_overlay.cpp -o map_bit_overlay.o
g++ $CXXFLAGS $INC -c ../../misc/map_bit_array_overlay.cpp -o map_bit_array_overlay.o
g++ $CXXFLAGS $INC -c ../../misc/bit_array.cpp -o bit_array.o
g++ $CXXFLAGS $INC -c ../../dyn_state/fort_add_vector.cpp -o fort_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/mine_add_vector.cpp -o mine_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/monastery_add_vector.cpp -o monastery_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/outpost_add_vector.cpp -o outpost_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/plantation_add_vector.cpp -o plantation_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/shipyard_add_vector.cpp -o shipyard_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/trade_post_add_vector.cpp -o trade_post_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/unit_add_vector.cpp -o unit_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/unit_movement_mng.cpp -o unit_movement_mng.o
g++ $CXXFLAGS $INC -c ../../game/tile_attr_tables.cpp -o tile_attr_tables.o
g++ $CXXFLAGS $INC -c ../../ai_pathing/walk_general/sector_network.cpp -o sector_network.o
g++ $CXXFLAGS $INC -c ../../ai_pathing/walk_general/sector_network_router.cpp -o sector_network_router.o
g++ $CXXFLAGS $INC -c ../../game/game_array_simple.cpp -o game_array_simple.o
g++ $CXXFLAGS $INC -c ../../game/factory_game_array_simple.cpp -o factory_game_array_simple.o
g++ $CXXFLAGS $INC -c ../../game/game_state.cpp -o game_state.o
g++ $CXXFLAGS $INC -c ../../game/player_ledger.cpp -o player_ledger.o
g++ $CXXFLAGS $INC -c ../../game/civ_relations.cpp -o civ_relations.o
g++ $CXXFLAGS $INC -c ../../game/tile_yields.cpp -o tile_yields.o
g++ $CXXFLAGS $INC -c ../../game/tile_working.cpp -o tile_working.o
g++ $CXXFLAGS $INC -c ../../game/std_add_helper.cpp -o std_add_helper.o
g++ $CXXFLAGS $INC -c ../../game/worker_helper.cpp -o worker_helper.o
g++ $CXXFLAGS $INC -c ../../game/city_array.cpp -o city_array.o
g++ $CXXFLAGS $INC -c ../../gen_bit_banks/general_bit_bank.cpp -o general_bit_bank.o
g++ $CXXFLAGS $INC -c ../../city/assessor/general_assessor.cpp -o general_assessor.o
g++ $CXXFLAGS $INC -c ../../city/effect_ctx.cpp -o effect_ctx.o
g++ $CXXFLAGS $INC -c ../../city/effector/effect_enabler.cpp -o effect_enabler.o
g++ $CXXFLAGS $INC -c ../../city/effector/booster_effect_register.cpp -o booster_effect_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/local_unit_exp_booster_register.cpp -o local_unit_exp_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/civ_ship_training_booster_register.cpp -o civ_ship_training_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/city_commerce_booster_register.cpp -o city_commerce_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/city_production_booster_register.cpp -o city_production_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/local_production_booster_register.cpp -o local_production_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/local_pop_growth_booster_register.cpp -o local_pop_growth_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/local_commerce_booster_register.cpp -o local_commerce_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/city_pop_growth_booster_register.cpp -o city_pop_growth_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/civ_pop_growth_booster_register.cpp -o civ_pop_growth_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/effector/city_culture_booster_register.cpp -o city_culture_booster_register.o
g++ $CXXFLAGS $INC -c ../../city/city.cpp -o city.o
g++ $CXXFLAGS $INC -c ../../city/city_tile_manager.cpp -o city_tile_manager.o
g++ $CXXFLAGS $INC -c ../../city/circular_tile_areas.cpp -o circular_tile_areas.o
g++ $CXXFLAGS $INC -c ../../city/city_border.cpp -o city_border.o
g++ $CXXFLAGS $INC -c ../../ai_pathing/walk_cities/city_network.cpp -o city_network.o
g++ $CXXFLAGS $INC -c ../city_connector.cpp -o city_connector.o
g++ $CXXFLAGS $INC -c city_connector_tester.cpp -o city_connector_tester.o

g++ $CXXFLAGS -o city_connector_tester \
    runtime_static_loader.o \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    runtime_trace_dbg.o \
    map_bit_overlay.o \
    map_bit_array_overlay.o \
    bit_array.o \
    fort_add_vector.o \
    mine_add_vector.o \
    monastery_add_vector.o \
    outpost_add_vector.o \
    plantation_add_vector.o \
    shipyard_add_vector.o \
    trade_post_add_vector.o \
    unit_add_vector.o \
    unit_movement_mng.o \
    tile_attr_tables.o \
    sector_network.o \
    sector_network_router.o \
    game_array_simple.o \
    factory_game_array_simple.o \
    game_state.o \
    player_ledger.o \
    civ_relations.o \
    tile_yields.o \
    tile_working.o \
    std_add_helper.o \
    worker_helper.o \
    city_array.o \
    general_bit_bank.o \
    general_assessor.o \
    effect_ctx.o \
    effect_enabler.o \
    booster_effect_register.o \
    local_unit_exp_booster_register.o \
    civ_ship_training_booster_register.o \
    city_commerce_booster_register.o \
    city_production_booster_register.o \
    local_production_booster_register.o \
    local_pop_growth_booster_register.o \
    local_commerce_booster_register.o \
    city_pop_growth_booster_register.o \
    civ_pop_growth_booster_register.o \
    city_culture_booster_register.o \
    city.o \
    city_tile_manager.o \
    circular_tile_areas.o \
    city_border.o \
    city_network.o \
    city_connector.o \
    city_connector_tester.o \
    -ldl \
    $LIB_SO \
    -Wl,-rpath,'$ORIGIN/../../data_io'

rm -f runtime_static_loader.o map_terrain_validate.o map_terrain_data.o map_loader.o runtime_trace_dbg.o \
    map_bit_overlay.o map_bit_array_overlay.o bit_array.o fort_add_vector.o mine_add_vector.o \
    monastery_add_vector.o outpost_add_vector.o plantation_add_vector.o shipyard_add_vector.o \
    trade_post_add_vector.o unit_add_vector.o unit_movement_mng.o tile_attr_tables.o \
    sector_network.o sector_network_router.o game_array_simple.o factory_game_array_simple.o \
    game_state.o player_ledger.o civ_relations.o tile_yields.o tile_working.o std_add_helper.o worker_helper.o city_array.o \
    general_bit_bank.o general_assessor.o effect_ctx.o effect_enabler.o booster_effect_register.o \
    local_unit_exp_booster_register.o civ_ship_training_booster_register.o city_commerce_booster_register.o \
    city_production_booster_register.o local_production_booster_register.o local_pop_growth_booster_register.o \
    local_commerce_booster_register.o city_pop_growth_booster_register.o civ_pop_growth_booster_register.o \
    city_culture_booster_register.o city.o city_tile_manager.o circular_tile_areas.o city_border.o \
    city_network.o city_connector.o city_connector_tester.o
