#!/bin/bash

LIB_SO="../../data_io/runtime_static_loader_lib.so"
if [ ! -f "$LIB_SO" ]; then
    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
    exit 1
fi

INC="-I. -I.. -I../.. -I../../game -I../../map_loader -I../../simple_map_gen -I../../misc -I../../data_io -I../../static_state"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_loader.cpp -o map_loader.o
g++ $CXXFLAGS $INC -c ../../game/runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c ../../game/game_array_simple.cpp -o game_array_simple.o
g++ $CXXFLAGS $INC -c ../../game/factory_game_array_simple.cpp -o factory_game_array_simple.o
g++ $CXXFLAGS $INC -c ../../misc/map_bit_overlay.cpp -o map_bit_overlay.o
g++ $CXXFLAGS $INC -c walk_coast_mk1.cpp -o walk_coast_mk1.o
g++ $CXXFLAGS $INC -c walk_coast_mk1_tester.cpp -o walk_coast_mk1_tester.o

g++ $CXXFLAGS -o walk_coast_mk1_tester \
    runtime_static_loader.o \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    runtime_trace_dbg.o \
    game_array_simple.o \
    factory_game_array_simple.o \
    map_bit_overlay.o \
    walk_coast_mk1.o \
    walk_coast_mk1_tester.o \
    -ldl \
    $LIB_SO \
    -Wl,-rpath,'$ORIGIN/../../data_io'

rm runtime_static_loader.o map_terrain_validate.o map_terrain_data.o map_loader.o runtime_trace_dbg.o \
    game_array_simple.o factory_game_array_simple.o map_bit_overlay.o \
    walk_coast_mk1.o walk_coast_mk1_tester.o
