#!/bin/bash
set -e

cd "$(dirname "$0")"

./city_air_defense_booster_register_comp

./city_air_range_booster_register_comp

./city_commerce_booster_register_comp

./city_corruption_booster_register_comp

./city_culture_booster_register_comp

./city_defense_booster_register_comp

./city_espionage_booster_register_comp

./city_happiness_booster_register_comp

./civ_movement_booster_register_comp

./city_nuke_defense_booster_register_comp

./city_pollution_booster_register_comp

./city_pop_growth_booster_register_comp

./civ_pop_growth_booster_register_comp

./city_production_booster_register_comp

./city_science_booster_register_comp

./city_sea_trade_booster_register_comp

./city_ship_defense_booster_register_comp

./civ_ship_movement_booster_register_comp

./civ_ship_training_booster_register_comp

./local_unit_exp_booster_register_comp

./civ_upgrade_cost_booster_register_comp

./civ_war_wear_booster_register_comp

