//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - AUTO-GENERATED by generate_booster_registers.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include "city_culture_booster_register.h"

//================================================================================================================================
//=> - CityCultureBoosterRegister data -
//================================================================================================================================

const BoosterRegisterEntry CityCultureBoosterRegister::s_entry[49] = {
    { { EffectEnablerKind::BUILDING, 2 }, 3, 0 }, // Library (building)
    { { EffectEnablerKind::BUILDING, 3 }, 2, 0 }, // Temple (building)
    { { EffectEnablerKind::BUILDING, 9 }, 3, 0 }, // Cathedral (building)
    { { EffectEnablerKind::BUILDING, 10 }, 4, 0 }, // University (building)
    { { EffectEnablerKind::BUILDING, 11 }, 2, 0 }, // Colosseum (building)
    { { EffectEnablerKind::BUILDING, 22 }, 2, 0 }, // Research Lab (building)
    { { EffectEnablerKind::SMALL_WONDER, 0 }, 2, 0 }, // Palace (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 1 }, 1, 0 }, // Forbidden Palace (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 2 }, 3, 0 }, // Military Academy (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 3 }, 3, 0 }, // Pentagon (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 4 }, 3, 0 }, // Battlefield Medicine (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 5 }, 3, 0 }, // Wall Street (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 7 }, 3, 0 }, // Apollo Program (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 8 }, 3, 0 }, // Ironworks (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 9 }, 3, 0 }, // National College (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 10 }, 3, 0 }, // National Epic (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 11 }, 3, 0 }, // Heroic Epic (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 12 }, 3, 0 }, // Oxford University (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 13 }, 3, 0 }, // Hermitage (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 14 }, 3, 0 }, // Circus Maximus (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 15 }, 3, 0 }, // East India Company (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 16 }, 3, 0 }, // National Intelligence Agency (small_wonder)
    { { EffectEnablerKind::SMALL_WONDER, 17 }, 3, 0 }, // Red Cross (small_wonder)
    { { EffectEnablerKind::WONDER, 0 }, 4, 0 }, // Pyramids (wonder)
    { { EffectEnablerKind::WONDER, 1 }, 6, 0 }, // Great Library (wonder)
    { { EffectEnablerKind::WONDER, 2 }, 4, 0 }, // Hanging Gardens (wonder)
    { { EffectEnablerKind::WONDER, 3 }, 3, 0 }, // Colossus (wonder)
    { { EffectEnablerKind::WONDER, 4 }, 2, 0 }, // Great Lighthouse (wonder)
    { { EffectEnablerKind::WONDER, 5 }, 4, 0 }, // Oracle (wonder)
    { { EffectEnablerKind::WONDER, 6 }, 2, 0 }, // Great Wall (wonder)
    { { EffectEnablerKind::WONDER, 7 }, 4, 0 }, // Statue of Zeus (wonder)
    { { EffectEnablerKind::WONDER, 8 }, 2, 0 }, // Sun Tzu's Art of War (wonder)
    { { EffectEnablerKind::WONDER, 9 }, 2, 0 }, // Leonardo's Workshop (wonder)
    { { EffectEnablerKind::WONDER, 10 }, 2, 0 }, // Knights Templar (wonder)
    { { EffectEnablerKind::WONDER, 11 }, 3, 0 }, // Magellan's Voyage (wonder)
    { { EffectEnablerKind::WONDER, 12 }, 4, 0 }, // Copernicus' Observatory (wonder)
    { { EffectEnablerKind::WONDER, 13 }, 6, 0 }, // Shakespeare's Theatre (wonder)
    { { EffectEnablerKind::WONDER, 14 }, 6, 0 }, // Newton's University (wonder)
    { { EffectEnablerKind::WONDER, 15 }, 5, 0 }, // J.S. Bach's Cathedral (wonder)
    { { EffectEnablerKind::WONDER, 16 }, 3, 0 }, // Adam Smith's Trading Company (wonder)
    { { EffectEnablerKind::WONDER, 17 }, 3, 0 }, // Darwin's Voyage (wonder)
    { { EffectEnablerKind::WONDER, 19 }, 4, 0 }, // Eiffel Tower (wonder)
    { { EffectEnablerKind::WONDER, 20 }, 3, 0 }, // Hoover Dam (wonder)
    { { EffectEnablerKind::WONDER, 21 }, 4, 0 }, // United Nations (wonder)
    { { EffectEnablerKind::WONDER, 22 }, 3, 0 }, // SETI Program (wonder)
    { { EffectEnablerKind::WONDER, 23 }, 4, 0 }, // Cure for Cancer (wonder)
    { { EffectEnablerKind::WONDER, 24 }, 3, 0 }, // Longevity (wonder)
    { { EffectEnablerKind::WONDER, 25 }, 2, 0 }, // Manhattan Project (wonder)
    { { EffectEnablerKind::WONDER, 26 }, 3, 0 }, // Apollo Program (wonder)
};

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
