//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - AUTO-GENERATED by generate_booster_registers.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include "city_science_booster_register.h"

//================================================================================================================================
//=> - CityScienceBoosterRegister data -
//================================================================================================================================

const BoosterRegisterEntry CityScienceBoosterRegister::s_entry[8] = {
    { { EffectEnablerKind::BUILDING, 2 }, 0, 50 }, // Library (building)
    { { EffectEnablerKind::BUILDING, 10 }, 0, 100 }, // University (building)
    { { EffectEnablerKind::BUILDING, 22 }, 0, 200 }, // Research Lab (building)
    { { EffectEnablerKind::SMALL_WONDER, 12 }, 0, 100 }, // Oxford University (small_wonder)
    { { EffectEnablerKind::WONDER, 5 }, 0, 100 }, // Oracle (wonder)
    { { EffectEnablerKind::WONDER, 12 }, 0, 100 }, // Copernicus' Observatory (wonder)
    { { EffectEnablerKind::WONDER, 14 }, 0, 100 }, // Newton's University (wonder)
    { { EffectEnablerKind::WONDER, 22 }, 0, 200 }, // SETI Program (wonder)
};

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
