//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - AUTO-GENERATED by generate_booster_registers.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include "city_production_booster_register.h"

//================================================================================================================================
//=> - CityProductionBoosterRegister data -
//================================================================================================================================

const BoosterRegisterEntry CityProductionBoosterRegister::s_entry[7] = {
    { { EffectEnablerKind::BUILDING, 23 }, 0, 50 }, // Factory (building)
    { { EffectEnablerKind::BUILDING, 32 }, 2, 0 }, // Waterworks (building)
    { { EffectEnablerKind::BUILDING, 43 }, 0, 150 }, // Manufacturing Plant (building)
    { { EffectEnablerKind::BUILDING, 49 }, 0, 20 }, // Offshore Platform (building)
    { { EffectEnablerKind::BUILDING, 52 }, 0, 100 }, // Solar Plant (building)
    { { EffectEnablerKind::BUILDING, 53 }, 0, 50 }, // Capitalization (building)
    { { EffectEnablerKind::SMALL_WONDER, 8 }, 0, 200 }, // Ironworks (small_wonder)
};

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
