#!/bin/bash
set -e

cd "$(dirname "$0")"

LIB_SO="../../data_io/runtime_static_loader_lib.so"
if [ ! -f "$LIB_SO" ]; then
    echo "missing $LIB_SO - run ../../data_io/runtime_static_loader_lib_comp first"
    exit 1
fi

INC="-I../../ \
     -I../../misc \
     -I../../data_io \
     -I../../static_state \
     -I../../city \
     -I../../city/effector \
     -I../../city/assessor \
     -I../../gen_bit_banks \
     -I../../game \
     -I../../dyn_state \
     -I../../map_loader \
     -I../../adv_map_gen \
     -I../../simple_map_gen \
     -I../../ai_pathing/walk_general"
CXXFLAGS="-std=c++17 -Wall -Wextra"

CITY_REG_CPP="local_unit_exp_booster_register.cpp civ_ship_training_booster_register.cpp city_commerce_booster_register.cpp city_production_booster_register.cpp city_pop_growth_booster_register.cpp civ_pop_growth_booster_register.cpp city_culture_booster_register.cpp local_commerce_booster_register.cpp local_pop_growth_booster_register.cpp local_production_booster_register.cpp local_culture_booster_register.cpp local_sanitation_booster_register.cpp city_sanitation_booster_register.cpp civ_sanitation_booster_register.cpp"

g++ $CXXFLAGS $INC -c ../../data_io/item_effect_helpers.cpp -o item_effect_helpers.o
g++ $CXXFLAGS $INC -c ../../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
g++ $CXXFLAGS $INC -c ../../misc/bit_array.cpp -o bit_array.o
g++ $CXXFLAGS $INC -c ../../misc/map_bit_overlay.cpp -o map_bit_overlay.o
g++ $CXXFLAGS $INC -c ../../misc/map_bit_array_overlay.cpp -o map_bit_array_overlay.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ $CXXFLAGS $INC -c ../../map_loader/map_loader.cpp -o map_loader.o
g++ $CXXFLAGS $INC -c ../../game/runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c ../../gen_bit_banks/general_bit_bank.cpp -o general_bit_bank.o
g++ $CXXFLAGS $INC -c ../../city/assessor/general_assessor.cpp -o general_assessor.o
g++ $CXXFLAGS $INC -c ../../dyn_state/fort_add_vector.cpp -o fort_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/mine_add_vector.cpp -o mine_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/monastery_add_vector.cpp -o monastery_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/outpost_add_vector.cpp -o outpost_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/plantation_add_vector.cpp -o plantation_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/shipyard_add_vector.cpp -o shipyard_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/trade_post_add_vector.cpp -o trade_post_add_vector.o
g++ $CXXFLAGS $INC -c ../../dyn_state/unit_add_vector.cpp -o unit_add_vector.o
g++ $CXXFLAGS $INC -c ../../ai_pathing/walk_general/sector_network.cpp -o sector_network.o
g++ $CXXFLAGS $INC -c ../../ai_pathing/walk_general/sector_network_router.cpp -o sector_network_router.o
g++ $CXXFLAGS $INC -c ../../dyn_state/unit_movement_mng.cpp -o unit_movement_mng.o
g++ $CXXFLAGS $INC -c ../../game/tile_attr_tables.cpp -o tile_attr_tables.o
g++ $CXXFLAGS $INC -c ../../game/game_array_simple.cpp -o game_array_simple.o
g++ $CXXFLAGS $INC -c ../../game/combat_mods.cpp -o combat_mods.o
g++ $CXXFLAGS $INC -c ../../game/game_state.cpp -o game_state.o
g++ $CXXFLAGS $INC -c ../../game/player_ledger.cpp -o player_ledger.o
g++ $CXXFLAGS $INC -c ../../game/civ_relations.cpp -o civ_relations.o
g++ $CXXFLAGS $INC -c ../../game/tile_yields.cpp -o tile_yields.o
g++ $CXXFLAGS $INC -c ../../game/tile_working.cpp -o tile_working.o
g++ $CXXFLAGS $INC -c ../../game/city_array.cpp -o city_array.o
g++ $CXXFLAGS $INC -c ../../city/circular_tile_areas.cpp -o circular_tile_areas.o
g++ $CXXFLAGS $INC -c ../../city/city_border.cpp -o city_border.o
g++ $CXXFLAGS $INC -c ../../city/city_tile_manager.cpp -o city_tile_manager.o
g++ $CXXFLAGS $INC -c ../../city/city.cpp -o city.o
g++ $CXXFLAGS $INC -c ../../city/effect_ctx.cpp -o effect_ctx.o
g++ $CXXFLAGS $INC -c effect_enabler.cpp -o effect_enabler.o
g++ $CXXFLAGS $INC -c booster_effect_register.cpp -o booster_effect_register.o
for c in $CITY_REG_CPP; do
    g++ $CXXFLAGS $INC -c "$c" -o "${c%.cpp}.o"
done
g++ $CXXFLAGS $INC -c dyn_produce_pay_tester.cpp -o dyn_produce_pay_tester.o

LINK_REGS=""
for c in $CITY_REG_CPP; do
    LINK_REGS="$LINK_REGS ${c%.cpp}.o"
done

g++ $CXXFLAGS -o dyn_produce_pay_tester \
    item_effect_helpers.o \
    runtime_static_loader.o \
    bit_array.o \
    map_bit_overlay.o \
    map_bit_array_overlay.o \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    runtime_trace_dbg.o \
    general_bit_bank.o \
    general_assessor.o \
    fort_add_vector.o \
    mine_add_vector.o \
    monastery_add_vector.o \
    outpost_add_vector.o \
    plantation_add_vector.o \
    shipyard_add_vector.o \
    trade_post_add_vector.o \
    unit_add_vector.o \
    sector_network.o \
    sector_network_router.o \
    unit_movement_mng.o \
    tile_attr_tables.o \
    game_array_simple.o \
    combat_mods.o \
    game_state.o \
    player_ledger.o \
    civ_relations.o \
    tile_yields.o \
    tile_working.o \
    city_array.o \
    circular_tile_areas.o \
    city_border.o \
    city_tile_manager.o \
    city.o \
    effect_ctx.o \
    effect_enabler.o \
    booster_effect_register.o \
    $LINK_REGS \
    \
    dyn_produce_pay_tester.o \
    -ldl \
    $LIB_SO \
    -Wl,-rpath,'$ORIGIN/../../data_io'

if [ "$#" -ge 1 ]; then
    ./dyn_produce_pay_tester "$@"
else
    ./dyn_produce_pay_tester
fi

RM_REGS=""
for c in $CITY_REG_CPP; do
    RM_REGS="$RM_REGS ${c%.cpp}.o"
done

rm item_effect_helpers.o runtime_static_loader.o bit_array.o map_bit_overlay.o map_bit_array_overlay.o \
    map_terrain_validate.o map_terrain_data.o map_loader.o runtime_trace_dbg.o \
    general_bit_bank.o general_assessor.o \
    fort_add_vector.o mine_add_vector.o monastery_add_vector.o outpost_add_vector.o \
    plantation_add_vector.o shipyard_add_vector.o trade_post_add_vector.o \
    unit_add_vector.o sector_network.o sector_network_router.o \
    unit_movement_mng.o tile_attr_tables.o \
    game_array_simple.o combat_mods.o game_state.o player_ledger.o civ_relations.o \
    tile_yields.o tile_working.o city_array.o circular_tile_areas.o city_border.o \
    city_tile_manager.o city.o \
    effect_ctx.o effect_enabler.o booster_effect_register.o \
    $RM_REGS \
