//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - AUTO-GENERATED by generate_job_slot_register.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include "job_slot_register.h"

#include "bit_array.h"
#include "effect_ctx.h"
#include "general_bit_bank.h"

//================================================================================================================================
//=> - JobSlotRegister data -
//================================================================================================================================

const JobSlotEntry JobSlotRegister::s_entry[12] = {
    { { EffectEnablerKind::BUILDING, 5 }, 0, 1, ItemEffectsScope::CITY, ItemEffectAmountMode::COUNT }, // Temple (building) -> Priest
    { { EffectEnablerKind::BUILDING, 20 }, 1, 1, ItemEffectsScope::CITY, ItemEffectAmountMode::COUNT }, // Colosseum (building) -> Entertainer
    { { EffectEnablerKind::BUILDING, 4 }, 2, 1, ItemEffectsScope::CITY, ItemEffectAmountMode::COUNT }, // Amphitheater (building) -> Artist
    { { EffectEnablerKind::BUILDING, 18 }, 2, 1, ItemEffectsScope::CITY, ItemEffectAmountMode::COUNT }, // Cathedral (building) -> Artist
    { { EffectEnablerKind::BUILDING, 6 }, 4, 1, ItemEffectsScope::CITY, ItemEffectAmountMode::COUNT }, // Marketplace (building) -> Merchant
    { { EffectEnablerKind::BUILDING, 25 }, 4, 1, ItemEffectsScope::CITY, ItemEffectAmountMode::COUNT }, // Commercial Dock (building) -> Merchant
    { { EffectEnablerKind::BUILDING, 3 }, 5, 1, ItemEffectsScope::CITY, ItemEffectAmountMode::COUNT }, // Library (building) -> Librarian
    { { EffectEnablerKind::BUILDING, 19 }, 6, 1, ItemEffectsScope::CITY, ItemEffectAmountMode::COUNT }, // University (building) -> Academic
    { { EffectEnablerKind::BUILDING, 21 }, 9, 1, ItemEffectsScope::CITY, ItemEffectAmountMode::COUNT }, // Factory (building) -> Civil Engineer
    { { EffectEnablerKind::BUILDING, 21 }, 10, 1, ItemEffectsScope::CITY, ItemEffectAmountMode::COUNT }, // Factory (building) -> Technician
    { { EffectEnablerKind::BUILDING, 22 }, 11, 2, ItemEffectsScope::CITY, ItemEffectAmountMode::COUNT }, // Police Station (building) -> Policeman
    { { EffectEnablerKind::BUILDING, 9 }, 12, 1, ItemEffectsScope::CITY, ItemEffectAmountMode::COUNT }, // Cesspools (building) -> Dung Collector
};

const u16 JobSlotRegister::s_off[15] = {
    0, 1, 2, 4, 4, 6, 7, 8, 8, 8, 9, 10, 11, 12, 12
};

//================================================================================================================================
//=> - JobSlotRegister helpers -
//================================================================================================================================

static bool job_slot_src_active (const EffectEnabler& en, const EffectCtx& ctx) {
    switch (en.m_kind) {
    case EffectEnablerKind::BUILDING:
        if (ctx.m_bld_bank == nullptr) {
            return false;
        }
        return ctx.m_bld_bank->is_flagged(ctx.m_city_idx, en.m_idx);
    case EffectEnablerKind::TECH:
        if (ctx.m_tech == nullptr || en.m_idx >= ctx.m_tech->get_count()) {
            return false;
        }
        return ctx.m_tech->get_bit(en.m_idx) == 1;
    case EffectEnablerKind::SMALL_WONDER:
        if (ctx.m_small_wonder_city == nullptr || en.m_idx >= ctx.m_small_wonder_n) {
            return false;
        }
        return ctx.m_small_wonder_city[en.m_idx] == ctx.m_city_idx;
    case EffectEnablerKind::WONDER:
        if (ctx.m_wonder_city == nullptr || en.m_idx >= ctx.m_wonder_n) {
            return false;
        }
        return ctx.m_wonder_city[en.m_idx] == ctx.m_city_idx;
    default:
        return false;
    }
}

static i16 add_i16_sat (i16 a, i16 b) {
    const i32 next = static_cast<i32>(a) + static_cast<i32>(b);
    if (next < -32768) {
        return -32768;
    }
    if (next > 32767) {
        return 32767;
    }
    return static_cast<i16>(next);
}

//================================================================================================================================
//=> - JobSlotRegister implementation -
//================================================================================================================================

i16 JobSlotRegister::bonus (u16 job_id, u16 base_slots, const EffectCtx& ctx) {
    if (job_id >= JOB_N || ENTRY_N == 0) {
        return 0;
    }
    const u16 begin = s_off[job_id];
    const u16 end = s_off[job_id + 1u];
    i16 sum = 0;
    for (u16 i = begin; i < end; ++i) {
        const JobSlotEntry& e = s_entry[i];
        if (!job_slot_src_active(e.m_enabler, ctx)) {
            continue;
        }
        if (e.m_mode == ItemEffectAmountMode::PERCENTAGE) {
            const i32 part = (static_cast<i32>(base_slots) * static_cast<i32>(e.m_amount)) / 100;
            sum = add_i16_sat(sum, static_cast<i16>(part));
            continue;
        }
        sum = add_i16_sat(sum, e.m_amount);
    }
    return sum;
}

u16 JobSlotRegister::capacity (u16 job_id, u16 base_slots, const EffectCtx& ctx) {
    const i32 total = static_cast<i32>(base_slots) + static_cast<i32>(bonus(job_id, base_slots, ctx));
    if (total <= 0) {
        return 0;
    }
    if (total > 65535) {
        return 65535;
    }
    return static_cast<u16>(total);
}

const JobSlotEntry* JobSlotRegister::entries () {
    return s_entry;
}

u16 JobSlotRegister::entry_count () {
    return ENTRY_N;
}

u16 JobSlotRegister::job_count () {
    return JOB_N;
}

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
