//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - AUTO-GENERATED by generate_produce_register.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include "produce_register.h"

#include "bit_array.h"
#include "effect_ctx.h"
#include "general_bit_bank.h"

#include <cstring>

//================================================================================================================================
//=> - ProduceRegister data -
//================================================================================================================================

const ProduceGroup ProduceRegister::s_group[5] = {
    { { EffectEnablerKind::BUILDING, 36 }, 2, {
        { ItemProduceKind::YIELD, 3, 10 }, // yield PRODUCTION
        { ItemProduceKind::RESOURCE, 10, -1 }, // resource Coal
    } }, // Coal Plant (building)
    { { EffectEnablerKind::BUILDING, 37 }, 2, {
        { ItemProduceKind::YIELD, 3, 20 }, // yield PRODUCTION
        { ItemProduceKind::RESOURCE, 9, -1 }, // resource Oil
    } }, // Oil Plant (building)
    { { EffectEnablerKind::BUILDING, 38 }, 1, {
        { ItemProduceKind::YIELD, 3, 20 }, // yield PRODUCTION
    } }, // Hydro Plant (building)
    { { EffectEnablerKind::BUILDING, 39 }, 2, {
        { ItemProduceKind::YIELD, 3, 50 }, // yield PRODUCTION
        { ItemProduceKind::RESOURCE, 6, -1 }, // resource Uranium
    } }, // Nuclear Plant (building)
    { { EffectEnablerKind::SMALL_WONDER, 8 }, 1, {
        { ItemProduceKind::RESOURCE, 2, 2 }, // resource Iron
    } }, // Ironworks (small_wonder)
};

//================================================================================================================================
//=> - ProduceRegister helpers -
//================================================================================================================================

static bool produce_src_active (const EffectEnabler& en, const EffectCtx& ctx) {
    switch (en.m_kind) {
    case EffectEnablerKind::BUILDING:
        if (ctx.m_bld_bank == nullptr) {
            return false;
        }
        return ctx.m_bld_bank->is_flagged(ctx.m_city_idx, en.m_idx);
    case EffectEnablerKind::TECH:
        if (ctx.m_tech == nullptr || en.m_idx >= ctx.m_tech->get_count()) {
            return false;
        }
        return ctx.m_tech->get_bit(en.m_idx) == 1;
    case EffectEnablerKind::SMALL_WONDER:
        if (ctx.m_small_wonder_city == nullptr || en.m_idx >= ctx.m_small_wonder_n) {
            return false;
        }
        return ctx.m_small_wonder_city[en.m_idx] == ctx.m_city_idx;
    case EffectEnablerKind::WONDER:
        if (ctx.m_wonder_city == nullptr || en.m_idx >= ctx.m_wonder_n) {
            return false;
        }
        return ctx.m_wonder_city[en.m_idx] == ctx.m_city_idx;
    default:
        return false;
    }
}

static void clamp_i16_arr (i16* v, u16 n) {
    for (u16 i = 0; i < n; ++i) {
        if (v[i] < 0) {
            v[i] = 0;
        }
    }
}

static void add_i16_sat (i16& dst, i16 delta) {
    const i32 next = static_cast<i32>(dst) + static_cast<i32>(delta);
    if (next < -32768) {
        dst = -32768;
    } else if (next > 32767) {
        dst = 32767;
    } else {
        dst = static_cast<i16>(next);
    }
}

static bool group_can_pay (const ProduceGroup& g, const ProduceRegister::Inventory& inv) {
    i16 need[ProduceRegister::INV_N];
    std::memset(need, 0, sizeof(need));
    for (u8 s = 0; s < g.m_slot_n; ++s) {
        const ProduceSlot& sl = g.m_slots[s];
        if (sl.m_kind != ItemProduceKind::RESOURCE || sl.m_amount >= 0) {
            continue;
        }
        if (sl.m_target >= ProduceRegister::INV_N) {
            return false;
        }
        add_i16_sat(need[sl.m_target], static_cast<i16>(-sl.m_amount));
    }
    for (u16 i = 0; i < ProduceRegister::INV_N; ++i) {
        if (need[i] > 0 && inv.m_v[i] < need[i]) {
            return false;
        }
    }
    return true;
}

static void apply_slot (ProduceRegister::Inventory& inv, ProduceRegister::CityYields& yld, const ProduceSlot& sl) {
    if (sl.m_kind == ItemProduceKind::RESOURCE) {
        if (sl.m_target >= ProduceRegister::INV_N) {
            return;
        }
        add_i16_sat(inv.m_v[sl.m_target], sl.m_amount);
        return;
    }
    if (sl.m_kind == ItemProduceKind::YIELD) {
        if (sl.m_target == 0 || sl.m_target >= ProduceRegister::YIELD_N) {
            return;
        }
        add_i16_sat(yld.m_v[sl.m_target], sl.m_amount);
    }
}

//================================================================================================================================
//=> - ProduceRegister implementation -
//================================================================================================================================

void ProduceRegister::clear (Inventory& inv) {
    std::memset(inv.m_v, 0, sizeof(inv.m_v));
}

void ProduceRegister::clear (CityYields& yld) {
    std::memset(yld.m_v, 0, sizeof(yld.m_v));
}

void ProduceRegister::apply (Inventory& inv, CityYields& yld, const EffectCtx& ctx) {
    if (GROUP_N == 0) {
        clamp_i16_arr(inv.m_v, INV_N);
        clamp_i16_arr(yld.m_v, YIELD_N);
        return;
    }
    for (u16 i = 0; i < GROUP_N; ++i) {
        const ProduceGroup& g = s_group[i];
        if (!produce_src_active(g.m_enabler, ctx)) {
            continue;
        }
        if (!group_can_pay(g, inv)) {
            continue;
        }
        for (u8 s = 0; s < g.m_slot_n; ++s) {
            apply_slot(inv, yld, g.m_slots[s]);
        }
    }
    clamp_i16_arr(inv.m_v, INV_N);
    clamp_i16_arr(yld.m_v, YIELD_N);
}

const ProduceGroup* ProduceRegister::groups () {
    return s_group;
}

u16 ProduceRegister::group_count () {
    return GROUP_N;
}

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
