//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - AUTO-GENERATED by generate_produce_register.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Includes -
//================================================================================================================================

#include <cctype>
#include <cstdio>
#include <cstring>

#include "building_static_key.h"
#include "item_effect_helpers.h"
#include "produce_register.h"
#include "resource_static_key.h"
#include "runtime_static_loader.h"
#include "small_wonder_static_key.h"
#include "tech_static_key.h"
#include "wonder_static_key.h"

//================================================================================================================================
//=> - Locals -
//================================================================================================================================

static RuntimeStaticLoader g_rt_loader;

static void lower_copy (char* dst, cstr src, u32 dst_n) {
    if (dst_n == 0) {
        return;
    }
    u32 i = 0;
    if (src != nullptr) {
        for (; src[i] != '\0' && i + 1 < dst_n; ++i) {
            dst[i] = static_cast<char>(std::tolower(static_cast<unsigned char>(src[i])));
        }
    }
    dst[i] = '\0';
}

static void upper_copy (char* dst, cstr src, u32 dst_n) {
    if (dst_n == 0) {
        return;
    }
    u32 i = 0;
    if (src != nullptr) {
        for (; src[i] != '\0' && i + 1 < dst_n; ++i) {
            dst[i] = static_cast<char>(std::toupper(static_cast<unsigned char>(src[i])));
        }
    }
    dst[i] = '\0';
}

static bool name_eq_ci (cstr a, cstr b) {
    char al[96];
    char bl[96];
    lower_copy(al, a, sizeof(al));
    lower_copy(bl, b, sizeof(bl));
    return std::strcmp(al, bl) == 0;
}

static cstr kind_label (EffectEnablerKind k) {
    switch (k) {
    case EffectEnablerKind::BUILDING: return "building";
    case EffectEnablerKind::TECH: return "tech";
    case EffectEnablerKind::SMALL_WONDER: return "small_wonder";
    case EffectEnablerKind::WONDER: return "wonder";
    default: return "?";
    }
}

static cstr host_name (const RuntimeStatics& st, const EffectEnabler& en) {
    switch (en.m_kind) {
    case EffectEnablerKind::BUILDING:
        if (en.m_idx < st.building().get_item_count()) {
            return st.building().get_name(BuildingStaticDataKey::from_raw(en.m_idx));
        }
        break;
    case EffectEnablerKind::TECH:
        if (en.m_idx < st.tech().get_item_count()) {
            return st.tech().get_name(TechStaticDataKey::from_raw(en.m_idx));
        }
        break;
    case EffectEnablerKind::SMALL_WONDER:
        if (en.m_idx < st.small_wonder().get_item_count()) {
            return st.small_wonder().get_name(SmallWonderStaticDataKey::from_raw(en.m_idx));
        }
        break;
    case EffectEnablerKind::WONDER:
        if (en.m_idx < st.wonder().get_item_count()) {
            return st.wonder().get_name(WonderStaticDataKey::from_raw(en.m_idx));
        }
        break;
    default:
        break;
    }
    return "<unknown>";
}

static void print_slot_hit (const RuntimeStatics& st, const ProduceGroup& g, const ProduceSlot& sl) {
    if (sl.m_kind == ItemProduceKind::YIELD) {
        std::printf("  %s %s -> yield %s amount=%d\n",
            kind_label(g.m_enabler.m_kind),
            host_name(st, g.m_enabler),
            ItemEffectHelper::produce_yield_enum_to_str(static_cast<ItemProduceYield>(sl.m_target)),
            static_cast<int>(sl.m_amount));
        return;
    }
    cstr res_nm = "<unknown>";
    if (sl.m_target < st.resource().get_item_count()) {
        res_nm = st.resource().get_name(ResourceStaticDataKey::from_raw(sl.m_target));
    }
    std::printf("  %s %s -> resource %s amount=%d\n",
        kind_label(g.m_enabler.m_kind),
        host_name(st, g.m_enabler),
        res_nm,
        static_cast<int>(sl.m_amount));
}

//================================================================================================================================
//=> - Main -
//================================================================================================================================

int main (int argc, char** argv) {
    if (argc < 2) {
        std::printf("usage: %s <resource_or_yield_name>\n", argv[0] != nullptr ? argv[0] : "produce_register_tester");
        return 1;
    }
    if (!g_rt_loader.load("../../data_io/runtime_static_loader_lib.so", "../../")) {
        std::printf("ERROR: failed to load runtime statics\n");
        return 1;
    }
    RuntimeStatics& st = g_rt_loader.statics();

    ItemProduceKind match_kind = ItemProduceKind::NONE;
    u16 match_target = U16_KEY_NULL;
    char yld_key[96];
    upper_copy(yld_key, argv[1], sizeof(yld_key));
    const ItemProduceYield yld = ItemEffectHelper::produce_yield_str_to_enum(yld_key);
    if (yld != ItemProduceYield::NONE) {
        match_kind = ItemProduceKind::YIELD;
        match_target = static_cast<u16>(yld);
    } else {
        const u16 res_n = st.resource().get_item_count();
        for (u16 i = 0; i < res_n; ++i) {
            cstr nm = st.resource().get_name(ResourceStaticDataKey::from_raw(i));
            if (name_eq_ci(nm, argv[1])) {
                match_kind = ItemProduceKind::RESOURCE;
                match_target = i;
                break;
            }
        }
    }
    if (match_kind == ItemProduceKind::NONE) {
        std::printf("ERROR: unknown resource/yield '%s'\n", argv[1]);
        return 1;
    }

    if (match_kind == ItemProduceKind::YIELD) {
        std::printf("PRODUCE register reverse scan for yield '%s' (id=%u)\n",
            ItemEffectHelper::produce_yield_enum_to_str(static_cast<ItemProduceYield>(match_target)),
            static_cast<u32>(match_target));
    } else {
        cstr res_nm = st.resource().get_name(ResourceStaticDataKey::from_raw(match_target));
        std::printf("PRODUCE register reverse scan for resource '%s' (idx=%u)\n", res_nm, static_cast<u32>(match_target));
    }
    std::printf("groups: %u  inventory slots: %u  yield slots: %u\n",
        static_cast<u32>(ProduceRegister::group_count()),
        static_cast<u32>(ProduceRegister::INV_N),
        static_cast<u32>(ProduceRegister::YIELD_N));

    const ProduceGroup* rows = ProduceRegister::groups();
    const u16 n = ProduceRegister::group_count();
    u32 hits = 0;
    for (u16 i = 0; i < n; ++i) {
        const ProduceGroup& g = rows[i];
        for (u8 s = 0; s < g.m_slot_n; ++s) {
            const ProduceSlot& sl = g.m_slots[s];
            if (sl.m_kind != match_kind || sl.m_target != match_target) {
                continue;
            }
            ++hits;
            print_slot_hit(st, g, sl);
        }
    }
    if (hits == 0) {
        std::printf("  (no producers)\n");
    }
    std::printf("hits: %u\n", hits);
    return 0;
}

//================================================================================================================================
//=> - End -
//================================================================================================================================
