#!/bin/bash

# Define the include path for the compiler
INC="-I.."

# Compile objects
g++ $INC -c [MEMBER_TAG]_bit_bank.cpp -o [MEMBER_TAG]_bit_bank.o
g++ $INC -c [MEMBER_TAG]_bit_bank_tester.cpp -o [MEMBER_TAG]_bit_bank_tester.o
g++ $INC -c [MEMBER_TAG]_bit_bank_major1_tester.cpp -o [MEMBER_TAG]_bit_bank_major1_tester.o
g++ $INC -c [MEMBER_TAG]_bit_bank_major2_tester.cpp -o [MEMBER_TAG]_bit_bank_major2_tester.o
g++ $INC -c [MEMBER_TAG]_bit_bank_visual1_tester.cpp -o [MEMBER_TAG]_bit_bank_visual1_tester.o

# Link everything into the final tester
g++ -o [MEMBER_TAG]_bit_bank_tester [MEMBER_TAG]_bit_bank.o [MEMBER_TAG]_bit_bank_tester.o
g++ -o [MEMBER_TAG]_bit_bank_major1_tester [MEMBER_TAG]_bit_bank.o [MEMBER_TAG]_bit_bank_major1_tester.o
g++ -o [MEMBER_TAG]_bit_bank_major2_tester [MEMBER_TAG]_bit_bank.o [MEMBER_TAG]_bit_bank_major2_tester.o
g++ -o [MEMBER_TAG]_bit_bank_visual1_tester [MEMBER_TAG]_bit_bank.o [MEMBER_TAG]_bit_bank_visual1_tester.o

# Clean up
rm \
    [MEMBER_TAG]_bit_bank.o \
    [MEMBER_TAG]_bit_bank_tester.o \
    [MEMBER_TAG]_bit_bank_major1_tester.o \
    [MEMBER_TAG]_bit_bank_major2_tester.o \
    [MEMBER_TAG]_bit_bank_visual1_tester.o