//================================================================================================================================
//=> - WARNING -
//================================================================================================================================
//
//  - This file is AUTO-GENERATED by generate_dyn_state.py
//  - Do not edit this file manually.
//
//================================================================================================================================
//=> - Include guards -
//================================================================================================================================

#ifndef SHIPYARD_ADD_VECTOR_H
#define SHIPYARD_ADD_VECTOR_H

#include "shipyard_add_vector_key.h"
#include "game_primitives.h"
#include "shipyard_add_struct.h"

//================================================================================================================================
//=> - ShipyardAddVector class -
//================================================================================================================================

class ShipyardAddVector {
public:
    ShipyardAddVector();
    ~ShipyardAddVector();

    ShipyardAddStruct* get_shipyard_add(ShipyardAddKey key);
    const ShipyardAddStruct* get_shipyard_add(ShipyardAddKey key) const;
    ShipyardAddKey get_next_new_shipyard_add_key();

    void return_shipyard_add(ShipyardAddKey key);
    ShipyardAddStruct* get_page(u16 page_idx);
    const ShipyardAddStruct* get_page(u16 page_idx) const;
    u16 get_head_shipyard_add_idx () const;

    static const u16 MAX_PAGES = 256;
    static const u16 SHIPYARD_ADD_ITEMS_PER_PAGE = 256;

private:
    friend class ShipyardAddVectorTester;

    ShipyardAddStruct* m_pages[MAX_PAGES];
    u8* m_exists_pages[MAX_PAGES];
    u16 m_shipyard_add_count;
    u16 m_head_shipyard_add_idx;
    u16 m_page_count;

    u16* m_recycled_pages[MAX_PAGES];
    u16 m_recycled_shipyard_add_count;
    u16 m_recycled_page_count;
};

#endif // SHIPYARD_ADD_VECTOR_H

//================================================================================================================================
//=> - End of file -
//================================================================================================================================
