#!/bin/bash
set -e

cd "$(dirname "$0")"

LIB_SO="../data_io/runtime_static_loader_lib.so"
if [ ! -f "$LIB_SO" ]; then
    echo "missing $LIB_SO - run ../data_io/runtime_static_loader_lib_comp first"
    exit 1
fi

INC="-I../ \
     -I../misc \
     -I../data_io \
     -I../static_state \
     -I../city \
     -I../dyn_state \
     -I../gen_bit_banks \
     -I../game"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../data_io/runtime_static_loader.cpp -o runtime_static_loader.o
g++ $CXXFLAGS $INC -c ../misc/bit_array.cpp -o bit_array.o
g++ $CXXFLAGS $INC -c ../gen_bit_banks/general_bit_bank.cpp -o general_bit_bank.o
g++ $CXXFLAGS $INC -c ../city/general_assessor.cpp -o general_assessor.o
g++ $CXXFLAGS $INC -c ../dyn_state/unit_add_vector.cpp -o unit_add_vector.o
g++ $CXXFLAGS $INC -c player_ledger.cpp -o player_ledger.o
g++ $CXXFLAGS $INC -c ../city/city.cpp -o city.o
g++ $CXXFLAGS $INC -c city_array.cpp -o city_array.o
g++ $CXXFLAGS $INC -c city_array_tester.cpp -o city_array_tester.o

g++ $CXXFLAGS -o city_array_tester \
    runtime_static_loader.o \
    bit_array.o \
    general_bit_bank.o \
    general_assessor.o \
    unit_add_vector.o \
    player_ledger.o \
    city.o \
    city_array.o \
    city_array_tester.o \
    -ldl \
    $LIB_SO \
    -Wl,-rpath,'$ORIGIN/../data_io'

rm runtime_static_loader.o bit_array.o general_bit_bank.o general_assessor.o unit_add_vector.o player_ledger.o city.o city_array.o city_array_tester.o
