#!/bin/bash

INC="-I.. -I../map_loader -I../simple_map_gen"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ $CXXFLAGS $INC -c ../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ $CXXFLAGS $INC -c ../map_loader/map_loader.cpp -o map_loader.o
g++ $CXXFLAGS $INC -c ../map_loader/starting_point_generator.cpp -o starting_point_generator.o
g++ $CXXFLAGS $INC -c game_setup.cpp -o game_setup.o
g++ $CXXFLAGS $INC -c game_setup_tester.cpp -o game_setup_tester.o

g++ $CXXFLAGS -o game_setup_tester \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    starting_point_generator.o \
    game_setup.o \
    game_setup_tester.o

rm map_terrain_validate.o map_terrain_data.o map_loader.o \
    starting_point_generator.o game_setup.o game_setup_tester.o
