#!/bin/bash

INC="-I.. -I../map_loader -I../simple_map_gen"
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c ../map_loader/map_terrain_validate.cpp -o map_terrain_validate.o
g++ $CXXFLAGS $INC -c ../map_loader/map_terrain_data.cpp -o map_terrain_data.o
g++ $CXXFLAGS $INC -c ../map_loader/map_loader.cpp -o map_loader.o
g++ $CXXFLAGS $INC -c runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c game_array_simple.cpp -o game_array_simple.o
g++ $CXXFLAGS $INC -c factory_game_array_simple.cpp -o factory_game_array_simple.o
g++ $CXXFLAGS $INC -c game_array_simple_tester.cpp -o game_array_simple_tester.o

g++ $CXXFLAGS -o game_array_simple_tester \
    map_terrain_validate.o \
    map_terrain_data.o \
    map_loader.o \
    runtime_trace_dbg.o \
    game_array_simple.o \
    factory_game_array_simple.o \
    game_array_simple_tester.o

rm map_terrain_validate.o map_terrain_data.o map_loader.o runtime_trace_dbg.o \
    game_array_simple.o factory_game_array_simple.o game_array_simple_tester.o
