#!/bin/bash

INC="-I.."
CXXFLAGS="-std=c++17 -Wall -Wextra"

g++ $CXXFLAGS $INC -c runtime_trace_dbg.cpp -o runtime_trace_dbg.o
g++ $CXXFLAGS $INC -c runtime_trace_dbg_tester.cpp -o runtime_trace_dbg_tester.o

g++ $CXXFLAGS -o runtime_trace_dbg_tester \
    runtime_trace_dbg.o \
    runtime_trace_dbg_tester.o

rm runtime_trace_dbg.o runtime_trace_dbg_tester.o
